Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2018-08, with the labels that each got.

#709 Update config move.
  python-iml-manager.spec.in
Labels: bug

#704 Dockerize manager services
  .dockerignore
  .travis.yml
  base.dockerfile
  chroma-manager.conf.template
  chroma-manager.py
  chroma_core/lib/service_config.py
  chroma_core/management/commands/chroma_service.py
  chroma_core/management/commands/print-settings.py
  chroma_core/plugins/block_devices.py
  chroma_core/services/crypto.py
  chroma_core/services/http_agent/__init__.py
  corosync.dockerfile
  gunicorn.dockerfile
  http-agent.dockerfile
  iml-manager.target
  job-scheduler.dockerfile
  lustre-audit.dockerfile
  nginx.dockerfile
  plugin-runner.dockerfile
  power-control.dockerfile
  requirements.dev
  requirements.test
  requirements.txt
  settings.py
  setup.dockerfile
  stats.dockerfile
  syslog.dockerfile
  tests/framework/services/runner.sh
  tests/framework/utils/collect_reports.sh
Labels: enhancement

#711 Add back update_package in lustre_audit
  chroma_core/services/lustre_audit/update_scan.py
Labels: bug

#712 Add docker-compose.yml file
  .dockerignore
  docker-compose.yml
Labels: enhancement

#130 Add Notify triggers for relevant chroma_core_* tables.
  chroma_core/management/commands/print-settings.py
  chroma_core/migrations/0041_table_update_notify.py
Labels: pinned

#714 Add dep on git when building base dockerfile
  base.dockerfile
Labels: bug

#715 Add support for Lustre 2.10.5
  storage_server.repo.in
  tests/framework/utils/defaults.sh.in
Labels: enhancement

#713 Accept linux plugin device data
  chroma_agent_comms/views.py
  chroma_core/plugins/linux.py
  python-iml-manager.spec.in
Labels: bug

#722 IML container tuning
  chroma-manager.py
  chroma_core/services/rpc.py
  docker-compose.yml
Labels: bug
