Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2018-06, with the labels that each got.

#639 Add more service ordering
  chroma-manager/chroma_core/lib/service_config.py
  chroma-manager/iml-manager.target
Labels: enhancement

#616 Exported zpool disk partitions displayed as usable volumes
  chroma-manager/chroma_core/plugins/block_devices.py
  chroma-manager/chroma_core/plugins/linux.py
  chroma-manager/chroma_core/services/plugin_runner/resource_manager.py
Labels: bug

#655 Update favicon location
  chroma-manager/chroma-manager.conf.template
Labels: enhancement

#647 Fix migration issue.
  chroma-manager/chroma_core/migrations/0023_auto__add_unconfigurersyslogjob__add_getcorosyncstatejob__add_pacemake.py
  chroma-manager/chroma_core/migrations/0039_add_primary_umtm_stepresults.py
Labels: bug, pinned
