Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2018-02, with the labels that each got.

#443 Support Lustre 2.10.3
  chroma-manager/storage_server.repo
  chroma-manager/tests/framework/utils/defaults.sh
Labels: enhancement

#219 Replace chroma-agent init with systemd unit
  chroma-agent/.gitignore
  chroma-agent/Makefile
  chroma-agent/chroma-agent-init.sh
  chroma-agent/chroma-agent.service
  chroma-agent/chroma-agent.spec
  chroma-agent/chroma_agent/agent_daemon.py
  chroma-manager/agent-bootstrap-script.template
  chroma-manager/scripts/deploy_build
  chroma-manager/tests/framework/integration/existing_filesystem_configuration/cluster_setup
  chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests
  chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup
  chroma-manager/tests/integration/core/remote_operations.py
  scripts/deploy_build
Labels: bug, enhancement

#109 Potential bug in test_filesystem_dne
  chroma-manager/tests/integration/shared_storage_configuration/test_filesystem_dne.py
Labels: bug

#469 Mark exported pools as not usable so they don't appear in volumes page
  chroma-manager/chroma_core/plugins/block_devices.py
Labels: bug, enhancement

#464 Update manager and agent dependencies for reactive architecture
  chroma-agent/chroma-agent.spec
  chroma-manager/chroma-manager.spec
  chroma-manager/chroma_core/plugins/block_devices.py
Labels: enhancement

#432 add iml-device-aggregator endpoint to nginx configuration
  chroma-manager/chroma-manager.conf.template
Labels: enhancement

#479 Pools need to be exported if target mount fails
  chroma-agent/chroma_agent/action_plugins/manage_targets.py
Labels: bug
