Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2018-03, with the labels that each got.

#482 Don't emit urllib3 warnings to stderr
  chroma-agent/chroma-agent.spec
  chroma-agent/chroma_agent/agent_daemon.py
  chroma-dependencies/Makefile
Labels: bug

#372 Update mdraid and emcpower linux device_plugin components to use device_scanner output
  chroma-agent/chroma_agent/device_plugins/linux.py
  chroma-agent/chroma_agent/device_plugins/linux_components/block_devices.py
  chroma-agent/chroma_agent/device_plugins/linux_components/device_mapper.py
  chroma-agent/chroma_agent/device_plugins/linux_components/emcpower.py
  chroma-agent/chroma_agent/device_plugins/linux_components/local_filesystems.py
  chroma-agent/chroma_agent/device_plugins/linux_components/mdraid.py
  chroma-agent/tests/data/device_plugins/linux/agent_plugin.json
  chroma-agent/tests/data/device_plugins/linux/agent_plugin_mdraid.json
  chroma-agent/tests/data/device_plugins/linux/device_scanner.json
  chroma-agent/tests/data/device_plugins/linux/device_scanner_mdraid.json
  chroma-agent/tests/data/device_plugins/linux/devices_MdRaid_EMCPower.json
  chroma-agent/tests/device_plugins/linux/test_device_mapper.py
  chroma-agent/tests/device_plugins/linux/test_emcpower.py
  chroma-agent/tests/device_plugins/linux/test_linux.py
  chroma-agent/tests/device_plugins/linux/test_local_filesystem.py
  chroma-agent/tests/device_plugins/linux/test_mdraid.py
Labels: enhancement

#489 Enable stale probot app
  .github/stale.yml
Labels: enhancement

#487 Environment: pragma in commit message
  chroma-manager/tests/framework/utils/selective_auto_pass.sh
Labels: enhancement, pinned

#458 Share knowledge about existing zpools imported on other hosts
  chroma-agent/tests/data/device_plugins/linux/agent_plugin.json
  chroma-agent/tests/data/device_plugins/linux/agent_plugin_mdraid.json
  chroma-agent/tests/data/device_plugins/linux/agent_plugin_mpath.json
  chroma-agent/tests/data/device_plugins/linux/agent_plugin_zfs.json
  chroma-agent/tests/data/device_plugins/linux/device_scanner.json
  chroma-agent/tests/data/device_plugins/linux/device_scanner_mdraid.json
  chroma-agent/tests/data/device_plugins/linux/device_scanner_mpath.json
  chroma-agent/tests/data/device_plugins/linux/device_scanner_zfs.json
  chroma-agent/tests/data/device_plugins/linux/devices_1.json
  chroma-agent/tests/data/device_plugins/linux/devices_HYD-1385.json
  chroma-agent/tests/data/device_plugins/linux/devices_HYD-1390.json
  chroma-agent/tests/data/device_plugins/linux/devices_HYD-2431.json
  chroma-agent/tests/data/device_plugins/linux/devices_MdRaid_EMCPower.json
  chroma-agent/tests/data/device_plugins/linux/devices_NTAP-12-min.json
  chroma-agent/tests/data/device_plugins/linux/devices_NTAP-12.json
  chroma-agent/tests/data/device_plugins/linux/dmsetup_1.json
  chroma-agent/tests/data/device_plugins/linux/dmsetup_HYD-1385.json
  chroma-agent/tests/data/device_plugins/linux/dmsetup_HYD-1390.json
  chroma-agent/tests/data/device_plugins/linux/dmsetup_HYD-2431.json
  chroma-agent/tests/data/device_plugins/linux/dmsetup_MdRaid_EMCPower.json
  chroma-agent/tests/data/device_plugins/linux/dmsetup_NTAP-12-min.json
  chroma-agent/tests/data/device_plugins/linux/dmsetup_NTAP-12.json
  chroma-agent/tests/data/device_plugins/linux/lvs_HYD-2431.json
  chroma-agent/tests/data/device_plugins/linux/mpaths_1.json
  chroma-agent/tests/data/device_plugins/linux/mpaths_HYD-1385.json
  chroma-agent/tests/data/device_plugins/linux/mpaths_HYD-1390.json
  chroma-agent/tests/data/device_plugins/linux/mpaths_NTAP-12-min.json
  chroma-agent/tests/data/device_plugins/linux/normalized_1.json
  chroma-agent/tests/data/device_plugins/linux/normalized_HYD-1385.json
  chroma-agent/tests/data/device_plugins/linux/normalized_HYD-1390.json
  chroma-agent/tests/data/device_plugins/linux/normalized_NTAP-12-min.json
  chroma-agent/tests/data/device_plugins/linux/vgs_HYD-2431.json
  chroma-agent/tests/data/zfs_example_data.py
  chroma-agent/tests/device_plugins/linux/__init__.py
  chroma-agent/tests/device_plugins/linux/test_linux.py
  chroma-manager/chroma_core/plugins/block_devices.py
  chroma-manager/chroma_core/plugins/linux.py
  chroma-manager/tests/unit/chroma_core/plugins/fixtures/agent_plugin.json
  chroma-manager/tests/unit/chroma_core/plugins/fixtures/device_aggregator.text
  chroma-manager/tests/unit/chroma_core/plugins/test_linux.py
Labels: enhancement, reactive architecture

#486 Assume yes answer to {vg,lv}create
  chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice_lvm.py
Labels: bug, pinned

#511 Failed to setup HA (failed to setup corosync)
  chroma-agent/chroma_agent/lib/node_admin.py
  chroma-agent/tests/test_node_admin.py
Labels: bug

#522 Post sim cleanup
  chroma-manager/Makefile
  chroma-manager/tests/framework/test_reporting/jenkins_steps/main
  chroma-manager/tests/framework/utils/selective_auto_pass.sh
  chroma-manager/tests/integration/shared_storage_configuration/test_anonymous_access_control.py
Labels: bug
