Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2018-11, with the labels that each got.

#748 Add packages to profile on client
  chroma_core/models/host.py
  chroma_core/models/server_profile.py
Labels: enhancement

#750 Link to IML Intro video on README.md
  README.md
  media/iml_overview_title_and_play.png
Labels: docs

#749 Fixup clear-ha remote operation
  chroma_core/models/host.py
  tests/integration/core/api_testcase_with_test_reset.py
  tests/integration/core/clear_ha_el6.sh
  tests/integration/core/clear_ha_el7.sh
  tests/integration/core/remote_operations.py
Labels: failing tests

#755 Convert dnf to yum usage.
  storage_server.repo.in
  tests/framework/integration/utils/install_client.sh
  tests/integration/core/chroma_integration_testcase.py
  tests/integration/core/remote_operations.py
Labels: enhancement
