Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2018-05, with the labels that each got.

#497 Fix reactive-stack SSI failures
  chroma-agent/chroma-agent.spec
  chroma-agent/chroma_agent/action_plugins/manage_targets.py
  chroma-agent/chroma_agent/agent_daemon.py
  chroma-manager/chroma-manager.conf.template
  chroma-manager/chroma-manager.spec
  chroma-manager/chroma_core/models/target.py
  chroma-manager/chroma_core/plugins/block_devices.py
  chroma-manager/chroma_core/plugins/linux.py
  chroma-manager/tests/integration/core/api_testcase_with_test_reset.py
  chroma-manager/tests/integration/core/remote_operations.py
  chroma-manager/tests/integration/shared_storage_configuration/test_alerting.py
  chroma-manager/tests/integration/shared_storage_configuration/test_filesystem_same_name.py
  chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py
  chroma-manager/tests/unit/chroma_core/plugins/fixtures/agent_plugin_formatted_ldiskfs.json
  chroma-manager/tests/unit/chroma_core/plugins/fixtures/device_aggregator_formatted_ldiskfs.text
  chroma-manager/tests/unit/chroma_core/plugins/test_block_devices.py
Labels: bug, failing tests, pinned, reactive architecture

#561 Move block device processing into device-aggregator
  chroma-agent/chroma-agent.spec
  chroma-agent/chroma_agent/action_plugins/detect_scan.py
  chroma-agent/chroma_agent/device_plugins/linux_components/block_devices.py
  chroma-agent/chroma_agent/device_plugins/lustre.py
  chroma-agent/tests/actions_plugins/test_manage_target.py
  chroma-manager/chroma_core/plugins/block_devices.py
  chroma-manager/chroma_core/plugins/linux.py
  chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main
  chroma-manager/tests/integration/core/api_testcase_with_test_reset.py
  chroma-manager/tests/integration/existing_filesystem_configuration/utils/create_lustre_filesystem.py
  chroma-manager/tests/integration/shared_storage_configuration/test_filesystem_same_name.py
  chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice_zfs.py
Labels: enhancement, pinned, reactive architecture

#467 Reactive stack
  chroma-agent/chroma-agent.spec
  chroma-bundles/chroma_support.repo
  chroma-bundles/include/find_deps.py
  chroma-manager/chroma-manager.spec
  chroma-manager/storage_server.repo
  chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup
  chroma-manager/tests/framework/utils/defaults.sh
  chroma-manager/tests/framework/utils/install_deps.sh
Labels: pinned, reactive architecture

#576 Fixup block devs
  chroma-agent/chroma_agent/action_plugins/detect_scan.py
  chroma-agent/chroma_agent/action_plugins/manage_targets.py
  chroma-agent/chroma_agent/device_plugins/audit/lustre/__init__.py
  chroma-agent/chroma_agent/device_plugins/block_devices.py
  chroma-agent/chroma_agent/device_plugins/linux_components/__init__.py
  chroma-agent/chroma_agent/device_plugins/lustre.py
  chroma-agent/chroma_agent/utils.py
  chroma-agent/tests/data/device_plugins/scanner-lu-mounted.out
  chroma-agent/tests/data/device_plugins/scanner-lu-not-mounted.out
  chroma-agent/tests/device_plugins/test_block_devices.py
  chroma-agent/tests/test_utils.py
  chroma-manager/tests/integration/core/remote_operations.py
  chroma-manager/tests/integration/existing_filesystem_configuration/utils/create_lustre_filesystem.py
  chroma-manager/tests/unit/chroma_core/plugins/test_block_devices.py
Labels: bug, enhancement, pinned, reactive architecture

#588 Settle before reading from device-scanner
  chroma-agent/chroma_agent/device_plugins/block_devices.py
Labels: bug

#593 Remove caching of localMounts
  chroma-agent/chroma_agent/device_plugins/block_devices.py
  chroma-agent/chroma_agent/device_plugins/lustre.py
Labels: bug

#592 EFS fix detection of LVM mounts
  chroma-agent/chroma_agent/device_plugins/lustre.py
  chroma-manager/tests/integration/existing_filesystem_configuration/utils/create_lustre_filesystem.py
Labels: bug

#597 Efs install parallel2
  chroma-manager/tests/integration/existing_filesystem_configuration/utils/create_lustre_filesystem.py
  chroma-manager/tests/integration/utils/test_filesystems/test_filesystem.py
Labels: enhancement

#610 fix efs lvm create
  chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice_lvm.py
Labels: bug

#586 Per build configurable MFL repo
  Makefile
  chroma-agent/Makefile
  chroma-bundles/Makefile
  chroma-bundles/chroma-manager/Makefile
  chroma-bundles/chroma_support.repo.in
  chroma-bundles/include/Makefile.bundle
  chroma-bundles/include/find_deps.py
  chroma-dependencies/Makefile
  chroma-manager/Makefile
  chroma-manager/storage_server.repo.in
  chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main
  chroma-manager/tests/framework/integration/installation_and_upgrade/cluster_setup
  chroma-manager/tests/framework/integration/installation_and_upgrade/jenkins_steps/main
  chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/jenkins_steps/main
  chroma-manager/tests/framework/services/jenkins_steps/main
  chroma-manager/tests/framework/unit/jenkins_steps/main
  chroma-manager/tests/framework/utils/defaults.sh.in
Labels: enhancement, pinned

#598 Fix LNet Detection
  chroma-agent/chroma_agent/device_plugins/linux_network.py
Labels: enhancement

#601 Separate prepare_device_commands into wipe_signatures and create_device
  chroma-manager/tests/integration/core/api_testcase_with_test_reset.py
  chroma-manager/tests/integration/existing_filesystem_configuration/utils/create_lustre_filesystem.py
  chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice.py
  chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice_linux.py
  chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice_lvm.py
  chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice_zfs.py
Labels: bug, enhancement, failing tests

#612 Fixup tests to accommodate changes in iml-common#41
  chroma-agent/tests/actions_plugins/test_manage_target.py
  chroma-agent/tests/actions_plugins/test_manage_targets.py
  chroma-agent/tests/device_plugins/test_corosync.py
  chroma-agent/tests/device_plugins/test_lustre.py
  chroma-agent/tests/test_corosync_config.py
  chroma-agent/tests/test_fencing.py
Labels: enhancement, failing tests

#617 Fix zpool labelclear
  chroma-manager/tests/integration/core/api_testcase_with_test_reset.py
Labels: bug, failing tests

#603 CentOS 7.5 and Lustre 2.10.4
  chroma-bundles/install
  chroma-manager/storage_server.repo
  chroma-manager/tests/framework/utils/defaults.sh
Labels: enhancement

#622 Exception in plugin_runner log when accessing aggregator socket
  chroma-manager/chroma-manager.conf.template
  chroma-manager/chroma-manager.spec
  chroma-manager/chroma_core/management/commands/nginx.py
  chroma-manager/chroma_core/plugins/block_devices.py
  chroma-manager/scripts/nginx_settings.py
  chroma-manager/settings.py
Labels: bug, failing tests

#626 Account for any non-shared/non-ha volumes available
  chroma-manager/tests/integration/shared_storage_configuration/test_ha_clustering.py
  chroma-manager/tests/integration/shared_storage_configuration/test_volumes.py
Labels: bug
