Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2019-04, with the labels that each got.

#845 Add iml-wasm-components docker build to CD step in travis file
  .travis.yml
Labels: bug

#826 Remove another instance of crossing boundary while in transaction.
  chroma_core/services/lustre_audit/update_scan.py
Labels: bug

#838 Bump Lustre to 2.10.7
  lustre-client.repo
  lustre-server.repo
  tests/framework/utils/defaults.sh.in
Labels: enhancement

#853 Update Paramiko
  requirements.txt
Labels: enhancement

#855 Add get_cloned_conns fn
  docker/iml-warp-drive.dockerfile
  iml-agent-comms/src/main.rs
  iml-agent-comms/src/messaging.rs
  iml-manager-messaging/src/lib.rs
  iml-rabbit/src/lib.rs
  iml-warp-drive/src/locks.rs
  iml-warp-drive/tests/integration_tests.rs
Labels: enhancement

#835 Locks and Actions Base
  .travis.yml
  chroma-manager/chroma-manager.conf.template
  chroma-manager/chroma_api/action.py
  chroma-manager/chroma_api/system_status.py
  chroma-manager/chroma_api/urls.py
  chroma-manager/chroma_api/utils.py
  chroma-manager/chroma_cli/handlers.py
  chroma-manager/chroma_core/lib/service_config.py
  chroma-manager/chroma_core/management/commands/print-settings.py
  chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py
  chroma-manager/chroma_core/services/job_scheduler/job_scheduler_client.py
  chroma-manager/chroma_core/services/job_scheduler/lock_cache.py
  chroma-manager/settings.py
  chroma-manager/tests/integration/core/api_testcase_with_test_reset.py
  chroma-manager/tests/integration/shared_storage_configuration/test_shutdown_reboot.py
  chroma-manager/tests/unit/chroma_api/chroma_api_test_case.py
  chroma-manager/tests/unit/chroma_api/test_misc.py
  chroma-manager/tests/unit/chroma_api/test_sorting_actions.py
  chroma-manager/tests/unit/chroma_core/services/job_scheduler/test_available_jobs.py
  chroma-manager/tests/unit/chroma_core/services/job_scheduler/test_available_transitions.py
  chroma-manager/tests/unit/lib/iml_unit_test_case.py
  chroma-manager/tests/unit/services/job_scheduler/job_test_case.py
  chroma-manager/tests/utils/http_requests.py
  chroma-manager/wsgi.py
  chroma_api/action.py
  tests/integration/existing_filesystem_configuration/test_filesystem_detection.py
  tests/integration/shared_storage_configuration/test_anonymous_access_control.py
  tests/integration/shared_storage_configuration/test_available_jobs_and_trans.py
  tests/integration/shared_storage_configuration/test_client_mount_management.py
Labels: enhancement

#865 Bump deps for wasm components
  iml-wasm-components/Cargo.lock
  iml-wasm-components/iml-action-dropdown/Cargo.toml
  iml-wasm-components/iml-action-dropdown/src/lib.rs
Labels: enhancement

#844 Implement Action Runner on Manager
  .copr/Makefile
  Cargo.lock
  Cargo.toml
  chroma_core/lib/job.py
  chroma_core/lib/long_polling/__init__.py
  ci/azure-clippy.yml
  iml-action-runner.service
  iml-action-runner.socket
  iml-agent-comms/Cargo.toml
  iml-agent-comms/src/flush_queue.rs
  iml-agent-comms/src/host.rs
  iml-agent-comms/src/main.rs
  iml-agent-comms/src/messaging.rs
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/agent_error.rs
  iml-agent/src/daemon_plugins/action_runner.rs
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/http_comms/session.rs
  iml-manager-messaging/Cargo.toml
  iml-manager-messaging/src/lib.rs
  iml-rabbit/src/lib.rs
  iml-services/Cargo.toml
  iml-services/src/lib.rs
  iml-services/src/service_queue.rs
  iml-services/src/services/action_runner.rs
  iml-services/src/services/action_runner/data.rs
  iml-services/src/services/action_runner/error.rs
  iml-services/src/services/action_runner/main.rs
  iml-services/src/services/action_runner/mod.rs
  iml-services/src/services/action_runner/receiver.rs
  iml-services/src/services/action_runner/sender.rs
  iml-services/src/services/mod.rs
  iml-services/src/services/stratagem.rs
  iml-services/tests/action_runner_tests.rs
  iml-warp-drive/src/locks.rs
  iml-warp-drive/src/main.rs
  iml-wire-types/src/lib.rs
  rust-iml.spec
Labels: enhancement

#864 Use correct interface for LNet in SSI testing
  provisioner_output-vagrant-ssi.json.in
  pyproject.toml
  tests/framework/utils/provisioner_interface/provision_cluster
  tests/integration/core/chroma_integration_testcase.py
  tests/integration/core/remote_operations.py
Labels: bug

#868 Ensure channels are closed when finished
  Cargo.lock
  iml-agent-comms/src/main.rs
  iml-agent-comms/src/messaging.rs
  iml-rabbit/src/lib.rs
Labels: bug

#871 Fix hanging test
  iml-services/tests/action_runner_tests.rs
Labels: bug

#872 Add tests
  Cargo.lock
  azure-pipelines.yml
  ci/azure-clippy.yml
  ci/azure-install-rabbit.yml
  ci/azure-test-coverage.yml
  ci/azure-test-stable.yml
  iml-agent/Cargo.toml
  iml-agent/src/daemon_plugins/action_runner.rs
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/http_comms/session.rs
  iml-agent/src/poller.rs
  iml-agent/src/reader.rs
  iml-rabbit/src/lib.rs
  iml-wire-types/src/lib.rs
Labels: tech debt

#877 Hosts can be removed / re-added prematurely
  iml-agent-comms/src/flush_queue.rs
  iml-agent-comms/src/host.rs
  iml-agent-comms/src/main.rs
  iml-agent-comms/src/messaging.rs
  iml-agent-comms/src/session.rs
  iml-agent/src/action_plugins/action_plugin.rs
  iml-services/src/services/action_runner/main.rs
  iml-services/src/services/action_runner/receiver.rs
  iml-services/src/services/action_runner/sender.rs
  iml-wire-types/src/lib.rs
Labels: bug

#861 stratagem_warn / stratagem_purge: Add CLI
  Cargo.lock
  Cargo.toml
  Makefile
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/action_plugins/stratagem/action_warning.rs
  iml-agent/src/action_plugins/stratagem/mod.rs
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/agent_error.rs
  iml-agent/src/cli.rs
  liblustreapi-sys/Cargo.toml
  liblustreapi/Cargo.toml
  stratagem-runner/Cargo.toml
  stratagem-runner/src/error.rs
  stratagem-runner/src/stratagem_purge.rs
  stratagem-runner/src/stratagem_warning.rs
Labels: enhancement

#873 Re-enable upgrade testing
  Makefile
  chroma_core/models/host.py
  chroma_core/models/target.py
  chroma_core/south_migrations/0040_table_update_notify.py
  chroma_core/south_migrations/0041_auto__del_packageversion__del_unique_packageversion_package_version_re.py
  provisioner_output-vagrant-upgrade.json.in
  tests/framework/integration/installation_and_upgrade/cluster_setup
  tests/framework/integration/installation_and_upgrade/jenkins_steps/main
  tests/framework/integration/installation_and_upgrade/run_tests
  tests/framework/integration/utils/upgrade_os.sh
  tests/framework/utils/cleanup.sh
  tests/framework/utils/defaults.sh.in
  tests/framework/utils/selective_auto_pass.sh
  tests/integration/core/remote_operations.py
  tests/integration/installation_and_upgrade/test_data_consistancy.py
  tests/integration/installation_and_upgrade/test_update_with_yum.py
  tests/utils/install-4.x.exp
  tests/utils/upgrade.exp
Labels: enhancement

#891 Use the cleanup.sh script
  tests/framework/integration/upgrade_os/jenkins_steps/main
Labels: tech debt

#890 Support streaming of directory contents
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/fs.rs
Labels: enhancement

#825 Test with b2_12
  chroma_core/models/target.py
  lustre-client.repo
  lustre-server.repo
  python-iml-manager.spec.in
  tests/framework/integration/installation_and_upgrade/run_tests
  tests/framework/utils/defaults.sh.in
  tests/integration/core/remote_operations.py
  tests/integration/shared_storage_configuration/test_conf_params.py
  tests/integration/shared_storage_configuration/test_hsm.py
Labels: enhancement

#899 Bump Wasm deps
  iml-wasm-components/Cargo.lock
  iml-wasm-components/iml-action-dropdown/Cargo.toml
Labels: tech debt

#888 Implement scan functionality
  Cargo.lock
  iml-agent-comms/Cargo.toml
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/agent_error.rs
  iml-agent/src/cli.rs
  iml-agent/src/cmd.rs
  iml-agent/src/fs.rs
  iml-agent/src/lib.rs
  iml-agent/src/systemd.rs
  iml-rabbit/Cargo.toml
  iml-services/Cargo.toml
  iml-warp-drive/Cargo.toml
  rust-iml.spec
  tokio-runtime-shutdown/Cargo.toml
Labels: enhancement
