Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2019-01, with the labels that each got.

#779 SSI: test_server_authentication using wrong path
  tests/integration/shared_storage_configuration/test_storage_server_authentication.py
Labels: bug

#782 Table Update Notify Migration
  chroma-manager/chroma_core/south_migrations/0040_table_update_notify.py
Labels: enhancement

#764 Wait for server boot after PDU restart
  tests/integration/shared_storage_configuration/test_power_control.py
Labels: failing tests

#785 Enforce default-options are non-null
  chroma_core/models/lnet_configuration.py
  chroma_core/models/power_control.py
  chroma_core/south_migrations/0042_power_control_type_remove_null_options.py
  chroma_core/south_migrations/0043_alter_power_control_type_option_default.py
Labels: bug

#789 Fix detection of rhel7.6
  chroma-bundles/install
Labels: bug

#796 GH-793
  chroma-manager/chroma_core/south_migrations/0023_auto__add_unconfigurersyslogjob__add_getcorosyncstatejob__add_pacemake.py
Labels: bug

#795 Only clear sessions if db is populated
  chroma-manager/chroma_core/lib/service_config.py
Labels: bug

#798 Fix migration issue. (#647)
  chroma-manager/chroma_core/south_migrations/0039_add_primary_umtm_stepresults.py
Labels: bug

#792 Remove fetch-help from server install
  tests/integration/core/chroma_integration_testcase.py
  tests/integration/core/utility_testcase.py
Labels: bug
