Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2019-12, with the labels that each got.

#1360 Wire up more routes
  iml-gui/configs/tailwind.config.js
  iml-gui/crate/src/components/font_awesome.rs
  iml-gui/crate/src/generated/css_classes.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/partial/header.rs
Labels: enhancement

#1361 Add activity indicator
  iml-gui/crate/Cargo.lock
  iml-gui/crate/Cargo.toml
  iml-gui/crate/src/components/activity_indicator.rs
  iml-gui/crate/src/components/font_awesome.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/partial/header.rs
  iml-wire-types/wire-types.rs
Labels: enhancement

#1368 Bump seed to latest version.
  iml-gui/crate/Cargo.lock
  iml-gui/crate/Cargo.toml
  iml-gui/crate/src/lib.rs
  iml-gui/entries/index.hbs
Labels: chore

#1369 Use to string of Page for menu display
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/partial/header.rs
Labels: tech debt

#1367 Fix issue with possible non-existent host.fqdn during AgentException
  chroma_core/lib/job.py
Labels: bug

#1370 Enable detail routing
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/home.rs
  iml-gui/crate/src/page/partial/header.rs
  iml-gui/crate/src/page/server_detail.rs
  iml-gui/crate/src/route.rs
Labels: enhancement

#1374 Purge service queues when restarting
  Cargo.lock
  iml-agent-comms/src/messaging.rs
  iml-rabbit/Cargo.toml
  iml-rabbit/src/lib.rs
  iml-services/iml-service-queue/src/service_queue.rs
  iml-warp-drive/src/locks.rs
Labels: enhancement

#1383 agent: Add lctl action plugin
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/lctl.rs
  iml-agent/src/action_plugins/mod.rs
Labels: enhancement

#1389 GH-1384 Setup NTP Storage Servers for Docker
  settings.py
Labels: bug

#1390 Fixup manager cli name
  iml-manager-cli/src/main.rs
Labels: bug

#1387 Try parallel compose building
  .travis.yml
  docker/iml-action-runner.dockerfile
  docker/iml-agent-comms.dockerfile
  docker/iml-manager-cli.dockerfile
  docker/iml-stratagem.dockerfile
  docker/iml-warp-drive.dockerfile
  docker/iml-wasm-components.dockerfile
  docker/rust-base.dockerfile
Labels: enhancement

#1391 IML CLI: Fix cmd error state
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/display_utils.rs
Labels: bug

#1392 Add missing imports
  chroma_api/filesystem.py
Labels: bug

#1393 Implement context-sensitive help
  iml-gui/crate/src/components/activity_indicator.rs
  iml-gui/crate/src/components/breadcrumbs.rs
  iml-gui/crate/src/ctx_help.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/partial/header.rs
  iml-gui/crate/src/route.rs
Labels: enhancement

#1399 Fix or silence warnings in iml-agent
  iml-agent/src/poller.rs
  iml-agent/src/reader.rs
Labels: tech debt

#1406 agent: Add get_kernel action to action_plugins
  iml-agent/src/action_plugins/action_plugin.rs
Labels: enhancement

#1407 Add edition to rustfmt.toml
  iml-gui/crate/rustfmt.toml
Labels: bug

#1362 Implement getting RPM package version
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/action_plugins/package.rs
  iml-agent/src/action_plugins/package_installed.rs
  iml-agent/src/cli.rs
  iml-agent/src/rpm.rs
Labels: enhancement

#1402 Implement checking of loaded kernel modules
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/kernel_module.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/cli.rs
Labels: enhancement

#1412 Bump futures and tokio to stable releases
  Cargo.lock
  iml-agent-comms/Cargo.toml
  iml-agent-comms/src/flush_queue.rs
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/ostpool.rs
  iml-agent/src/action_plugins/stratagem/action_purge.rs
  iml-agent/src/action_plugins/stratagem/action_warning.rs
  iml-agent/src/agent_error.rs
  iml-agent/src/cmd.rs
  iml-agent/src/http_comms/session.rs
  iml-agent/src/main.rs
  iml-agent/src/poller.rs
  iml-agent/src/reader.rs
  iml-agent/src/systemd.rs
  iml-fs/Cargo.toml
  iml-fs/src/lib.rs
  iml-mailbox/Cargo.toml
  iml-mailbox/src/lib.rs
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/error.rs
  iml-manager-cli/src/server.rs
  iml-manager-client/Cargo.toml
  iml-postgres/Cargo.toml
  iml-postgres/src/lib.rs
  iml-rabbit/Cargo.toml
  iml-request-retry/Cargo.toml
  iml-request-retry/examples/demo-server-client.rs
  iml-request-retry/src/lib.rs
  iml-services/iml-action-runner/Cargo.toml
  iml-services/iml-action-runner/src/data.rs
  iml-services/iml-action-runner/src/error.rs
  iml-services/iml-action-runner/src/main.rs
  iml-services/iml-action-runner/tests/action_runner_tests.rs
  iml-services/iml-service-queue/Cargo.toml
  iml-services/iml-stratagem/Cargo.toml
  iml-util/Cargo.toml
  iml-util/util.rs
  iml-warp-drive/Cargo.toml
  iml-warp-drive/src/users.rs
  iml-wire-types/Cargo.toml
  tokio-runtime-shutdown/Cargo.toml
Labels: tech debt

#1414 Fix formatting for rust 1.40
  iml-agent-comms/src/main.rs
  iml-agent/src/action_plugins/ntp/action_configure.rs
  iml-agent/src/reader.rs
  iml-services/iml-action-runner/src/main.rs
  iml-services/iml-action-runner/src/sender.rs
  iml-services/iml-action-runner/tests/action_runner_tests.rs
  iml-warp-drive/src/main.rs
Labels: chore

#1415 Fix dependencies of subcrates
  iml-agent/Cargo.toml
  iml-fs/Cargo.toml
  iml-manager-cli/Cargo.toml
  iml-rabbit/Cargo.toml
  iml-util/Cargo.toml
Labels: chore, tech debt

#1394 Add ostpool notify support
  chroma_core/migrations/0005_add_table_json_notify.py
  chroma_core/migrations/0008_ostpool_json_notify.py
  chroma_core/migrations/__init__.py
  iml-gui/crate/src/lib.rs
  iml-warp-drive/src/cache.rs
  iml-warp-drive/src/db_record.rs
  iml-wire-types/wire-types.rs
Labels: enhancement

#1418 Implement Label for some more wire-types.
  iml-wire-types/wire-types.rs
Labels: enhancement

#1420 Remove Flatten Trait
  iml-fs/src/lib.rs
  iml-util/util.rs
Labels: enhancement

#1419 Implement paging component
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/components/paging.rs
Labels: enhancement

#1422 Update deps in wasm components
  iml-wasm-components/Cargo.lock
Labels: dependencies

#1424 Flush after write-all in mailbox
  iml-mailbox/src/lib.rs
Labels: bug

#1423 Bump warp and reqwest to latest in github
  Cargo.lock
  iml-agent-comms/Cargo.toml
  iml-agent/Cargo.toml
  iml-fs/Cargo.toml
  iml-fs/src/lib.rs
  iml-mailbox/Cargo.toml
  iml-mailbox/src/lib.rs
  iml-manager-cli/Cargo.toml
  iml-manager-client/Cargo.toml
  iml-rabbit/Cargo.toml
  iml-request-retry/Cargo.toml
  iml-services/iml-action-runner/Cargo.toml
  iml-services/iml-stratagem/Cargo.toml
  iml-util/Cargo.toml
  iml-warp-drive/Cargo.toml
  iml-warp-drive/src/main.rs
  liblustreapi/Cargo.toml
  tokio-runtime-shutdown/Cargo.toml
Labels: chore, tech debt

#1395 Implement create_ltuer_conf
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/ltuer.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/cli.rs
  iml-agent/systemd-units/rust-iml-agent.service
Labels: enhancement

#1403 Create `create_lpurge_conf` action plugin
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/lpurge.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/action_plugins/snapshots/lpurge_conf_tests__works.snap
  iml-agent/src/cli.rs
Labels: enhancement

#1426 Remove termion
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/cli.rs
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/display_utils.rs
  liblustreapi-types/build.rs
Labels: tech debt

#1428 Implement getting kernel module version
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/kernel_module.rs
  iml-agent/src/cli.rs
Labels: enhancement

#1431 Reenable job_scheduler/host tests
  tests/unit/chroma_core/helpers/mock_agent_rpc.py
  tests/unit/services/job_scheduler/host/__init__.py
  tests/unit/services/job_scheduler/host/test_host.py
  tests/unit/services/job_scheduler/host/test_host_contact.py
Labels: tech debt
