Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2019-07, with the labels that each got.

#1026 Add pie-chart component
  iml-wasm-components/Cargo.lock
  iml-wasm-components/Cargo.toml
  iml-wasm-components/iml-duration-picker/Cargo.toml
  iml-wasm-components/iml-duration-picker/src/lib.rs
  iml-wasm-components/iml-pie-chart/Cargo.toml
  iml-wasm-components/iml-pie-chart/src/lib.rs
Labels: enhancement

#1025 Update invoke_rust_agent_expect_result to handle various exceptions
  chroma_core/lib/job.py
Labels: enhancement

#863 Create Actions for Stratagem on Manager side
  chroma_api/stratagem.py
  chroma_api/urls.py
  chroma_core/lib/cache.py
  chroma_core/lib/job.py
  chroma_core/lib/stratagem.py
  chroma_core/models/__init__.py
  chroma_core/models/filesystem.py
  chroma_core/models/stratagem.py
  chroma_core/services/job_scheduler/job_scheduler.py
  chroma_core/services/job_scheduler/job_scheduler_client.py
  chroma_core/south_migrations/0046_auto__add_sendstratagemresultstoclientjob__add_stratagemconfiguration_.py
  chroma_help/help.py
Labels: enhancement

#1030 Update manager cli to parse purge and report durations correctly
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/cli.rs
  iml-manager-cli/src/main.rs
Labels: bug

#1031 Add Validation cases to RunStratagemCommandResult enum
  iml-manager-cli/src/manager_cli_error.rs
Labels: enhancement

#1027 fixups
  iml-wasm-components/.copr/Makefile
  iml-wasm-components/iml-alert-indicator/src/lib.rs
  iml-wasm-components/iml-popover/src/lib.rs
Labels: enhancement

#1035 Fix TestAnonymousAccessControl
  tests/integration/shared_storage_configuration/test_anonymous_access_control.py
Labels: bug, failing tests

#1037 Add stratagem endpoints to end point exception
  tests/integration/installation_and_upgrade/test_data_consistancy.py
Labels: failing tests

#1018 Update minimum version requirements to ensure upgrades
  python-iml-manager.spec
  setup.py
  tests/framework/integration/installation_and_upgrade/run_tests
Labels: bug

#1038 Add Stratagem Client Validation
  chroma_api/stratagem.py
  iml-manager-cli/src/manager_cli_error.rs
Labels: enhancement

#1039 Fix local build of rust rpms
  .copr/Makefile
  Makefile
Labels: bug

#1033 Refactor action dropdown
  Cargo.lock
  iml-warp-drive/src/locks.rs
  iml-wasm-components/.copr/Makefile
  iml-wasm-components/Cargo.lock
  iml-wasm-components/iml-action-dropdown/Cargo.toml
  iml-wasm-components/iml-action-dropdown/src/action_dropdown.rs
  iml-wasm-components/iml-action-dropdown/src/action_items.rs
  iml-wasm-components/iml-action-dropdown/src/deferred_action_dropdown.rs
  iml-wasm-components/iml-action-dropdown/src/fetch.rs
  iml-wasm-components/iml-action-dropdown/src/hsm.rs
  iml-wasm-components/iml-action-dropdown/src/hsm_action_dropdown.rs
  iml-wasm-components/iml-action-dropdown/src/hsm_dropdown.rs
  iml-wasm-components/iml-action-dropdown/src/lib.rs
  iml-wasm-components/iml-action-dropdown/src/model.rs
  iml-wasm-components/iml-action-dropdown/src/multi_dropdown.rs
  iml-wasm-components/iml-action-dropdown/src/snapshots/tests__group_actions_by_label_1.snap
  iml-wasm-components/iml-action-dropdown/src/snapshots/tests__group_actions_by_label_2.snap
  iml-wasm-components/iml-action-dropdown/src/update.rs
  iml-wasm-components/iml-alert-indicator/Cargo.toml
  iml-wasm-components/iml-alert-indicator/src/lib.rs
  iml-wasm-components/iml-tooltip/src/lib.rs
  iml-wasm-components/iml-utils/Cargo.toml
  iml-wasm-components/iml-utils/src/lib.rs
  iml-wasm-components/iml-wasm/Cargo.toml
  iml-wasm-components/iml-wasm/src/deferred_action_dropdown.rs
  iml-wasm-components/iml-wasm/src/hsm_dropdown.rs
  iml-wasm-components/iml-wasm/src/lib.rs
  iml-wasm-components/iml-wasm/src/multi_action_dropdown.rs
  iml-wire-types/Cargo.toml
  iml-wire-types/src/lib.rs
Labels: tech debt

#1041 Add lock-indicator component
  iml-wasm-components/Cargo.lock
  iml-wasm-components/Cargo.toml
  iml-wasm-components/iml-lock-indicator/Cargo.toml
  iml-wasm-components/iml-lock-indicator/lock-indicator.rs
Labels: enhancement

#1043 Avoid divide by 0 on pie chart
  iml-wasm-components/iml-pie-chart/src/lib.rs
Labels: bug

#1042 Filter out empty actions
  iml-wasm-components/iml-action-dropdown/src/deferred_action_dropdown.rs
  iml-wasm-components/iml-action-dropdown/src/model.rs
Labels: bug

#1057 Add initial bootstrap-components module
  iml-wasm-components/Cargo.lock
  iml-wasm-components/Cargo.toml
  iml-wasm-components/bootstrap-components/Cargo.toml
  iml-wasm-components/bootstrap-components/bootstrap.rs
  iml-wasm-components/iml-alert-indicator/Cargo.toml
  iml-wasm-components/iml-alert-indicator/src/lib.rs
  iml-wasm-components/iml-duration-picker/Cargo.toml
  iml-wasm-components/iml-duration-picker/src/lib.rs
  iml-wasm-components/iml-lock-indicator/Cargo.toml
  iml-wasm-components/iml-lock-indicator/lock-indicator.rs
  iml-wasm-components/iml-popover/src/lib.rs
  iml-wasm-components/iml-tooltip/src/lib.rs
Labels: enhancement

#1058 Implement toggle module
  iml-wasm-components/Cargo.lock
  iml-wasm-components/Cargo.toml
  iml-wasm-components/iml-toggle/Cargo.toml
  iml-wasm-components/iml-toggle/toggle.rs
Labels: enhancement

#1044 Add Grafana Dashboard Provisioning
  .copr/Makefile
  chroma_core/lib/stratagem.py
  grafana/dashboards/iml-dashboards.yaml
  grafana/dashboards/stratagem-dashboard-1.json
  python-iml-manager.spec
Labels: enhancement

#1064 Fixup RPM build
  .copr/Makefile
  MANIFEST.in
  grafana/grafana-iml.ini
  python-iml-manager.spec
Labels: bug, enhancement

#1065 GH-1056 - Create nginx integration with influx
  chroma-manager.conf.template
Labels: enhancement

#1068 GH-1062 - Stratagem duration models should be bigint
  chroma_api/stratagem.py
  chroma_core/models/stratagem.py
  chroma_core/south_migrations/0046_auto__add_sendstratagemresultstoclientjob__add_stratagemconfiguration_.py
  iml-manager-cli/src/manager_cli_error.rs
Labels: enhancement

#1070 GH-1050 - Create grafana chart iframe and iml-stratagem module
  iml-wasm-components/Cargo.lock
  iml-wasm-components/Cargo.toml
  iml-wasm-components/iml-environment/src/lib.rs
  iml-wasm-components/iml-grafana-chart/Cargo.toml
  iml-wasm-components/iml-grafana-chart/src/lib.rs
  iml-wasm-components/iml-stratagem/Cargo.toml
  iml-wasm-components/iml-stratagem/src/lib.rs
Labels: enhancement

#1069 Dynamic liblustreapi.so loading
  Cargo.lock
  Cargo.toml
  chroma_agent_comms/views.py
  chroma_core/models/host.py
  iml-agent/src/action_plugins/stratagem/action_purge.rs
  iml-agent/src/action_plugins/stratagem/action_warning.rs
  liblustreapi-types/Cargo.toml
  liblustreapi-types/build.rs
  liblustreapi-types/src/bindings.rs
  liblustreapi-types/src/lib.rs
  liblustreapi-types/wrapper.h
  liblustreapi/Cargo.toml
  liblustreapi/src/error.rs
  liblustreapi/src/lib.rs
Labels: enhancement

#1072 Implement the Filesystem page in seed
  iml-wasm-components/Cargo.lock
  iml-wasm-components/Cargo.toml
  iml-wasm-components/iml-alert-indicator/src/lib.rs
  iml-wasm-components/iml-fs-page/Cargo.toml
  iml-wasm-components/iml-fs-page/fs-page.rs
  iml-wasm-components/iml-wasm/Cargo.toml
  iml-wasm-components/iml-wasm/src/lib.rs
Labels: enhancement

#1040 Use warp-drive for notify updates
  .gitignore
  Cargo.lock
  chroma_core/south_migrations/0040_table_update_notify.py
  chroma_core/south_migrations/0047_table_json_notify.py
  docker/iml-warp-drive.dockerfile
  docker/iml-wasm-components.dockerfile
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/main.rs
  iml-manager-client/src/lib.rs
  iml-postgres/Cargo.toml
  iml-postgres/src/lib.rs
  iml-warp-drive/Cargo.toml
  iml-warp-drive/src/cache.rs
  iml-warp-drive/src/db_record.rs
  iml-warp-drive/src/lib.rs
  iml-warp-drive/src/listen.rs
  iml-warp-drive/src/main.rs
  iml-warp-drive/src/users.rs
  iml-wire-types/src/lib.rs
  tokio-runtime-shutdown/Cargo.toml
  wsgi.py
Labels: enhancement

#1071 Gh 1051 Implement inode users component
  iml-wasm-components/Cargo.lock
  iml-wasm-components/bootstrap-components/bootstrap.rs
  iml-wasm-components/iml-stratagem/Cargo.toml
  iml-wasm-components/iml-stratagem/src/inode_error.rs
  iml-wasm-components/iml-stratagem/src/inode_table.rs
  iml-wasm-components/iml-stratagem/src/lib.rs
Labels: enhancement

#1076 Add rust-iml-cli as manager req
  Cargo.lock
  iml-warp-drive/Cargo.toml
  iml-wasm-components/Cargo.lock
  iml-wasm-components/iml-fs-page/fs-page.rs
  iml-wire-types/Cargo.toml
  python-iml-manager.spec
Labels: enhancement

#1078 Add mount_point for detect scan in monitored mode.
  chroma_core/lib/detection.py
Labels: enhancement

#1082 Add manager cli for configuring Stratagem
  Cargo.lock
  chroma_api/stratagem.py
  chroma_core/models/stratagem.py
  chroma_core/services/job_scheduler/job_scheduler.py
  chroma_core/south_migrations/0046_auto__add_sendstratagemresultstoclientjob__add_stratagemconfiguration_.py
  chroma_core/south_migrations/0047_table_json_notify.py
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/display_utils.rs
  iml-manager-cli/src/main.rs
  iml-manager-cli/src/manager_cli_error.rs
  iml-manager-cli/src/stratagem.rs
  iml-manager-client/src/lib.rs
  iml-warp-drive/src/cache.rs
  iml-wire-types/src/lib.rs
Labels: bug, enhancement

#1073 Skip All MDTs not MDT0 for filesystem "unavailable" state
  chroma_core/lib/util.py
  chroma_core/models/filesystem.py
  chroma_core/services/job_scheduler/job_scheduler.py
Labels: enhancement

#1085 Add (Un)Configure stratagem timer
  chroma_core/models/stratagem.py
Labels: enhancement

#1090 Integrate with newest upstream changes
  Cargo.lock
  chroma_core/models/stratagem.py
  iml-agent/src/action_plugins/stratagem/server.rs
Labels: enhancement

#1091 Update warp-drive
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-warp-drive/src/cache.rs
  iml-warp-drive/src/db_record.rs
Labels: enhancement

#1074 Implement stratagem configuration component
  chroma_api/stratagem.py
  chroma_core/lib/service_config.py
  chroma_core/models/stratagem.py
  grafana/dashboards/stratagem-dashboard-1.json
  grafana/grafana-iml.ini
  iml-wasm-components/Cargo.lock
  iml-wasm-components/Cargo.toml
  iml-wasm-components/iml-duration-picker/Cargo.toml
  iml-wasm-components/iml-duration-picker/src/lib.rs
  iml-wasm-components/iml-environment/src/lib.rs
  iml-wasm-components/iml-fs/Cargo.toml
  iml-wasm-components/iml-fs/src/fs_detail_page.rs
  iml-wasm-components/iml-grafana-chart/src/lib.rs
  iml-wasm-components/iml-stratagem/Cargo.toml
  iml-wasm-components/iml-stratagem/src/delete_stratagem_button.rs
  iml-wasm-components/iml-stratagem/src/enable_stratagem_button.rs
  iml-wasm-components/iml-stratagem/src/inode_table.rs
  iml-wasm-components/iml-stratagem/src/lib.rs
  iml-wasm-components/iml-stratagem/src/update_stratagem_button.rs
  iml-wasm-components/iml-toggle/toggle.rs
  iml-wasm-components/iml-tooltip/src/lib.rs
  iml-wasm-components/iml-wasm/Cargo.toml
  iml-wasm-components/iml-wasm/src/lib.rs
Labels: enhancement
