Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2019-11, with the labels that each got.

#1296 Create new Add server CLI
  Cargo.lock
  chroma_api/host.py
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/error.rs
  iml-manager-cli/src/server.rs
  iml-wire-types/wire-types.rs
Labels: enhancement

#1303 Wait for gunicorn
  iml-gunicorn.service
  python-iml-manager.spec
  wsgi.py
Labels: bug

#1281 Port update repo cli
  .copr/Makefile
  Cargo.lock
  Cargo.toml
  chroma_api/host.py
  chroma_core/models/host.py
  chroma_core/south_migrations/0048_add_model_UpdateYumFileJob.py
  ci/azure-5.0-release-pipeline.yml
  ci/azure-test-pipeline.yml
  ci/template/azure-clippy.yml
  ci/template/azure-install-rust.yml
  ci/template/azure-rustfmt.yml
  ci/template/azure-test-stable.yml
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/display_utils.rs
  iml-manager-cli/src/error.rs
  iml-manager-cli/src/lib.rs
  iml-manager-cli/src/main.rs
  iml-manager-cli/src/server.rs
  iml-manager-cli/src/stratagem.rs
  iml-manager-cli/src/update_repo_file.rs
  iml-manager-client-1/Cargo.toml
  iml-manager-client-1/src/lib.rs
  iml-manager-client-3/Cargo.toml
  iml-manager-client-3/src/lib.rs
  iml-warp-drive/Cargo.toml
  iml-wire-types/wire-types.rs
Labels: enhancement

#1299 Update IML agent to use async / await
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/check_ha.rs
  iml-agent/src/action_plugins/check_stonith.rs
  iml-agent/src/action_plugins/stratagem/action_purge.rs
  iml-agent/src/action_plugins/stratagem/action_warning.rs
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/agent_error.rs
  iml-agent/src/cli.rs
  iml-agent/src/cmd.rs
  iml-agent/src/daemon_plugins/action_runner.rs
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/daemon_plugins/mod.rs
  iml-agent/src/http_comms/agent_client.rs
  iml-agent/src/http_comms/crypto_client.rs
  iml-agent/src/http_comms/hyper_client.rs
  iml-agent/src/http_comms/mailbox_client.rs
  iml-agent/src/http_comms/mod.rs
  iml-agent/src/http_comms/session.rs
  iml-agent/src/main.rs
  iml-agent/src/poller.rs
  iml-agent/src/reader.rs
  iml-agent/src/systemd.rs
  iml-fs/Cargo.toml
  iml-fs/src/lib.rs
  iml-mailbox/Cargo.toml
  iml-mailbox/src/lib.rs
  iml-mailbox/src/main.rs
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/update_repo_file.rs
  liblustreapi/src/lib.rs
Labels: enhancement

#1311 Fixup SVG styles
  iml-wasm-components/Cargo.lock
  iml-wasm-components/iml-pie-chart/src/lib.rs
Labels: bug

#1308 Gh 1285
  iml-wasm-components/iml-fs/src/fs_detail_page.rs
  iml-wasm-components/iml-fs/src/fs_page.rs
Labels: enhancement

#1314 Revert to rust stable
  .github/actions/copr-rust/action.yml
  .github/workflows/devel-release.yml
  .github/workflows/prod-release.yml
  .github/workflows/rust-ci.yml
  .github/workflows/wasm-ci.yml
Labels: enhancement

#1313 Revert to rust stable
  ci/azure-5.0-release-pipeline.yml
  ci/azure-test-pipeline.yml
  ci/template/azure-clippy.yml
  ci/template/azure-rustfmt.yml
  ci/template/azure-test-stable.yml
Labels: enhancement

#1312 Gh 1285 (#1308)
  iml-wasm-components/iml-fs/src/fs_detail_page.rs
  iml-wasm-components/iml-fs/src/fs_page.rs
Labels: bug

#1172 Leave /var/lib/chroma on manager
  python-iml-manager.spec
  tests/framework/integration/installation_and_upgrade/run_tests
Labels: bug

#1310 Add filesystem manager CLI
  Cargo.lock
  Cargo.toml
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/filesystem.rs
  iml-manager-cli/src/lib.rs
  iml-manager-cli/src/main.rs
  iml-manager-client/src/lib.rs
  iml-warp-drive/src/cache.rs
  iml-wasm-components/Cargo.lock
  iml-wasm-components/Cargo.toml
  iml-wasm-components/iml-action-dropdown/Cargo.toml
  iml-wasm-components/iml-alert-indicator/Cargo.toml
  iml-wasm-components/iml-fs/Cargo.toml
  iml-wasm-components/iml-fs/src/lib.rs
  iml-wasm-components/iml-lock-indicator/Cargo.toml
  iml-wasm-components/iml-stratagem/Cargo.toml
  iml-wasm-components/iml-stratagem/src/inode_table.rs
  iml-wasm-components/iml-utils/Cargo.toml
  iml-wasm-components/iml-utils/src/lib.rs
  iml-wasm-components/iml-wasm/Cargo.toml
  iml-wire-types/wire-types.rs
  number-formatter/Cargo.toml
  number-formatter/src/lib.rs
Labels: enhancement

#1317 Add systemd action plugins
  Cargo.lock
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/systemd.rs
  iml-wire-types/wire-types.rs
Labels: enhancement

#1319 Fix service testing
  .travis.yml
Labels: bug

#1320 Set ZFS params for EFS testing
  tests/integration/utils/test_blockdevices/test_blockdevice_zfs.py
Labels: failing tests

#1322 Avoid passing host
  chroma_core/lib/job.py
  chroma_core/models/lnet_configuration.py
  chroma_core/models/ntp.py
  tests/unit/chroma_core/jobs/test_jobs.py
Labels: bug

#1324 Bump wasm deps
  iml-wasm-components/Cargo.lock
Labels: tech debt

#1334 Fix RemovedInDjango20Warning for user.is_authenticated
  chroma_api/alert.py
  chroma_api/authentication.py
  chroma_api/command.py
  chroma_api/log.py
  chroma_api/session.py
  chroma_api/user.py
Labels: bug

#1298 Find latest kernel that supports listed modules
  iml-agent/src/action_plugins/check_kernel.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/cli.rs
Labels: enhancement

#1336 Add tokio_utils
  Cargo.lock
  iml-util/Cargo.toml
  iml-util/util.rs
Labels: enhancement

#1328 Add new smart input UI component
  iml-wasm-components/Cargo.lock
  iml-wasm-components/Cargo.toml
  iml-wasm-components/iml-input/Cargo.toml
  iml-wasm-components/iml-input/src/lib.rs
Labels: enhancement

#1341 Bump deps (rust-iml)
  Cargo.lock
  iml-agent-comms/src/error.rs
  iml-agent-comms/src/main.rs
  iml-mailbox/src/lib.rs
  iml-mailbox/src/main.rs
  iml-services/iml-action-runner/src/error.rs
  iml-services/iml-action-runner/src/sender.rs
  iml-services/iml-action-runner/tests/action_runner_tests.rs
  iml-warp-drive/src/error.rs
Labels: enhancement

#1339 Remove error_for_status call from POST
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/server.rs
  iml-manager-cli/src/stratagem.rs
  iml-manager-client/src/lib.rs
Labels: bug

#1340 Backport #1339
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/server.rs
  iml-manager-cli/src/stratagem.rs
  iml-manager-client-3/src/lib.rs
  python-iml-manager.spec
  rust-iml.spec
Labels: bug

#1262 Add OstPools
  chroma_api/filesystem.py
  chroma_api/urls.py
  chroma_core/migrations/0007_ostpools.py
  chroma_core/models/filesystem.py
  chroma_core/services/job_scheduler/job_scheduler.py
  chroma_core/services/job_scheduler/job_scheduler_client.py
  chroma_help/help.py
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/action_plugins/ostpool.rs
  iml-agent/src/cli.rs
  iml-agent/src/cmd.rs
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/filesystem.rs
  iml-manager-cli/src/lib.rs
  iml-manager-cli/src/ostpool.rs
  iml-wire-types/wire-types.rs
  liblustreapi-types/build.rs
  liblustreapi-types/src/bindings.rs
  liblustreapi/src/lib.rs
  tests/unit/chroma_core/models/test_advertised_jobs.py
  tests/unit/chroma_core/services/job_scheduler/test_available_jobs.py
Labels: enhancement

#1333 Support both unix socket and TCP communication in the action runner
  Cargo.lock
  iml-services/iml-action-runner/Cargo.toml
  iml-services/iml-action-runner/src/main.rs
Labels: enhancement

#1342 Tokio utils
  Cargo.lock
  iml-services/Cargo.toml
  iml-services/src/services/action_runner/main.rs
  iml-util/Cargo.toml
  iml-util/util.rs
  iml-wasm-components/Cargo.lock
  python-iml-manager.spec
Labels: enhancement

#1344 Add font-awesome componet
  iml-gui/crate/src/components/font_awesome.rs
  iml-gui/crate/src/components/mod.rs
Labels: enhancement

#1347 Implement popover
  iml-gui/crate/LICENSE
  iml-gui/crate/src/components/arrow.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/components/popover.rs
  iml-gui/crate/src/components/tooltip.rs
Labels: enhancement

#1327 Check stratagem
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/action_plugins/package_installed.rs
  iml-agent/src/cli.rs
  iml-agent/src/lib.rs
  iml-agent/src/rpm.rs
Labels: enhancement

#1358 Revert "Fix RemovedInDjango20Warning for user.is_authenticated (#1334)"
  chroma_api/alert.py
  chroma_api/authentication.py
  chroma_api/command.py
  chroma_api/log.py
  chroma_api/session.py
  chroma_api/user.py
Labels: bug

#1356 Extract Action plugin concept
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/daemon_plugins/action_runner.rs
  iml-util/Cargo.toml
  iml-util/util.rs
Labels: enhancement

#1357 Add local action plugins
  Cargo.lock
  chroma_core/lib/job.py
  chroma_core/lib/util.py
  chroma_core/models/host.py
  chroma_core/services/job_scheduler/agent_rpc.py
  iml-services/iml-action-runner/src/data.rs
  iml-services/iml-action-runner/src/error.rs
  iml-services/iml-action-runner/src/lib.rs
  iml-services/iml-action-runner/src/local_actions.rs
  iml-services/iml-action-runner/src/main.rs
  iml-services/iml-action-runner/src/receiver.rs
  iml-services/iml-action-runner/src/sender.rs
  iml-services/iml-action-runner/tests/action_runner_tests.rs
  tests/unit/chroma_core/lib/test_util.py
Labels: enhancement
