Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2019-05, with the labels that each got.

#900 Ensure ZFS settings are retained across reboots
  tests/integration/core/api_testcase_with_test_reset.py
Labels: bug

#902 Use Lustre 2.12.1 from download site when available
  lustre-client.repo
  lustre-server.repo
  tests/framework/utils/defaults.sh.in
Labels: tech debt

#887 Add patchless profile
  .gitignore
  base_managed_patchless.profile
  lustre-server-patchless.repo
  tests/integration/core/chroma_integration_testcase.py
Labels: enhancement

#903 Obsolete old packages
  python-iml-manager.spec.in
Labels: bug

#904 Pin 4.10.0 repo
  .gitignore
  chroma-bundles/chroma_support.repo
  chroma-bundles/include/find_deps.py
  chroma-manager/storage_server.repo
Labels: enhancement

#910 Add pipeline for 5.0 release
  ci/azure-5.0-release-pipeline.yml
  ci/azure-build-pipeline.yml
  ci/template/azure-build-check.yml
  ci/template/azure-clippy.yml
  ci/template/azure-install-lustre.yml
  ci/template/azure-install-rabbit.yml
  ci/template/azure-install-rust.yml
  ci/template/azure-release.yml
  ci/template/azure-rustfmt.yml
  ci/template/azure-test-coverage.yml
  ci/template/azure-test-stable.yml
Labels: enhancement

#908 Add line-delimited streaming support to crypto-client
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/agent_error.rs
  iml-agent/src/http_comms/agent_client.rs
  iml-agent/src/http_comms/crypto_client.rs
Labels: enhancement

#905 Try using 4.0.10.1 for upgrades
  tests/framework/integration/installation_and_upgrade/run_tests
Labels: enhancement

#911 Extract more azure pipelines
  ci/azure-5.0-release-pipeline.yml
  ci/azure-devel-release-pipeline.yml
  ci/azure-test-pipeline.yml
Labels: tech debt

#913 Fix iml_zfs_module_parameters.conf
  tests/integration/core/api_testcase_with_test_reset.py
Labels: bug

#914 Do not build PRs for 5.0
  ci/azure-5.0-release-pipeline.yml
  ci/azure-devel-release-pipeline.yml
Labels: bug

#915 Update to IML 5 repo
  .copr/Makefile
  .gitignore
  .travis.yml
  MANIFEST.in
  Makefile
  chroma_manager/__init__.py
  chroma_manager/scm_version.py
  chroma_support.repo
  docker/base.dockerfile
  include/.gitrepo
  include/LICENSE
  include/Makefile
  include/Makefile.version
  include/README.md
  include/common.mk
  include/copr-mfl.enc
  include/copr.mk
  include/copr_srpm.mk
  include/git-versioning.mk
  include/githooks.mk
  include/hooks/commit-msg
  include/npm.mk
  include/python-common.mk
  include/python-localsrc.mk
  include/python-pypi.mk
  include/rpm-common.mk
  include/rpm.mk
  include/travis/copr-deploy.sh
  include/travis/mock_build_test.sh
  include/travis/run_in_centos7_docker.sh
  include/travis/virus-scan.sh
  python-iml-manager.spec
  requirements.txt
  scm_version.py
  settings.py
  setup.py
  tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup
  tests/framework/services/runner.sh
  tests/framework/utils/defaults.sh.in
Labels: enhancement

#918 Remove obsoletes for httpd
  python-iml-manager.spec
Labels: bug

#920 Scripts folder missing under /usr/share/chroma-manager
  .copr/Makefile
  MANIFEST.in
  python-iml-manager.spec
Labels: bug

#923 Pull version from pkg_resources
  docker/docker-compose.yml
  python-iml-manager.spec
  scm_version.py
Labels: enhancement

#896 Set FQDN so HA works when hostname != FQDN
  chroma_core/models/corosync2.py
  tests/unit/chroma_core/jobs/test_corosync2_jobs.py
Labels: bug

#927 Bump multihost I/O timeout to 60 seconds
  tests/integration/core/api_testcase_with_test_reset.py
Labels: failing tests

#929 Obsolete Django-south
  python-iml-manager.spec
  scm_version.py
Labels: bug

#930 Clear old sessions before upgrading
  chroma_core/lib/service_config.py
  python-iml-manager.spec
  scm_version.py
Labels: bug

#933 Ensure hosts are talking to each other.
  tests/integration/shared_storage_configuration/test_corosync.py
Labels: failing tests

#935 Check selinux status in RebootIfNeeded
  chroma_core/models/host.py
  tests/unit/chroma_core/helpers/mock_agent_rpc.py
Labels: bug, failing tests

#936 Load power-control service after rabbitmq-server.service
  iml-power-control.service
Labels: bug

#949 Bump wasm bindgen dep
  iml-wasm-components/Cargo.lock
  iml-wasm-components/iml-action-dropdown/Cargo.toml
Labels: tech debt

#948 flush_queue should take a oneshot channel for cancelation
  iml-agent-comms/src/flush_queue.rs
  iml-agent-comms/src/host.rs
  iml-agent-comms/src/main.rs
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/main.rs
  iml-agent/src/reader.rs
Labels: bug

#955 Add Managed MLNX Profile
  base_managed_ib_RH7.profile
  lustre-server-mlnx.repo
Labels: enhancement

#950 Implement /mailbox endpoint
  .copr/Makefile
  Cargo.lock
  Cargo.toml
  chroma-manager.conf.template
  chroma_core/lib/service_config.py
  chroma_core/management/commands/print-settings.py
  iml-mailbox.conf
  iml-mailbox.service
  iml-mailbox/Cargo.toml
  iml-mailbox/src/lib.rs
  iml-mailbox/src/main.rs
  iml-manager-env/src/lib.rs
  iml-manager.target
  rust-iml.spec
  settings.py
Labels: enhancement

#901 Create bridge between rust and python layer in the manager
  chroma_core/lib/job.py
  chroma_core/lib/util.py
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/daemon_plugins/action_runner.rs
  iml-manager.target
  python-iml-manager.spec
  requirements.txt
  tests/unit/chroma_core/lib/test_util.py
Labels: enhancement

#960 Ensure action plugin output reflects action result
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/agent_error.rs
  iml-agent/src/env.rs
  iml-agent/src/server_properties.rs
Labels: bug

#961 Fix wasm snapshots
  iml-wasm-components/Cargo.lock
  iml-wasm-components/iml-action-dropdown/src/snapshots/tests__group_actions_by_label_1.snap
  iml-wasm-components/iml-action-dropdown/src/snapshots/tests__group_actions_by_label_2.snap
  iml-wasm-components/iml-action-dropdown/src/snapshots/tests__locks_list.snap
Labels: bug

#962 Fixup coverage test
  ci/template/azure-test-coverage.yml
Labels: bug

#963 Implement mailbox_client
  Cargo.lock
  iml-agent-comms/Cargo.toml
  iml-agent/Cargo.toml
  iml-agent/src/agent_error.rs
  iml-agent/src/http_comms/hyper_client.rs
  iml-agent/src/http_comms/mailbox_client.rs
  iml-agent/src/http_comms/mod.rs
  iml-agent/src/server_properties.rs
  iml-services/Cargo.toml
  iml-warp-drive/Cargo.toml
  tokio-runtime-shutdown/Cargo.toml
Labels: enhancement

#965 Update scan output
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/cli.rs
Labels: enhancement

#966 Add stream_fidlists action.
  Cargo.lock
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/cli.rs
Labels: enhancement

#967 Add initial rust manager cli
  .copr/Makefile
  Cargo.lock
  Cargo.toml
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/api_client.rs
  iml-manager-cli/src/lib.rs
  iml-manager-cli/src/main.rs
  iml-manager-cli/src/manager_cli_error.rs
  iml-manager-env/src/lib.rs
  iml-rabbit/Cargo.toml
  iml-wire-types/src/lib.rs
  rust-iml.spec
Labels: enhancement

#968 Bump seed to the latest version.
  iml-wasm-components/Cargo.lock
  iml-wasm-components/iml-action-dropdown/Cargo.toml
  iml-wasm-components/iml-action-dropdown/src/fetch_actions.rs
  iml-wasm-components/iml-action-dropdown/src/lib.rs
Labels: enhancement

#969 Split off the tooltip into new crate
  iml-wasm-components/.copr/Makefile
  iml-wasm-components/Cargo.lock
  iml-wasm-components/Cargo.toml
  iml-wasm-components/iml-action-dropdown/Cargo.toml
  iml-wasm-components/iml-action-dropdown/src/action_items.rs
  iml-wasm-components/iml-action-dropdown/src/lib.rs
  iml-wasm-components/iml-action-dropdown/src/sleep.rs
  iml-wasm-components/iml-tooltip/Cargo.toml
  iml-wasm-components/iml-tooltip/src/lib.rs
Labels: enhancement

#970 Extract sleep to it's own crate
  iml-wasm-components/Cargo.lock
  iml-wasm-components/Cargo.toml
  iml-wasm-components/iml-action-dropdown/Cargo.toml
  iml-wasm-components/iml-action-dropdown/src/fetch_actions.rs
  iml-wasm-components/iml-action-dropdown/src/lib.rs
  iml-wasm-components/iml-sleep/Cargo.toml
  iml-wasm-components/iml-sleep/src/lib.rs
Labels: enhancement
