Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2019-09, with the labels that each got.

#1197 Move db row representations to iml-wire-types.
  Cargo.lock
  iml-warp-drive/Cargo.toml
  iml-warp-drive/src/cache.rs
  iml-warp-drive/src/db_record.rs
  iml-warp-drive/src/listen.rs
  iml-wasm-components/Cargo.lock
  iml-wasm-components/iml-action-dropdown/Cargo.toml
  iml-wasm-components/iml-action-dropdown/src/model.rs
  iml-wasm-components/iml-action-dropdown/src/snapshots/tests__locks_list.snap
  iml-wasm-components/iml-duration-picker/Cargo.toml
  iml-wasm-components/iml-environment/Cargo.toml
  iml-wasm-components/iml-fs/Cargo.toml
  iml-wasm-components/iml-fs/src/fs_detail_page.rs
  iml-wasm-components/iml-sleep/Cargo.toml
  iml-wasm-components/iml-stratagem/Cargo.toml
  iml-wasm-components/iml-stratagem/src/lib.rs
  iml-wasm-components/iml-toggle/Cargo.toml
  iml-wasm-components/iml-tooltip/Cargo.toml
  iml-wasm-components/iml-utils/Cargo.toml
  iml-wire-types/Cargo.toml
  iml-wire-types/wire-types.rs
Labels: enhancement

#1199 Add check_ha() to iml-agent
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/check_ha.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/agent_error.rs
  iml-agent/src/cli.rs
Labels: enhancement

#1204 Add support for manager-side pragma
  tests/framework/integration/existing_filesystem_configuration/cluster_setup
  tests/framework/integration/installation_and_upgrade/run_tests
  tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup.in
  tests/framework/utils/selective_auto_pass.sh
Labels: enhancement

#1206 Create util crate
  Cargo.lock
  Cargo.toml
  iml-util/Cargo.toml
  iml-util/util.rs
Labels: enhancement

#1209 Update IML version to 5.1.0
  .travis.yml
  ci/azure-5.0-release-pipeline.yml
  python-iml-manager.spec
  scm_version.py
  setup.py
Labels: enhancement

#1211 Fixup python cli
  chroma_api/authentication.py
  chroma_cli/api.py
Labels: bug

#1215 Fix serial scanning
  chroma_core/models/stratagem.py
Labels: bug

#1216 Fix race condition clearing temp table
  chroma_core/models/stratagem.py
  chroma_core/services/job_scheduler/job_scheduler.py
  chroma_core/south_migrations/0046_auto__add_sendstratagemresultstoclientjob__add_stratagemconfiguration_.py
Labels: bug

#1221 Use copr-lustre to build
  ci/azure-test-pipeline.yml
Labels: bug

#1174 SSI: Wait for all clusters before setting volume mounts
  tests/integration/core/chroma_integration_testcase.py
Labels: bug, failing tests

#1223 Use serial try-restart of pacemaker
  tests/integration/core/chroma_integration_testcase.py
Labels: failing tests
