Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2019-08, with the labels that each got.

#1092 Remove mtm when removing target
  chroma_core/models/target.py
Labels: bug

#1118 Start timer after interval from unit activation
  chroma_core/models/stratagem.py
Labels: bug

#1121 Fix splitting devices with hyphenated filesystem names
  chroma_core/lib/util.py
Labels: bug

#1122 Write filepaths instead of csv data
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/stratagem/action_warning.rs
  iml-agent/src/agent_error.rs
  iml-fs/src/lib.rs
Labels: enhancement

#1124 Update perf streaming from MDS to the manager
  Cargo.lock
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-fs/src/lib.rs
  iml-mailbox/Cargo.toml
Labels: bug

#1108 Statagem timer re-add removes old timer
  chroma_core/models/stratagem.py
Labels: bug

#1125 Do not count directories
  chroma_core/models/stratagem.py
  iml-agent/src/action_plugins/stratagem/server.rs
Labels: bug

#947 Manager side device-scanner changes
  chroma-manager.conf.template
  chroma_core/lib/service_config.py
  chroma_core/management/commands/print-settings.py
  chroma_core/plugins/block_devices.py
  chroma_core/plugins/linux.py
  chroma_core/services/lustre_audit/update_scan.py
  docker/docker-compose.yml
  iml-manager.target
  settings.py
Labels: enhancement

#1126 Bump seed to 0.4.0
  iml-wasm-components/Cargo.lock
  iml-wasm-components/bootstrap-components/Cargo.toml
  iml-wasm-components/bootstrap-components/bootstrap.rs
  iml-wasm-components/iml-action-dropdown/Cargo.toml
  iml-wasm-components/iml-action-dropdown/src/action_dropdown.rs
  iml-wasm-components/iml-action-dropdown/src/action_dropdown_error.rs
  iml-wasm-components/iml-action-dropdown/src/deferred_action_dropdown.rs
  iml-wasm-components/iml-action-dropdown/src/hsm_action_dropdown.rs
  iml-wasm-components/iml-action-dropdown/src/lib.rs
  iml-wasm-components/iml-action-dropdown/src/multi_dropdown.rs
  iml-wasm-components/iml-alert-indicator/Cargo.toml
  iml-wasm-components/iml-alert-indicator/src/lib.rs
  iml-wasm-components/iml-duration-picker/Cargo.toml
  iml-wasm-components/iml-duration-picker/src/lib.rs
  iml-wasm-components/iml-environment/Cargo.toml
  iml-wasm-components/iml-fs/Cargo.toml
  iml-wasm-components/iml-fs/src/fs_detail_page.rs
  iml-wasm-components/iml-fs/src/fs_page.rs
  iml-wasm-components/iml-fs/src/lib.rs
  iml-wasm-components/iml-grafana-chart/Cargo.toml
  iml-wasm-components/iml-grafana-chart/src/lib.rs
  iml-wasm-components/iml-lock-indicator/Cargo.toml
  iml-wasm-components/iml-lock-indicator/lock-indicator.rs
  iml-wasm-components/iml-paging/Cargo.toml
  iml-wasm-components/iml-paging/paging.rs
  iml-wasm-components/iml-pie-chart/Cargo.toml
  iml-wasm-components/iml-pie-chart/src/lib.rs
  iml-wasm-components/iml-sleep/Cargo.toml
  iml-wasm-components/iml-stratagem/Cargo.toml
  iml-wasm-components/iml-stratagem/src/delete_stratagem_button.rs
  iml-wasm-components/iml-stratagem/src/enable_stratagem_button.rs
  iml-wasm-components/iml-stratagem/src/inode_error.rs
  iml-wasm-components/iml-stratagem/src/inode_table.rs
  iml-wasm-components/iml-stratagem/src/lib.rs
  iml-wasm-components/iml-stratagem/src/update_stratagem_button.rs
  iml-wasm-components/iml-toggle/Cargo.toml
  iml-wasm-components/iml-toggle/toggle.rs
  iml-wasm-components/iml-tooltip/Cargo.toml
  iml-wasm-components/iml-tooltip/src/lib.rs
  iml-wasm-components/iml-utils/Cargo.toml
  iml-wasm-components/iml-utils/src/lib.rs
  iml-wasm-components/iml-wasm/Cargo.toml
  iml-wasm-components/iml-wasm/src/deferred_action_dropdown.rs
  iml-wasm-components/iml-wasm/src/hsm_dropdown.rs
  iml-wasm-components/iml-wasm/src/multi_action_dropdown.rs
Labels: enhancement

#1131 Add trailing newline to each 1000 fid chunks.
  Cargo.lock
  iml-agent-comms/Cargo.toml
  iml-agent/src/action_plugins/stratagem/action_warning.rs
  iml-manager-cli/Cargo.toml
Labels: bug

#1132 Fix table formatting
  iml-wasm-components/iml-fs/src/fs_detail_page.rs
Labels: enhancement

#1104 Restart grafana during chroma-config setup
  chroma_core/lib/service_config.py
Labels: bug

#1133 When forgetting the filesystem in Monitored mode, also forget Stratagem
  chroma_api/stratagem.py
  chroma_core/models/stratagem.py
  chroma_core/services/job_scheduler/job_scheduler.py
  chroma_core/south_migrations/0046_auto__add_sendstratagemresultstoclientjob__add_stratagemconfiguration_.py
  iml-manager-cli/src/stratagem.rs
  iml-wire-types/src/lib.rs
Labels: enhancement

#1136 Make last column potentially fixed for stratagem config.
  iml-wasm-components/iml-stratagem/src/lib.rs
Labels: bug

#1138 Top inode users table should be truncated after n users
  iml-wasm-components/iml-stratagem/src/inode_table.rs
Labels: enhancement

#1129 Stratagem API checks
  chroma_api/stratagem.py
  chroma_core/models/stratagem.py
  iml-manager-cli/src/manager_cli_error.rs
Labels: bug

#1143 Stratagem Updates
  iml-wasm-components/Cargo.lock
  iml-wasm-components/iml-stratagem/Cargo.toml
  iml-wasm-components/iml-stratagem/src/delete_stratagem_button.rs
  iml-wasm-components/iml-stratagem/src/enable_stratagem_button.rs
  iml-wasm-components/iml-stratagem/src/inode_table.rs
  iml-wasm-components/iml-stratagem/src/lib.rs
  iml-wasm-components/iml-stratagem/src/update_stratagem_button.rs
Labels: enhancement

#1135 Create Separate Scan Now Modal
  iml-wasm-components/Cargo.lock
  iml-wasm-components/iml-action-dropdown/Cargo.toml
  iml-wasm-components/iml-action-dropdown/src/deferred_action_dropdown.rs
  iml-wasm-components/iml-action-dropdown/src/dispatch_custom_event.rs
  iml-wasm-components/iml-action-dropdown/src/hsm_action_dropdown.rs
  iml-wasm-components/iml-action-dropdown/src/lib.rs
  iml-wasm-components/iml-alert-indicator/src/lib.rs
  iml-wasm-components/iml-duration-picker/Cargo.toml
  iml-wasm-components/iml-duration-picker/duration-picker.rs
  iml-wasm-components/iml-environment/Cargo.toml
  iml-wasm-components/iml-fs/Cargo.toml
  iml-wasm-components/iml-fs/src/fs_detail_page.rs
  iml-wasm-components/iml-fs/src/fs_page.rs
  iml-wasm-components/iml-sleep/Cargo.toml
  iml-wasm-components/iml-stratagem/Cargo.toml
  iml-wasm-components/iml-stratagem/src/enable_stratagem_button.rs
  iml-wasm-components/iml-stratagem/src/lib.rs
  iml-wasm-components/iml-stratagem/src/scan_now.rs
  iml-wasm-components/iml-stratagem/src/update_stratagem_button.rs
  iml-wasm-components/iml-toggle/Cargo.toml
  iml-wasm-components/iml-tooltip/Cargo.toml
  iml-wasm-components/iml-utils/Cargo.toml
  iml-wasm-components/iml-utils/src/lib.rs
Labels: enhancement

#1145 Stratagem scan attempts to send fid and purge lists to client, even if
  chroma_api/stratagem.py
  chroma_core/models/stratagem.py
Labels: bug

#1088 Optionally use llapi_rmfids if it's available
  iml-agent/src/action_plugins/stratagem/action_purge.rs
  iml-agent/src/cli.rs
  liblustreapi-types/build.rs
  liblustreapi-types/src/bindings.rs
  liblustreapi/src/lib.rs
Labels: enhancement

#1147 Add Mellanox client profiles / repo
  base_managed_ib_RH7.profile
  lustre-client-mlnx.repo
  posix_copytool_worker_mlnx.profile
  robinhood_server_mlnx.profile
Labels: enhancement

#1140 Enable / Update / Delete stratagem config should show command modal
  chroma_api/stratagem.py
  chroma_core/services/job_scheduler/job_scheduler.py
  chroma_core/services/job_scheduler/job_scheduler_client.py
  iml-wasm-components/iml-duration-picker/duration-picker.rs
  iml-wasm-components/iml-fs/src/fs_detail_page.rs
  iml-wasm-components/iml-stratagem/src/delete_stratagem_button.rs
  iml-wasm-components/iml-stratagem/src/enable_stratagem_button.rs
  iml-wasm-components/iml-stratagem/src/lib.rs
  iml-wasm-components/iml-stratagem/src/scan_now.rs
  iml-wasm-components/iml-stratagem/src/update_stratagem_button.rs
Labels: enhancement

#1148 Chroma config profile
  chroma_core/lib/service_config.py
Labels: enhancement

#1149 Stratagem duration values need to load using the maximuim unit that doesn't have a remainder.
  iml-wasm-components/iml-duration-picker/duration-picker.rs
  iml-wasm-components/iml-stratagem/src/lib.rs
Labels: bug

#1150 Add support for returning sizes of file counts.
  Cargo.lock
  chroma_core/lib/stratagem.py
  chroma_core/models/stratagem.py
  grafana/dashboards/stratagem-dashboard-1.json
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/cli.rs
  iml-wasm-components/iml-fs/src/fs_detail_page.rs
  iml-wasm-components/iml-stratagem/src/inode_table.rs
  iml-wasm-components/iml-stratagem/src/lib.rs
Labels: enhancement

#1154 Fix warp-drive to start server after API request finishes.
  iml-warp-drive/src/main.rs
Labels: bug

#1036 Temporary solution for race between plugin_runner and device-aggregator
  .copr/Makefile
  10-device-aggregator.service.conf
  chroma_core/plugins/block_devices.py
  chroma_core/plugins/linux.py
  python-iml-manager.spec
Labels: bug

#1155 Skip removal of bundle_name index
  chroma_core/south_migrations/0044_auto__del_bundle__del_unique_bundle_bundle_name__add_repo__add_unique_.py
Labels: bug

#1159 Some small text updates
  chroma_core/services/job_scheduler/job_scheduler.py
  chroma_help/help.py
  iml-wasm-components/iml-stratagem/src/inode_table.rs
Labels: enhancement

#1162 Update stratagem cli wording
  iml-manager-cli/src/stratagem.rs
Labels: enhancement

#1158 Create influx measurements and dynamic grafana dashboards for each fi…
  chroma_api/stratagem.py
  chroma_core/lib/stratagem.py
  chroma_core/models/stratagem.py
  chroma_core/services/job_scheduler/job_scheduler.py
  chroma_core/services/job_scheduler/job_scheduler_client.py
  chroma_core/south_migrations/0046_auto__add_sendstratagemresultstoclientjob__add_stratagemconfiguration_.py
  grafana/dashboards/stratagem-dashboard-1.json
  iml-wasm-components/Cargo.lock
  iml-wasm-components/iml-fs/src/fs_detail_page.rs
  iml-wasm-components/iml-grafana-chart/Cargo.toml
  iml-wasm-components/iml-grafana-chart/src/lib.rs
  iml-wasm-components/iml-stratagem/src/inode_table.rs
  iml-wasm-components/iml-stratagem/src/lib.rs
Labels: enhancement

#1163 Add command to update stratagem interval
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/stratagem.rs
  iml-manager-client/src/lib.rs
  iml-wire-types/src/lib.rs
Labels: enhancement

#1164 GH-1157 - Show legend for file-size and space distribution charts
  grafana/dashboards/stratagem-dashboard-1.json
Labels: enhancement

#1166 Serve mailbox files from Nginx directly
  Cargo.lock
  chroma-manager.conf.template
  chroma_core/lib/service_config.py
  iml-mailbox/src/main.rs
Labels: enhancement

#1168 Use tracing instead of log
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/stratagem/action_purge.rs
  iml-agent/src/action_plugins/stratagem/action_warning.rs
  iml-agent/src/cli.rs
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/http_comms/agent_client.rs
  iml-agent/src/http_comms/mailbox_client.rs
  iml-agent/src/http_comms/session.rs
  iml-agent/src/main.rs
  iml-agent/src/poller.rs
  iml-agent/src/reader.rs
Labels: enhancement

#1170 Remove stream-lines dep
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/http_comms/crypto_client.rs
  iml-agent/src/http_comms/mailbox_client.rs
  iml-fs/Cargo.toml
  iml-fs/src/lib.rs
  iml-mailbox/Cargo.toml
  iml-mailbox/src/lib.rs
  iml-mailbox/src/main.rs
  iml-manager-client/Cargo.toml
Labels: enhancement

#1167 Stratagem buttons should be disabled based on write locks
  chroma_core/models/stratagem.py
  chroma_core/services/job_scheduler/job_scheduler.py
  chroma_core/south_migrations/0046_auto__add_sendstratagemresultstoclientjob__add_stratagemconfiguration_.py
  iml-wasm-components/iml-fs/src/fs_detail_page.rs
  iml-wasm-components/iml-stratagem/src/lib.rs
  iml-wasm-components/iml-stratagem/src/scan_now.rs
Labels: enhancement

#1173 Update Lock
  iml-wasm-components/iml-stratagem/src/scan_now.rs
Labels: bug

#1144 Only clear shutdown ring0 if it's set
  tests/integration/core/clear_ha_el7.sh
  tests/integration/core/remote_operations.py
Labels: failing tests

#1165 Stratagem GUI should be hidden if not available
  chroma_api/target.py
  iml-wasm-components/iml-fs/src/fs_detail_page.rs
Labels: bug
