Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2019-06, with the labels that each got.

#964 Use devel repo everywhere, with single point of change
  .copr/Makefile
  .gitignore
  .travis.yml
  Makefile
  base.repo.in
  chroma_support.repo
  tests/framework/chroma_support.repo.in
  tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup.in
  tests/framework/services/runner.sh.in
Labels: bug

#980 Fixup mailbox streaming
  .copr/Makefile
  Cargo.lock
  Cargo.toml
  chroma_core/lib/service_config.py
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/agent_error.rs
  iml-agent/src/http_comms/mailbox_client.rs
  iml-agent/src/lib.rs
  iml-fs/Cargo.toml
  iml-fs/src/lib.rs
  iml-mailbox/Cargo.toml
  iml-mailbox/src/lib.rs
  iml-mailbox/src/main.rs
  iml-manager-cli/src/main.rs
  python-iml-manager.spec
Labels: enhancement

#979 Propagate step results to next step during job execution
  chroma_core/services/job_scheduler/job_scheduler.py
Labels: enhancement

#982 Remove max-body for mailbox endpoint
  chroma-manager.conf.template
Labels: bug

#981 Add invoke_rust_agent_expect_result
  chroma_core/lib/job.py
Labels: enhancement

#983 Wait for cmd
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/lib.rs
  iml-manager-cli/src/main.rs
  iml-manager-cli/src/manager_cli_error.rs
  iml-wire-types/src/lib.rs
Labels: enhancement

#985 Some small fixups for agent cli
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/cli.rs
Labels: enhancement

#912 Add function to read stratagem warning mailbox
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/stratagem/action_purge.rs
  iml-agent/src/action_plugins/stratagem/action_warning.rs
  iml-agent/src/action_plugins/stratagem/mod.rs
  iml-agent/src/cli.rs
  iml-agent/src/env.rs
  iml-agent/src/fidlist.rs
  iml-agent/src/lib.rs
  liblustreapi/src/lib.rs
Labels: enhancement

#987 Add top-level wasm package
  iml-wasm-components/Cargo.lock
  iml-wasm-components/Cargo.toml
  iml-wasm-components/iml-action-dropdown/Cargo.toml
  iml-wasm-components/iml-action-dropdown/src/lib.rs
  iml-wasm-components/iml-wasm/Cargo.toml
  iml-wasm-components/iml-wasm/src/lib.rs
Labels: enhancement

#978 Add influxdb to base.repo and Requires
  base.repo.in
  chroma_core/lib/service_config.py
  docker/docker-compose.override.yml
  docker/docker-compose.yml
  python-iml-manager.spec
  tests/framework/chroma_support.repo.in
Labels: enhancement

#990 Add action types
  Cargo.lock
  iml-wire-types/Cargo.toml
  iml-wire-types/src/lib.rs
Labels: enhancement

#986 Add support for `LAT_ATTR_CLASSIFY` rules
  Cargo.lock
  iml-agent/src/action_plugins/stratagem/action_purge.rs
  iml-agent/src/action_plugins/stratagem/action_warning.rs
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/cli.rs
  iml-mailbox/src/lib.rs
Labels: enhancement

#984 Wait on jobs
  chroma_core/services/job_scheduler/command_plan.py
  chroma_core/services/job_scheduler/job_scheduler.py
Labels: enhancement

#991 Add cli flags to stratagem command
  iml-manager-cli/src/main.rs
  iml-manager-cli/src/manager_cli_error.rs
Labels: enhancement

#993 Pin Rabbitmq-server
  python-iml-manager.spec
Labels: dependencies

#995 Simplify plugin types
  iml-agent/src/action_plugins/action_plugin.rs
Labels: enhancement

#994 Wire up client action plugins
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/stratagem/action_warning.rs
  iml-agent/src/lib.rs
Labels: enhancement

#996 Grafana
  .copr/Makefile
  chroma_core/lib/service_config.py
  docker/docker-compose.override.yml
  docker/docker-compose.yml
  grafana-iml.ini
  python-iml-manager.spec
  tests/framework/chroma_support.repo.in
Labels: enhancement

#998 Parse fids as non-JSON
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/stratagem/action_purge.rs
  iml-agent/src/action_plugins/stratagem/action_warning.rs
Labels: tech debt

#997 Add iml-postgres crate
  Cargo.lock
  Cargo.toml
  iml-agent/Cargo.toml
  iml-manager-env/src/lib.rs
  iml-postgres/Cargo.toml
  iml-postgres/src/lib.rs
Labels: enhancement

#989 Bump seed to latest version
  iml-wasm-components/Cargo.lock
  iml-wasm-components/iml-action-dropdown/Cargo.toml
  iml-wasm-components/iml-action-dropdown/src/action_dropdown.rs
  iml-wasm-components/iml-action-dropdown/src/action_dropdown_error.rs
  iml-wasm-components/iml-action-dropdown/src/action_items.rs
  iml-wasm-components/iml-action-dropdown/src/button.rs
  iml-wasm-components/iml-action-dropdown/src/fetch.rs
  iml-wasm-components/iml-action-dropdown/src/fetch_actions.rs
  iml-wasm-components/iml-action-dropdown/src/hsm.rs
  iml-wasm-components/iml-action-dropdown/src/hsm_dropdown.rs
  iml-wasm-components/iml-action-dropdown/src/lib.rs
  iml-wasm-components/iml-action-dropdown/src/model.rs
  iml-wasm-components/iml-action-dropdown/src/update.rs
  iml-wasm-components/iml-duration-picker/cargo.toml
  iml-wasm-components/iml-sleep/Cargo.toml
  iml-wasm-components/iml-sleep/src/lib.rs
  iml-wasm-components/iml-tooltip/Cargo.toml
  iml-wasm-components/iml-wasm/src/lib.rs
Labels: enhancement

#999 Update influx db name for stratagem scans
  chroma_core/lib/service_config.py
  settings.py
Labels: enhancement

#1005 Fixup mdc_stat call
  Cargo.lock
  iml-agent/src/action_plugins/stratagem/action_warning.rs
  liblustreapi-sys/Cargo.toml
  liblustreapi/Cargo.toml
  liblustreapi/src/lib.rs
Labels: bug

#1006 Ensure filename passed to IOC_MDC_GETFILEINFO is null terminated
  liblustreapi/src/lib.rs
Labels: bug

#1009 Split config between warn and purge rules
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/cli.rs
Labels: bug

#1010 Extract manager API client
  Cargo.lock
  Cargo.toml
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/lib.rs
  iml-manager-cli/src/main.rs
  iml-manager-cli/src/manager_cli_error.rs
  iml-manager-client/Cargo.toml
  iml-manager-client/src/lib.rs
Labels: tech debt

#1011 Fix fid error
  liblustreapi/src/lib.rs
Labels: bug

#1008 Ensure ntpd is running
  chroma_core/lib/service_config.py
Labels: bug

#1013 Update deps
  iml-wasm-components/Cargo.lock
  iml-wasm-components/iml-action-dropdown/Cargo.toml
  iml-wasm-components/iml-action-dropdown/src/action_dropdown.rs
  iml-wasm-components/iml-action-dropdown/src/hsm_dropdown.rs
  iml-wasm-components/iml-action-dropdown/src/lib.rs
  iml-wasm-components/iml-duration-picker/cargo.toml
  iml-wasm-components/iml-sleep/Cargo.toml
  iml-wasm-components/iml-tooltip/Cargo.toml
Labels: enhancement

#1014 Update wire-types
  Cargo.lock
  iml-agent-comms/Cargo.toml
  iml-agent/Cargo.toml
  iml-manager-cli/Cargo.toml
  iml-rabbit/Cargo.toml
  iml-services/Cargo.toml
  iml-wire-types/Cargo.toml
  iml-wire-types/src/lib.rs
Labels: enhancement

#1015 Add util and enviroment wasm modules
  iml-wasm-components/iml-environment/Cargo.toml
  iml-wasm-components/iml-environment/src/lib.rs
  iml-wasm-components/iml-utils/Cargo.toml
  iml-wasm-components/iml-utils/src/lib.rs
Labels: enhancement

#1019 Create popover component
  iml-wasm-components/Cargo.lock
  iml-wasm-components/Cargo.toml
  iml-wasm-components/iml-popover/Cargo.toml
  iml-wasm-components/iml-popover/src/lib.rs
Labels: enhancement

#1021 Implement Alert indicator
  iml-wasm-components/Cargo.lock
  iml-wasm-components/Cargo.toml
  iml-wasm-components/iml-alert-indicator/Cargo.toml
  iml-wasm-components/iml-alert-indicator/src/lib.rs
Labels: enhancement

#1022 Move lock types into wire-types
  Cargo.lock
  iml-agent-comms/Cargo.toml
  iml-agent/Cargo.toml
  iml-manager-cli/Cargo.toml
  iml-rabbit/Cargo.toml
  iml-services/Cargo.toml
  iml-warp-drive/Cargo.toml
  iml-warp-drive/src/locks.rs
  iml-warp-drive/src/request.rs
  iml-wasm-components/Cargo.lock
  iml-wasm-components/iml-action-dropdown/Cargo.toml
  iml-wasm-components/iml-action-dropdown/src/hsm_dropdown.rs
  iml-wasm-components/iml-action-dropdown/src/model.rs
  iml-wasm-components/iml-alert-indicator/Cargo.toml
  iml-wire-types/Cargo.toml
  iml-wire-types/src/lib.rs
Labels: enhancement

#1003 Add Grafana reverse proxy to nginx
  chroma-manager.conf.template
  chroma_api/session.py
  chroma_api/urls.py
  chroma_core/lib/service_config.py
  grafana-iml.ini
  tests/integration/shared_storage_configuration/test_anonymous_access_control.py
Labels: enhancement

#1024 Add support for Lustre 2.12.2
  lustre-client.repo
  lustre-server-patchless.repo
  lustre-server.repo
  tests/framework/utils/defaults.sh.in
Labels: enhancement

#1020 Update command to account for stratagem status
  iml-manager-cli/src/main.rs
  iml-manager-cli/src/manager_cli_error.rs
  iml-manager-client/src/lib.rs
Labels: enhancement
