Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2019-10, with the labels that each got.

#1229 Lock patchless profile to el7.6
  base_managed_patchless.profile
Labels: bug

#1230 Lower all alerts associated with a host when it is removed
  chroma_core/models/host.py
  chroma_core/models/utils.py
Labels: enhancement

#1225 Add ComponentState structs and sub enums
  iml-wire-types/wire-types.rs
Labels: enhancement

#1233 RunState::Stopped for inactive and disabled
  iml-wire-types/wire-types.rs
Labels: bug

#1235 Bump rust iml to 0.1.2
  python-iml-manager.spec
  rust-iml.spec
Labels: dependencies

#1236 - Fix date in changelog
  rust-iml.spec
Labels: bug

#1252 Fix travis unit test failures
  .travis.yml
Labels: bug

#1259 Bump view-server dep
  python-iml-manager.spec
Labels: bug

#1258 Wasm bump
  iml-wasm-components/Cargo.lock
Labels: bug

#1261 Remove old egg info upon upgrade.
  python-iml-manager.spec
Labels: bug

#1268 Bump Vagrant box version for test
  Vagrantfile
  tests/framework/utils/defaults.sh.in
  tests/framework/utils/provisioner_interface/provision_cluster
Labels: enhancement

#1266 GH-1246 - Stop services during setup before restarting rabbitmq
  chroma_core/lib/service_config.py
Labels: bug

#1265 Centrally define base packages
  chroma_agent_comms/views.py
  chroma_core/models/host.py
  chroma_core/models/server_profile.py
  chroma_core/services/lustre_audit/update_scan.py
Labels: bug

#1267 GH-1260 - Support Lustre 2.12.3
  lustre-client-mlnx.repo
  lustre-client.repo
  lustre-server-mlnx.repo
  lustre-server-patchless.repo
  lustre-server.repo
  tests/framework/utils/defaults.sh.in
Labels: enhancement

#1272 Remove duplicate method
  chroma_api/stratagem.py
Labels: bug

#1284 Lock influxdb yum repo to "7"
  tests/framework/chroma_support.repo.in
Labels: bug

#1276 Fix patchless validate for 2.12.3
  base_managed_patchless.profile
  tests/framework/integration/existing_filesystem_configuration/cluster_setup
  tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup.in
Labels: bug

#1271 GH-1248 Add package-upgrade check
  tests/integration/core/remote_operations.py
  tests/integration/installation_and_upgrade/test_update_with_yum.py
Labels: enhancement

#1227 Rely more on systemd for service management
  chroma_core/lib/service_config.py
  iml-gunicorn.service
  iml-job-scheduler.service
  iml-mailbox.service
  iml-manager.target
  iml-warp-drive/systemd-units/iml-warp-drive.service
Labels: enhancement

#1220 Split service binaries to separate crates
  Cargo.lock
  Cargo.toml
  iml-services/Cargo.toml
  iml-services/iml-action-runner/Cargo.toml
  iml-services/iml-action-runner/src/data.rs
  iml-services/iml-action-runner/src/error.rs
  iml-services/iml-action-runner/src/lib.rs
  iml-services/iml-action-runner/src/main.rs
  iml-services/iml-action-runner/src/receiver.rs
  iml-services/iml-action-runner/src/sender.rs
  iml-services/iml-action-runner/tests/action_runner_tests.rs
  iml-services/iml-service-queue/Cargo.toml
  iml-services/iml-service-queue/src/lib.rs
  iml-services/iml-service-queue/src/service_queue.rs
  iml-services/iml-stratagem/Cargo.toml
  iml-services/iml-stratagem/src/main.rs
  iml-services/src/services/action_runner/mod.rs
  iml-services/src/services/mod.rs
Labels: enhancement

#1286 Remove chroma-host-discover
  .copr/Makefile
  chroma-host-discover
  chroma-host-discover-init.sh
  python-iml-manager.spec
  setup.py
Labels: bug

#1198 Add support for github actions
  .copr/Makefile
  .github/actions/copr-rust/action.yml
  .github/actions/copr-wasm/action.yml
  .github/workflows/devel-release.yml
  .github/workflows/prod-release.yml
  .github/workflows/rust-ci.yml
  .github/workflows/wasm-ci.yml
  README.md
  ci/azure-5.0-release-pipeline.yml
  ci/azure-devel-release-pipeline.yml
  ci/azure-test-pipeline.yml
  ci/template/azure-build-check.yml
  ci/template/azure-clippy.yml
  ci/template/azure-install-lustre.yml
  ci/template/azure-install-rabbit.yml
  ci/template/azure-install-rust.yml
  ci/template/azure-release.yml
  ci/template/azure-rustfmt.yml
  ci/template/azure-test-coverage.yml
  ci/template/azure-test-stable.yml
  iml-wasm-components/.copr/Makefile
Labels: enhancement

#1275 Async manager
  Cargo.lock
  Cargo.toml
  chroma_core/management/commands/print-settings.py
  iml-agent-comms/Cargo.toml
  iml-agent-comms/src/error.rs
  iml-agent-comms/src/flush_queue.rs
  iml-agent-comms/src/host.rs
  iml-agent-comms/src/lib.rs
  iml-agent-comms/src/main.rs
  iml-agent-comms/src/messaging.rs
  iml-agent-comms/src/session.rs
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/check_ha.rs
  iml-agent/src/daemon_plugins/action_runner.rs
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/http_comms/hyper_client.rs
  iml-agent/src/http_comms/session.rs
  iml-agent/src/reader.rs
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/error.rs
  iml-manager-cli/src/lib.rs
  iml-manager-cli/src/main.rs
  iml-manager-cli/src/server.rs
  iml-manager-cli/src/stratagem.rs
  iml-manager-client/Cargo.toml
  iml-manager-client/src/lib.rs
  iml-manager-env/src/lib.rs
  iml-postgres/Cargo.toml
  iml-postgres/src/lib.rs
  iml-rabbit/Cargo.toml
  iml-rabbit/src/lib.rs
  iml-services/iml-action-runner/Cargo.toml
  iml-services/iml-action-runner/src/data.rs
  iml-services/iml-action-runner/src/error.rs
  iml-services/iml-action-runner/src/main.rs
  iml-services/iml-action-runner/src/receiver.rs
  iml-services/iml-action-runner/src/sender.rs
  iml-services/iml-action-runner/tests/action_runner_tests.rs
  iml-services/iml-service-queue/Cargo.toml
  iml-services/iml-service-queue/src/service_queue.rs
  iml-services/iml-stratagem/Cargo.toml
  iml-services/iml-stratagem/src/main.rs
  iml-util/util.rs
  iml-warp-drive/Cargo.toml
  iml-warp-drive/src/cache.rs
  iml-warp-drive/src/error.rs
  iml-warp-drive/src/lib.rs
  iml-warp-drive/src/listen.rs
  iml-warp-drive/src/locks.rs
  iml-warp-drive/src/main.rs
  iml-warp-drive/src/users.rs
  iml-wire-types/Cargo.toml
  iml-wire-types/wire-types.rs
  liblustreapi/src/lib.rs
  rust-iml.spec
  tests/framework/utils/selective_auto_pass.sh
  tokio-runtime-shutdown/Cargo.toml
  tokio-runtime-shutdown/src/lib.rs
Labels: enhancement

#1219 Batch purge operations.
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/check_ha.rs
  iml-agent/src/action_plugins/stratagem/action_purge.rs
  iml-agent/src/action_plugins/stratagem/action_warning.rs
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/agent_error.rs
  iml-agent/src/cli.rs
  iml-agent/src/cmd.rs
  iml-agent/src/daemon_plugins/action_runner.rs
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/http_comms/agent_client.rs
  iml-agent/src/http_comms/crypto_client.rs
  iml-agent/src/http_comms/hyper_client.rs
  iml-agent/src/http_comms/mailbox_client.rs
  iml-agent/src/http_comms/session.rs
  iml-agent/src/main.rs
  iml-agent/src/poller.rs
  iml-agent/src/reader.rs
  iml-agent/src/systemd.rs
  liblustreapi-types/Cargo.toml
  liblustreapi/Cargo.toml
  liblustreapi/src/error.rs
  liblustreapi/src/lib.rs
Labels: bug

#1291 Add support to display command progress for multiple commands
  Cargo.lock
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/display_utils.rs
  iml-manager-cli/src/error.rs
  iml-wasm-components/Cargo.lock
Labels: enhancement

#1289 Swap rabbitmq stop / start with restart
  chroma_core/lib/service_config.py
Labels: tech debt

#1292 Black formatting fixes.
  chroma_cli/parser.py
  chroma_core/models/host.py
  docker/iml-warp-drive.dockerfile
  requirements.test
  requirements.txt
  settings.py
  tests/integration/core/constants.py
  tests/services/test_agent_rpc.py
  tests/unit/chroma_api/test_stats.py
  tests/unit/chroma_api/test_target.py
  tests/unit/chroma_core/models/test_samples.py
  tests/unit/chroma_core/models/test_series.py
Labels: bug

#1282 Agent check_stonith
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/check_stonith.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/agent_error.rs
  iml-agent/src/cli.rs
Labels: enhancement

#1294 Fixup action checks
  .github/workflows/wasm-ci.yml
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/update_repo_file.rs
Labels: bug
