Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2020-05, with the labels that each got.

#1849 Add force-remove hosts to IML CLI
  iml-manager-cli/src/server.rs
Labels: enhancement, needs-docs

#1847 Make settings populator call atomic
  iml-settings-populator.service
Labels: enhancement

#1856 Always show the command_details button for commands
  iml-gui/crate/src/page/activity.rs
Labels: enhancement, needs-docs

#1854 Fix OST pool CLI display
  iml-manager-cli/src/ostpool.rs
Labels: bug

#1857 Switch println to tracing::debug in test-utils
  Cargo.lock
  iml-system-test-utils/Cargo.toml
  iml-system-test-utils/src/lib.rs
  iml-system-test-utils/src/ssh.rs
  iml-system-test-utils/src/vagrant.rs
Labels: enhancement

#1846 Use smaller locks around daemon plugins
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/daemon_plugins/action_runner.rs
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/daemon_plugins/device.rs
  iml-agent/src/daemon_plugins/postoffice.rs
  iml-agent/src/http_comms/session.rs
  iml-agent/src/poller.rs
  iml-agent/src/reader.rs
Labels: enhancement

#1864 Fix volume lookup
  chroma_core/models/stratagem.py
Labels: bug

#1866 Update Lustre to 2.12.4
  lustre-client-mlnx.repo
  lustre-client.repo
  lustre-server-mlnx.repo
  lustre-server-patchless.repo
  lustre-server.repo
Labels: chore

#1867 Add "make local" target to create dated releases
  Makefile
  vagrant/scripts/install_iml_local.sh
Labels: enhancement

#1863 Try to use rabbitmq-server dropin
  .copr/Makefile
  iml-action-runner.service
  iml-action-runner.socket
  iml-agent-comms.service
  iml-api.service
  iml-corosync.service
  iml-device.service
  iml-gunicorn.service
  iml-http-agent.service
  iml-job-scheduler.service
  iml-lustre-audit.service
  iml-mailbox.service
  iml-ntp.service
  iml-ostpool.service
  iml-plugin-runner.service
  iml-postoffice.service
  iml-power-control.service
  iml-rust-stats.service
  iml-syslog.service
  iml-system-test-utils/src/lib.rs
  iml-system-test-utils/src/ssh.rs
  iml-system-test-utils/src/vagrant.rs
  iml-warp-drive/systemd-units/iml-warp-drive.service
  python-iml-manager.spec
  rabbitmq-server-dropin.conf
Labels: bug

#1874 Service Queue: print debug string instead of vec
  iml-services/iml-service-queue/src/service_queue.rs
Labels: enhancement

#1869 Fill device state
  iml-agent/src/daemon_plugins/device.rs
Labels: bug

#1796 1353 steps modal
  iml-gui/crate/Cargo.lock
  iml-gui/crate/Cargo.toml
  iml-gui/crate/src/components/command_modal.rs
  iml-gui/crate/src/components/modal.rs
  iml-gui/crate/src/dependency_tree.rs
  iml-gui/crate/src/generated/css_classes.rs
  iml-gui/crate/src/lib.rs
  iml-wire-types/src/lib.rs
Labels: enhancement

#1886 Fix missing gpgkey for local install
  vagrant/scripts/install_iml_local.sh
Labels: bug

#1885 Fix target failover
  chroma_core/models/target.py
Labels: bug

#1888 Bump deps to latest
  Cargo.lock
  iml-agent/src/daemon_plugins/device.rs
  iml-agent/src/daemon_plugins/postoffice.rs
Labels: chore

#1889 Add `Executable` trait to iml-orm
  Cargo.lock
  iml-manager-cli/src/profile.rs
  iml-orm/Cargo.toml
  iml-orm/src/alerts.rs
  iml-orm/src/lib.rs
  iml-orm/src/profile.rs
  iml-services/iml-ntp/src/main.rs
Labels: enhancement

#1824 Task Queue: rename Action queue to task queue
  Cargo.lock
  chroma-manager.conf.template
  chroma_core/migrations/0016_action_queue.py
  chroma_core/migrations/0016_task.py
  chroma_core/models/__init__.py
  chroma_core/models/action_queue.py
  chroma_core/models/task.py
  chroma_core/services/job_scheduler/job_scheduler.py
  chroma_core/services/job_scheduler/job_scheduler_client.py
  chroma_help/help.py
  iml-api/Cargo.toml
  iml-api/src/command.rs
  iml-api/src/error.rs
  iml-api/src/main.rs
  iml-api/src/task.rs
  iml-orm/README.md
  iml-orm/src/command.rs
  iml-orm/src/fidtaskqueue.rs
  iml-orm/src/job.rs
  iml-orm/src/lib.rs
  iml-orm/src/lustrefid.rs
  iml-orm/src/models.rs
  iml-orm/src/schema.rs
  iml-orm/src/step.rs
  iml-orm/src/task.rs
  rust-iml.spec
  tests/unit/chroma_core/models/test_advertised_jobs.py
  tests/unit/chroma_core/services/job_scheduler/test_available_jobs.py
Labels: enhancement

#1894 Race between agent and manager to resolve action
  iml-services/iml-action-runner/src/data.rs
  iml-services/iml-action-runner/src/sender.rs
Labels: bug

#1881 Optimize local builds
  .copr/Makefile
  vagrant/scripts/install_iml_local.sh
Labels: enhancement

#1914 Load devices at startup
  Cargo.lock
  iml-services/iml-device/src/error.rs
  iml-services/iml-device/src/main.rs
Labels: enhancement

#1913 Avoid pg_notify if rows are identical
  chroma_core/migrations/__init__.py
Labels: bug

#1912 Do not print empty tables
  iml-manager-cli/src/display_utils.rs
Labels: bug

#1900 Integration Test Host Updates
  iml-system-docker-tests/Cargo.lock
  iml-system-docker-tests/src/lib.rs
  iml-system-docker-tests/tests/ldiskfs_test.rs
  iml-system-docker-tests/tests/stratagem_test.rs
  iml-system-rpm-tests/Cargo.lock
  iml-system-rpm-tests/src/lib.rs
  iml-system-rpm-tests/tests/stratagem_test.rs
  iml-system-test-utils/src/lib.rs
  iml-system-test-utils/src/ssh.rs
  iml-system-test-utils/src/vagrant.rs
Labels: failing tests

#1899 Cancel jobs for command modal
  iml-gui/crate/src/components/command_modal.rs
Labels: enhancement

#1909 Update how vm's are destroyed
  iml-system-docker-tests/src/lib.rs
  iml-system-rpm-tests/src/lib.rs
  iml-system-test-utils/src/vagrant.rs
Labels: failing tests

#1918 Add trait for determining changes between old and new collections
  iml-orm/src/lib.rs
Labels: enhancement

#1823 Implement SFA monitor
  .copr/Makefile
  .github/workflows/iml-gui.yml
  Cargo.lock
  Cargo.toml
  chroma_core/management/commands/print-settings.py
  chroma_core/migrations/0017_sfaenclosure_sfastoragesystem.py
  chroma_core/migrations/0018_sfa_json_notify.py
  chroma_core/models/__init__.py
  chroma_core/models/sfa.py
  docker/docker-compose.yml
  docker/iml-sfa.dockerfile
  iml-api/src/main.rs
  iml-gui/crate/Cargo.lock
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/test_utils/fixtures.rs
  iml-manager-env/Cargo.toml
  iml-manager-env/src/lib.rs
  iml-manager.target
  iml-orm/Cargo.toml
  iml-orm/fixtures/disks.xml
  iml-orm/src/alerts.rs
  iml-orm/src/lib.rs
  iml-orm/src/schema.rs
  iml-orm/src/sfa/mod.rs
  iml-orm/src/sfa/tokio_postgres_interop.rs
  iml-orm/src/sfa/wbem_interop.rs
  iml-sfa.service
  iml-sfa/Cargo.toml
  iml-sfa/src/main.rs
  iml-system-test-utils/src/vagrant.rs
  iml-warp-drive/Cargo.toml
  iml-warp-drive/src/cache.rs
  iml-warp-drive/src/db_record.rs
  iml-wire-types/Cargo.toml
  iml-wire-types/src/db.rs
  iml-wire-types/src/lib.rs
  iml-wire-types/src/warp_drive.rs
  python-iml-manager.spec
  rust-iml.spec
  settings.py
  vagrant/scripts/install_iml_local.sh
  wbem-client/fixtures/instance.xml
  wbem-client/src/cim_xml.rs
  wbem-client/src/lib.rs
  wbem-client/src/sfa_classes.rs
  wbem-client/src/snapshots/wbem_client__cim_xml__req__tests__build_imethodcall_instance.snap
  wbem-client/src/snapshots/wbem_client__cim_xml__resp__tests__instance.snap
  wbem-client/src/snapshots/wbem_client__cim_xml__resp__tests__instance_list.snap
  wbem-client/src/snapshots/wbem_client__sfa_classes__tests__sfa_enclosure.snap
  wbem-client/src/snapshots/wbem_client__sfa_classes__tests__sfa_storage_instasnce.snap
Labels: enhancement

#1915 Integrate pipenv
  Pipfile
  Pipfile.lock
Labels: chore

#1925 Add enclosure model field
  chroma_core/migrations/0017_sfaenclosure_sfastoragesystem.py
  chroma_core/models/sfa.py
  iml-orm/src/schema.rs
  iml-orm/src/sfa/mod.rs
  iml-orm/src/sfa/tokio_postgres_interop.rs
  iml-orm/src/sfa/wbem_interop.rs
Labels: enhancement

#1924 Handle existing lustre_fid
  chroma_core/migrations/__init__.py
Labels: bug

#1926 SFA Integration fixups
  Cargo.lock
  iml-gui/crate/Cargo.lock
  iml-orm/Cargo.toml
  iml-orm/src/lib.rs
  iml-orm/src/sfa/mod.rs
  iml-sfa/src/main.rs
  iml-wire-types/src/db.rs
Labels: bug

#1927 Update server list trait
  iml-system-docker-tests/Cargo.lock
  iml-system-docker-tests/src/lib.rs
  iml-system-docker-tests/tests/ldiskfs_test.rs
  iml-system-docker-tests/tests/stratagem_test.rs
  iml-system-docker-tests/tests/zfs_test.rs
  iml-system-rpm-tests/Cargo.lock
  iml-system-rpm-tests/src/lib.rs
  iml-system-rpm-tests/tests/ldiskfs_test.rs
  iml-system-rpm-tests/tests/stratagem_test.rs
  iml-system-rpm-tests/tests/zfs_test.rs
  iml-system-test-utils/src/iml.rs
  iml-system-test-utils/src/lib.rs
  iml-system-test-utils/src/vagrant.rs
Labels: enhancement

#1929 Add Action Runner Client crate
  Cargo.lock
  Cargo.toml
  iml-action-client/Cargo.toml
  iml-action-client/src/lib.rs
  iml-manager-env/Cargo.toml
  iml-manager-env/src/lib.rs
  iml-wire-types/src/lib.rs
Labels: enhancement
