Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2020-11, with the labels that each got.

#2357 Fix Bug in generic file scan
  chroma_core/models/stratagem.py
Labels: bug

#2321 Begin converting the linux plugin over to rust
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/agent_error.rs
  iml-agent/src/fixtures/network_interfaces.txt
  iml-agent/src/fixtures/network_stats.txt
  iml-agent/src/lib.rs
  iml-agent/src/network_interface.rs
  iml-agent/src/network_interface_stats.rs
  iml-agent/src/network_interfaces.rs
  iml-agent/src/snapshots/iml_agent__network_interface__tests__parsing_multiple_interfaces.snap
  iml-agent/src/snapshots/iml_agent__network_interface_stats__tests__parse.snap
  iml-gui/crate/Cargo.lock
  iml-wire-types/Cargo.toml
  iml-wire-types/src/lib.rs
Labels: enhancement

#2353 Integrate network interface data into IML
  .copr/Makefile
  Cargo.lock
  Cargo.toml
  docker/docker-compose.yml
  docker/iml-network.dockerfile
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/daemon_plugins/mod.rs
  iml-agent/src/daemon_plugins/network.rs
  iml-agent/src/network_interface_stats.rs
  iml-agent/src/network_interfaces.rs
  iml-manager.target
  iml-network.service
  iml-services/iml-network/Cargo.toml
  iml-services/iml-network/src/main.rs
  migrations/20201028182332_network_interface.sql
  python-iml-manager.spec
  rust-iml.spec
  sqlx-data.json
  vagrant/scripts/install_iml_docker_local.sh
  vagrant/scripts/install_iml_docker_repouri.sh
  vagrant/scripts/install_iml_local.sh
Labels: enhancement

#2368 Allow different CLI names for Agent CLI
  iml-agent/src/cli.rs
Labels: enhancement

#2347 Return all resources from iml-agent::high-availability::get_crm_mon
  iml-agent/src/high_availability.rs
  iml-agent/src/snapshots/iml_agent__high_availability__tests__read_es.snap
  iml-agent/src/snapshots/iml_agent__high_availability__tests__read_vagrant.snap
  iml-agent/src/snapshots/iml_agent__high_availability__tests__read_vagrant_stopped.snap
  iml-api/src/graphql/mod.rs
  iml-services/iml-corosync/src/lib.rs
  migrations/20201105070221_corosync_resource.sql
  sqlx-data.json
Labels: enhancement

#2365 Remove chroma cli
  .travis.yml
  Pipfile
  Pipfile.lock
  chroma_cli/__init__.py
  chroma_cli/api.py
  chroma_cli/api_resource.py
  chroma_cli/config.py
  chroma_cli/defaults.py
  chroma_cli/exceptions.py
  chroma_cli/handlers.py
  chroma_cli/main.py
  chroma_cli/output.py
  chroma_cli/parser.py
  python-iml-manager.spec
  requirements.txt
  setup.py
  tests/feature/cli/features/environment.py
  tests/feature/cli/features/exploration.feature
  tests/feature/cli/features/filesystem-management.feature
  tests/feature/cli/features/lnet-management.feature
  tests/feature/cli/features/options.feature
  tests/feature/cli/features/output.feature
  tests/feature/cli/features/server-management.feature
  tests/feature/cli/features/steps/background.py
  tests/feature/cli/features/steps/helpers.py
  tests/feature/cli/features/steps/standard_cli.py
  tests/feature/cli/features/target-management.feature
Labels: chore

#2371 Update crypto to support newer openssl
  chroma_core/migrations/0028_expand_client_serial.py
  chroma_core/models/client_certificate.py
  chroma_core/services/crypto.py
  tests/services/test_nginx.py
  tests/unit/chroma_core/helpers/helper.py
Labels: chore

#2369 move some python CI checks to github actions
  .copr/Makefile
  .github/workflows/devel-release.yml
  .github/workflows/iml-docker-ci.yml
  .github/workflows/python-ci.yml
  .github/workflows/rust-ci.yml
  .travis.yml
  Pipfile
  Pipfile.lock
  tests/unit/chroma_core/helpers/helper.py
Labels: chore

#2363 Implement server profile GraphQL queries
  iml-api/src/graphql/mod.rs
  iml-manager-cli/src/profile.rs
  iml-wire-types/src/db.rs
  iml-wire-types/src/lib.rs
  sqlx-data.json
Labels: enhancement

#2372 Update graphql python client
  chroma_core/lib/graphql.py
Labels: enhancement

#2377 Require influx < 2
  python-iml-manager.spec
Labels: bug

#2370 agent: Return cloned resources with index from crm mon output
  iml-agent/src/action_plugins/high_availability/mod.rs
  iml-agent/src/high_availability.rs
  iml-agent/src/snapshots/iml_agent__high_availability__tests__read_es.snap
Labels: bug

#2378 Extract device-scanner client
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/daemon_plugins/device.rs
  iml-agent/src/device_scanner_client.rs
  iml-agent/src/lib.rs
  iml-services/iml-device/Cargo.toml
Labels: enhancement

#2373 Fix Stale Influx Entries
  iml-services/iml-stats/src/main.rs
Labels: bug

#2376 Switch server profiles CLI to GraphQL
  Cargo.lock
  iml-api/src/graphql/mod.rs
  iml-graphql-queries/src/lib.rs
  iml-graphql-queries/src/server_profile.rs
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/display_utils.rs
  iml-manager-cli/src/error.rs
  iml-manager-cli/src/profile.rs
  iml-wire-types/src/lib.rs
  sqlx-data.json
Labels: enhancement

#2178 Add create and destroy resource
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/high_availability/fixtures/create-client-cloned.xml
  iml-agent/src/action_plugins/high_availability/mod.rs
  iml-agent/src/action_plugins/lustre/client.rs
  iml-agent/src/high_availability.rs
  iml-wire-types/src/lib.rs
Labels: enhancement

#2390 Update iml-system-*-tests/Cargo.lock
  iml-system-docker-tests/Cargo.lock
  iml-system-rpm-tests/Cargo.lock
Labels: chore

#2391 Add ha_resource_move action
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/high_availability/mod.rs
Labels: enhancement

#2362 Ingest lnet data from storage servers into management db
  Cargo.lock
  chroma_core/lib/influx.py
  chroma_core/models/host.py
  iml-agent/Cargo.toml
  iml-agent/src/agent_error.rs
  iml-agent/src/daemon_plugins/action_runner.rs
  iml-agent/src/daemon_plugins/network.rs
  iml-agent/src/network_interfaces.rs
  iml-agent/src/snapshots/iml_agent__network_interfaces__tests__parse_lnetctl_net_show_output.snap
  iml-services/iml-network/Cargo.toml
  iml-services/iml-network/src/main.rs
  iml-services/iml-network/src/snapshots/iml_network__tests__parse_lnetctl_data.snap
  iml-wire-types/src/lib.rs
  migrations/20201102184120_lnet.sql
  sqlx-data.json
  tests/unit/chroma_api/chroma_api_test_case.py
  tests/unit/chroma_api/test_client_management.py
  tests/unit/chroma_api/test_misc.py
  tests/unit/chroma_api/test_power_control.py
  tests/unit/lib/iml_unit_test_case.py
Labels: enhancement

#2400 Do not try to parse empty lnetctl result
  iml-agent/src/network_interfaces.rs
  iml-services/iml-network/src/main.rs
  iml-services/iml-network/src/snapshots/iml_network__tests__parse_empty_lnetctl_data.snap
  iml-services/iml-network/src/snapshots/iml_network__tests__parse_lnetctl_data.snap
Labels: bug

#2387 Search for config in different places
  iml-manager-cli/src/main.rs
Labels: enhancement

#2364 Use direct lctl device calls for snapshots
  iml-agent/src/action_plugins/lustre/snapshot.rs
  iml-agent/src/action_plugins/lustre/snapshot/parse.rs
  iml-agent/src/action_plugins/lustre/snapshots/iml_agent__action_plugins__lustre__snapshot__tests__parse_device_list.snap
  iml-agent/src/daemon_plugins/ostpool.rs
  iml-agent/src/daemon_plugins/snapshot.rs
  iml-agent/src/lustre.rs
  iml-gui/crate/src/page/snapshot/list.rs
  iml-manager-cli/src/display_utils.rs
  iml-services/iml-snapshot/src/main.rs
  iml-wire-types/src/snapshot.rs
  migrations/20201106182518_snapshot_mounted.sql
  sqlx-data.json
Labels: enhancement
