Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2020-01, with the labels that each got.

#1432 Use browser notification API to show alerts
  iml-gui/crate/Cargo.lock
  iml-gui/crate/Cargo.toml
  iml-gui/crate/src/components/activity_indicator.rs
  iml-gui/crate/src/components/font_awesome.rs
  iml-gui/crate/src/components/tooltip.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/notification.rs
  iml-gui/crate/src/page/partial/header.rs
  iml-gui/static/notification.sw.js
Labels: enhancement

#1430 DDN test task Starostin (Issue 1421: Implement --prompt / --force flags for adding new servers)
  Cargo.lock
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/server.rs
Labels: enhancement

#1417 Trim down docker image size
  .dockerignore
  base.dockerfile.dockerignore
  docker/base.dockerfile
  docker/iml-wasm-components.dockerfile
  docker/rust-base.dockerfile
  docker/setup.dockerfile
Labels: tech debt

#1440 Use immutable data structures for warp-drive `Cache`
  Cargo.lock
  iml-gui/crate/Cargo.lock
  iml-gui/crate/Cargo.toml
  iml-gui/crate/src/components/activity_indicator.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/notification.rs
  iml-postgres/Cargo.toml
  iml-warp-drive/Cargo.toml
  iml-warp-drive/src/cache.rs
  iml-warp-drive/src/locks.rs
  iml-warp-drive/src/main.rs
  iml-warp-drive/src/users.rs
  iml-wasm-components/Cargo.lock
  iml-wire-types/Cargo.toml
  iml-wire-types/wire-types.rs
Labels: enhancement

#1438 Fix a few clippy warnings
  iml-agent/src/action_plugins/action_plugin.rs
  iml-fs/src/lib.rs
  iml-util/util.rs
  number-formatter/src/lib.rs
Labels: chore

#1434 Add iml-orm crate
  Cargo.lock
  Cargo.toml
  iml-manager-env/src/lib.rs
  iml-orm/Cargo.toml
  iml-orm/README.md
  iml-orm/diesel.toml
  iml-orm/migrations/.gitkeep
  iml-orm/src/lib.rs
  iml-orm/src/models.rs
  iml-orm/src/schema.rs
  iml-postgres/src/lib.rs
Labels: enhancement

#1386 Seperate out version comparison
  Cargo.lock
  Cargo.toml
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/check_kernel.rs
  version-utils/Cargo.toml
  version-utils/src/lib.rs
Labels: enhancement

#1444 Commit Cargo.lock
  Cargo.lock
Labels: chore

#1443 Remove items from paging Model
  .github/workflows/iml-gui.yml
  iml-gui/configs/tailwind.config.js
  iml-gui/crate/.editorconfig
  iml-gui/crate/.gitignore
  iml-gui/crate/Cargo.lock
  iml-gui/crate/Cargo.toml
  iml-gui/crate/LICENSE
  iml-gui/crate/src/components/dropdown.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/components/paging.rs
  iml-gui/crate/src/components/tree.rs
  iml-gui/crate/src/generated/css_classes.rs
Labels: enhancement

#1447 Add Table component
  Cargo.lock
  iml-gui/crate/Makefile.toml
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/components/table.rs
Labels: enhancement

#1364 Ostpool: Add agent daemon and queue processing service
  .copr/Makefile
  Cargo.lock
  Cargo.toml
  chroma_api/filesystem.py
  chroma_core/services/job_scheduler/job_scheduler.py
  chroma_core/services/job_scheduler/job_scheduler_client.py
  chroma_help/help.py
  docker/docker-compose.override.yml
  docker/docker-compose.yml
  docker/iml-ostpool.dockerfile
  iml-agent/src/action_plugins/ostpool.rs
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/daemon_plugins/mod.rs
  iml-agent/src/daemon_plugins/ostpool.rs
  iml-manager-cli/src/ostpool.rs
  iml-manager.target
  iml-ostpool.service
  iml-services/iml-ostpool/Cargo.toml
  iml-services/iml-ostpool/src/db.rs
  iml-services/iml-ostpool/src/error.rs
  iml-services/iml-ostpool/src/lib.rs
  iml-services/iml-ostpool/src/main.rs
  iml-wire-types/wire-types.rs
  python-iml-manager.spec
  rust-iml.spec
Labels: enhancement

#1451 Move Vagrantfiles repo into IML repo
  .gitignore
  base.dockerfile.dockerignore
  vagrant/.gitignore
  vagrant/README.md
  vagrant/Vagrantfile
  vagrant/scripts/bootstrap_iscsi.sh
  vagrant/scripts/configure_lustre_network.sh
  vagrant/scripts/create_ldiskfs_fs_osts.sh
  vagrant/scripts/deploy_hosts.sh
  vagrant/scripts/disable_selinux.sh
  vagrant/scripts/install_iml.sh
  vagrant/scripts/install_iml_local.sh
  vagrant/scripts/install_iml_tar.sh
  vagrant/scripts/install_ldiskfs_no_iml.sh
  vagrant/scripts/install_zfs_no_iml.sh
  vagrant/scripts/key_config.sh
  vagrant/scripts/load-diagnostics-db.sh
  vagrant/scripts/use_vault.sh
  vagrant/scripts/zfs_params.sh
Labels: chore

#1452 Use a separate order to remove a record
  iml-gui/crate/src/lib.rs
Labels: bug

#1450 A few small fixups
  Cargo.lock
  iml-agent/src/daemon_plugins/ostpool.rs
  iml-manager-cli/src/ostpool.rs
Labels: tech debt

#1456 Remove extra save from RemoveOstPoolJob and AddOstPoolJob
  chroma_core/models/filesystem.py
Labels: bug

#1455 Implement full local provisioning
  iml-manager-cli/src/server.rs
  vagrant/Vagrantfile
  vagrant/scripts/install_iml_local.sh
  vagrant/scripts/install_iml_local_agent.sh
Labels: tech debt

#1459 Implement spec and CI for iml-docker
  .copr/Makefile
  .github/actions/copr/action.yml
  .github/workflows/devel-release.yml
  .github/workflows/iml-docker-ci.yml
  .github/workflows/prod-release.yml
  iml-docker.spec
Labels: enhancement

#1437 Create new Remove server CLI command
  iml-manager-cli/src/main.rs
  iml-manager-cli/src/server.rs
Labels: enhancement

#1474 Make memory and cpu configurable in Vagrant
  vagrant/Vagrantfile
Labels: enhancement

#1416 Implement ReplaceNidsStep
  chroma_core/models/host.py
  tests/unit/chroma_core/helpers/mock_agent_rpc.py
  tests/unit/services/job_scheduler/host/test_host.py
Labels: enhancement

#1475 Bump deps
  Cargo.lock
  Cargo.toml
  iml-agent/Cargo.toml
  iml-manager-cli/Cargo.toml
  iml-manager-client/Cargo.toml
  iml-request-retry/Cargo.toml
  iml-services/iml-ostpool/Cargo.toml
Labels: chore

#1466 Implement LNet Status Indicator component
  iml-gui/crate/src/components/lnet_status.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/lib.rs
Labels: enhancement

#1454 Agent Postman
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/action_plugins/postoffice.rs
  iml-agent/src/cli.rs
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/daemon_plugins/mod.rs
  iml-agent/src/daemon_plugins/postoffice.rs
  iml-agent/systemd-units/rust-iml-agent.service
  iml-agent/systemd-units/settings.conf
  iml-agent/systemd-units/tmpfiles.conf
  rust-iml.spec
Labels: enhancement

#1481 Fix rpm build
  .copr/Makefile
  rust-iml.spec
Labels: bug

#1488 check_stonith: Fix untrimmed nodename
  iml-agent/src/action_plugins/check_stonith.rs
  iml-agent/src/action_plugins/fixtures/check_stonith_test_es.xml
  iml-agent/src/action_plugins/fixtures/check_stonith_test_multihost_dynamic.xml
  iml-agent/src/action_plugins/fixtures/check_stonith_test_multihost_static.xml
Labels: bug

#1484 Fix: install-iml-local provisioner agent packages are overwritten
  Makefile
  vagrant/scripts/install_iml_local.sh
  vagrant/scripts/install_iml_local_agent.sh
Labels: bug

#1288 check_ha use ComponentState
  iml-agent/src/action_plugins/check_ha.rs
  iml-agent/src/action_plugins/snapshots/check_ha_test_mixed_mode.xml
  iml-agent/src/cli.rs
  iml-wire-types/wire-types.rs
Labels: enhancement

#1492 Bump warp to 0.2
  Cargo.lock
  iml-agent-comms/Cargo.toml
  iml-mailbox/Cargo.toml
  iml-request-retry/Cargo.toml
  iml-services/iml-action-runner/Cargo.toml
  iml-warp-drive/Cargo.toml
Labels: chore

#1496 Replace parking_lot::Mutex in postoffice
  iml-agent/src/daemon_plugins/postoffice.rs
Labels: enhancement

#1499 Utilize webpack proxy for development
  iml-gui/configs/webpack.config.js
  iml-gui/crate/src/lib.rs
  iml-gui/package.json
  iml-gui/yarn.lock
Labels: chore

#1491 Disable buildtools repo when we are done using it.
  .copr/Makefile
Labels: bug

#1503 Fixup alert type endpoint
  chroma_api/alert.py
Labels: bug

#1507 Attempt to fix insecure request warnings in Jenkins.
  tests/framework/test_reporting/aggregate_test_results.py
  tests/utils/http_requests.py
Labels: bug

#1510 Account for missing FS in iml-ostpool service
  iml-services/iml-ostpool/src/main.rs
Labels: bug

#1505 GH-1504 Create post office manager plugin
  .copr/Makefile
  Cargo.lock
  Cargo.toml
  docker/docker-compose.override.yml
  docker/docker-compose.yml
  docker/iml-postoffice.dockerfile
  iml-manager.target
  iml-postoffice.service
  iml-services/iml-postoffice/Cargo.toml
  iml-services/iml-postoffice/src/main.rs
  python-iml-manager.spec
  rust-iml.spec
  vagrant/scripts/install_iml_local.sh
Labels: bug

#1401 Integrate grafana into docker stack
  chroma-manager.conf.template
  chroma_core/lib/service_config.py
  docker/docker-compose.yml
  docker/grafana.dockerfile
  docker/grafana/setup-grafana
  docker/grafana/setup-grafana.sh
  docker/setup-nginx
  grafana/datasources/influxdb-iml-datasource.yml
  python-iml-manager.spec
  settings.py
Labels: enhancement

#1516 fixup formatting
  chroma_core/models/host.py
Labels: bug

#1433 Create `lamigo` service unit
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/lamigo.rs
  iml-agent/src/action_plugins/lustre.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/action_plugins/snapshots/lamigo_tests__works.snap
  iml-agent/src/agent_error.rs
  iml-agent/src/cli.rs
  iml-agent/systemd-units/settings.conf
Labels: enhancement

#1519 Add media breakpoint tracking
  iml-gui/crate/src/breakpoints.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/partial/header.rs
Labels: bug, enhancement

#1520 Extract logo
  iml-gui/crate/src/components/logo.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/page/partial/header.rs
Labels: enhancement

#1405 Integrate Influxdb into docker
  chroma-manager.conf.template
  chroma_core/lib/service_config.py
  chroma_core/lib/stratagem.py
  chroma_core/management/commands/print-settings.py
  docker/docker-compose.yml
  docker/influxdb.dockerfile
  docker/influxdb/setup-influxdb.sh
  docker/setup-nginx
  settings.py
Labels: enhancement

#1524 Use target host nids instead of mgs nids
  chroma_core/models/host.py
  chroma_core/models/target.py
  tests/unit/services/job_scheduler/host/test_host.py
Labels: failing tests

#1527 Archive RPM build results
  .github/workflows/rust-ci.yml
  .github/workflows/wasm-ci.yml
  README.md
Labels: chore

#1531 Allow Client vm's to be configured for docker networking
  vagrant/Vagrantfile
Labels: enhancement

#1532 Use current user instead of login user
  Vagrantfile
Labels: bug

#1525 Implement Auth
  iml-gui/crate/Cargo.lock
  iml-gui/crate/Cargo.toml
  iml-gui/crate/src/auth.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/components/restrict.rs
  iml-gui/crate/src/components/tree.rs
  iml-gui/crate/src/extensions.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/notification.rs
  iml-gui/crate/src/page/login.rs
  iml-gui/crate/src/page/mod.rs
  iml-gui/crate/src/page/partial/header.rs
  iml-gui/crate/src/page/user_detail.rs
  iml-gui/crate/src/route.rs
  iml-gui/crate/src/sleep.rs
  iml-gui/package.json
  iml-gui/yarn.lock
  iml-wire-types/wire-types.rs
Labels: enhancement

#1533 Create a base systemd dockerfile
  docker/systemd-base.dockerfile
Labels: enhancement

#1542 Keep sosreports in archive format
  tests/integration/utils/chroma_log_collector.py
Labels: failing tests

#1546 Rust 1.41 fixes
  iml-agent/src/action_plugins/check_ha.rs
  iml-agent/src/action_plugins/kernel_module.rs
  iml-agent/src/action_plugins/ntp/action_configure.rs
  iml-agent/src/cli.rs
  iml-agent/src/http_comms/crypto_client.rs
  iml-agent/src/http_comms/mailbox_client.rs
  iml-agent/src/poller.rs
  iml-agent/src/reader.rs
  iml-agent/src/rpm.rs
  iml-agent/src/systemd.rs
  iml-fs/src/lib.rs
  iml-gui/crate/src/auth.rs
  iml-gui/crate/src/components/activity_indicator.rs
  iml-gui/crate/src/components/paging.rs
  iml-gui/crate/src/components/tree.rs
  iml-gui/crate/src/extensions.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/login.rs
  iml-gui/crate/src/page/server.rs
  iml-gui/crate/src/watch_state.rs
  iml-manager-cli/src/filesystem.rs
  iml-manager-cli/src/ostpool.rs
  iml-manager-cli/src/server.rs
  iml-services/iml-action-runner/src/local_actions.rs
  iml-services/iml-action-runner/src/receiver.rs
  iml-services/iml-service-queue/src/service_queue.rs
  iml-warp-drive/src/db_record.rs
  iml-warp-drive/src/error.rs
  iml-warp-drive/src/listen.rs
  iml-wire-types/wire-types.rs
  liblustreapi/src/error.rs
  tests/integration/utils/chroma_log_collector.py
Labels: chore

#1547 Switch to new Cargo.lock format
  Cargo.lock
Labels: chore
