Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2020-07, with the labels that each got.

#2028 Ensure activation of LVs during creation
  vagrant/scripts/create_ldiskfs_lvm_fs.sh
Labels: bug

#2029 Update retry_future to take ownership of policy
  iml-manager-client/src/lib.rs
  iml-request-retry/Cargo.toml
  iml-request-retry/examples/demo-server-client.rs
  iml-request-retry/src/lib.rs
  iml-sfa/src/main.rs
Labels: enhancement

#2038 Fix fs detail overflow
  iml-gui/crate/src/page/filesystem.rs
Labels: bug

#2040 Improve and unify server operations in CLI
  iml-manager-cli/src/server.rs
  iml-system-test-utils/src/vagrant.rs
  vagrant/scripts/deploy_hosts.sh
Labels: enhancement, needs-docs

#2046 Allow for influx retention time to be tunable
  docker/docker-compose.yml
  settings.py
Labels: enhancement, needs-docs

#2049 Do not install postgres-devel
  .copr/Makefile
  docker/power-control.dockerfile
  vagrant/Vagrantfile
Labels: bug

#2037 Fix agent ostpool resend
  iml-agent/src/daemon_plugins/ostpool.rs
Labels: bug

#2053 Fix "server add" invocation in tests
  iml-system-test-utils/src/iml.rs
Labels: bug, failing tests

#2045 Only unmount clients that were on the current host
  .github/workflows/rust-ci.yml
  Cargo.lock
  chroma_api/host.py
  chroma_core/lib/cache.py
  chroma_core/migrations/0021_many_mountpoint.py
  chroma_core/models/client_mount.py
  chroma_core/models/copytool.py
  chroma_core/models/stratagem.py
  chroma_core/services/job_scheduler/job_scheduler.py
  chroma_help/help.py
  iml-orm/src/models.rs
  iml-orm/src/schema.rs
  iml-services/iml-device/Cargo.toml
  iml-services/iml-device/README.md
  iml-services/iml-device/sqlx-data.json
  iml-services/iml-device/src/lib.rs
  iml-services/iml-device/src/main.rs
  iml-services/iml-device/tests/integration_tests.rs
  iml-services/iml-device/tests/snapshots/integration_tests__insert-2.snap
  iml-services/iml-device/tests/snapshots/integration_tests__insert-3.snap
  iml-services/iml-device/tests/snapshots/integration_tests__insert.snap
  iml-wire-types/src/lib.rs
  tests/unit/chroma_api/test_client_management.py
  vagrant/scripts/install_iml.sh
  vagrant/scripts/install_iml_local.sh
  vagrant/scripts/install_iml_repouri.sh
Labels: bug

#2058 bump deps to latest
  Cargo.lock
  iml-rabbit/Cargo.toml
Labels: chore

#2023 Snapshot graph
  Cargo.lock
  iml-system-docker-tests/Cargo.lock
  iml-system-docker-tests/Cargo.toml
  iml-system-docker-tests/src/lib.rs
  iml-system-docker-tests/tests/ldiskfs_test.rs
  iml-system-docker-tests/tests/stratagem_test.rs
  iml-system-docker-tests/tests/zfs_test.rs
  iml-system-rpm-tests/Cargo.lock
  iml-system-rpm-tests/src/lib.rs
  iml-system-rpm-tests/tests/ldiskfs_test.rs
  iml-system-rpm-tests/tests/stratagem_test.rs
  iml-system-rpm-tests/tests/zfs_test.rs
  iml-system-test-utils/Cargo.lock
  iml-system-test-utils/Cargo.toml
  iml-system-test-utils/src/docker.rs
  iml-system-test-utils/src/iml.rs
  iml-system-test-utils/src/lib.rs
  iml-system-test-utils/src/snapshots.rs
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_ldiskfs_test_path_from_graph.snap
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_stratagem_test_path_from_graph.snap
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_zfs_test_path_from_graph.snap
  iml-system-test-utils/src/ssh.rs
  iml-system-test-utils/src/vagrant.rs
  vagrant/scripts/wait_for_ntp.sh
Labels: integration-tests

#2064 Fix OST pool grow
  chroma_core/services/job_scheduler/job_scheduler.py
Labels: bug

#2050 Prepare iml install on docker
  iml-system-docker-tests/Cargo.lock
  iml-system-docker-tests/src/lib.rs
  iml-system-docker-tests/tests/ldiskfs_test.rs
  iml-system-docker-tests/tests/stratagem_test.rs
  iml-system-docker-tests/tests/zfs_test.rs
  iml-system-rpm-tests/src/lib.rs
  iml-system-rpm-tests/tests/ldiskfs_test.rs
  iml-system-rpm-tests/tests/stratagem_test.rs
  iml-system-rpm-tests/tests/zfs_test.rs
  iml-system-test-utils/src/docker.rs
  iml-system-test-utils/src/iml.rs
  iml-system-test-utils/src/lib.rs
  iml-system-test-utils/src/snapshots.rs
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_ldiskfs_test_path_from_graph.snap
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_stratagem_test_path_from_graph.snap
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_zfs_test_path_from_graph.snap
  iml-system-test-utils/src/ssh.rs
  iml-system-test-utils/src/vagrant.rs
  vagrant/README.md
  vagrant/Vagrantfile
  vagrant/scripts/install_iml_docker_local.sh
  vagrant/scripts/install_iml_docker_repouri.sh
Labels: integration-tests

#2051 Drop retention policy before creating it
  chroma_core/lib/service_config.py
  docker/influxdb/setup-influxdb.sh
Labels: bug

#2066 Add more information when encountering 'Error parsing json'
  chroma_core/lib/job.py
Labels: integration-tests

#2069 Update sos reports
  vagrant/scripts/create_iml_diagnostics.sh
Labels: integration-tests

#2078 vagrant: Add client mount provisioner
  vagrant/README.md
  vagrant/Vagrantfile
  vagrant/scripts/mount_lustre_client.sh
Labels: enhancement

#2074 Update iml-manager-env for docker and postgres
  iml-manager-env/src/lib.rs
Labels: bug, enhancement

#2054 Use `Identity::from_pem`
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/env.rs
  iml-agent/src/http_comms/crypto_client.rs
  iml-agent/src/http_comms/mailbox_client.rs
  iml-agent/src/main.rs
Labels: enhancement

#2080 Remove queue purge during startup
  iml-services/iml-service-queue/src/service_queue.rs
Labels: bug

#2065 Update test debugging
  docker/docker-compose.yml
  iml-system-test-utils/src/lib.rs
  iml-system-test-utils/src/ssh.rs
  vagrant/Vagrantfile
  vagrant/scripts/enable_debug.sh
  vagrant/scripts/wait_for_ntp.sh
Labels: integration-tests

#2082 Specify python version
  docker/grafana.dockerfile
Labels: chore

#2081 Update mem::replace assignments
  iml-gui/crate/Cargo.lock
  iml-gui/crate/src/components/dropdown.rs
  iml-gui/crate/src/watch_state.rs
Labels: chore

#2083 Move snapshot location in agent testing
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/daemon_plugins/snapshots/iml_agent__daemon_plugins__ntp__test__session_with_ntp_configured_by_iml.snap
Labels: chore

#2077 Agent to teardown sessions on signals
  iml-agent/src/main.rs
Labels: enhancement

#2085 Fix client mount in run_stratagem
  chroma_core/services/job_scheduler/job_scheduler.py
Labels: bug

#2073 Switch direct dependencies to rustls
  Cargo.lock
  iml-action-client/Cargo.toml
  iml-agent/Cargo.toml
  iml-agent/src/agent_error.rs
  iml-manager-cli/Cargo.toml
  iml-manager-client/Cargo.toml
  wbem-client/Cargo.toml
Labels: enhancement

#2092 Fix Journal cursor deadlock
  Cargo.lock
  iml-agent/src/daemon_plugins/journal.rs
  iml-services/iml-journal/src/main.rs
  iml-wire-types/src/lib.rs
Labels: bug

#2095 Show command modal when modifying file scan
  chroma_api/job.py
  iml-gui/crate/src/components/stratagem/mod.rs
Labels: bug, enhancement

#2101 Use docker buildx for building
  docker/Makefile
  docker/compose-deps.hcl
Labels: enhancement

#2103 Make docker image tarball a required file
  iml-docker.service
  iml-docker.spec
Labels: bug

#2094 Add alternate client mount provisioners
  vagrant/README.md
  vagrant/Vagrantfile
  vagrant/scripts/mount_lustre_client.sh
Labels: enhancement

#2099 Deduplicate lctl calls in iml-agent
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/lctl.rs
  iml-agent/src/action_plugins/lustre.rs
  iml-agent/src/action_plugins/ostpool.rs
  iml-agent/src/daemon_plugins/ostpool.rs
  iml-agent/src/lustre.rs
Labels: enhancement

#2104 Rename try_mount to mount in iml-agent
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/lustre.rs
  iml-agent/src/cli.rs
Labels: enhancement

#2105 Only destroy matching sessions
  Cargo.lock
  iml-agent-comms/src/messaging.rs
  iml-agent/src/http_comms/agent_client.rs
  iml-agent/src/http_comms/session.rs
  iml-agent/src/poller.rs
  iml-agent/src/reader.rs
  iml-wire-types/src/lib.rs
Labels: bug

#2102 tests: Mount filesystem(s) during detect_fs
  Cargo.lock
  iml-system-docker-tests/src/lib.rs
  iml-system-docker-tests/tests/ldiskfs_test.rs
  iml-system-docker-tests/tests/stratagem_test.rs
  iml-system-docker-tests/tests/zfs_test.rs
  iml-system-rpm-tests/src/lib.rs
  iml-system-rpm-tests/tests/ldiskfs_test.rs
  iml-system-rpm-tests/tests/stratagem_test.rs
  iml-system-rpm-tests/tests/zfs_test.rs
  iml-system-test-utils/Cargo.toml
  iml-system-test-utils/src/lib.rs
  iml-system-test-utils/src/snapshots.rs
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_ldiskfs_test_path_from_graph.snap
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_stratagem_test_path_from_graph.snap
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_zfs_test_path_from_graph.snap
  iml-system-test-utils/src/ssh.rs
  iml-system-test-utils/src/vagrant.rs
  vagrant/README.md
  vagrant/Vagrantfile
Labels: enhancement, integration-tests

#2042 Make listing servers default command
  iml-manager-cli/src/main.rs
  iml-manager-cli/src/server.rs
Labels: enhancement

#2110 Add TAGS to gitignore
  .gitignore
Labels: chore

#2112 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#2106 Implement creating and destroying snapshots
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/lustre.rs
  iml-agent/src/action_plugins/lustre/snapshot.rs
  iml-agent/src/cli.rs
  iml-wire-types/Cargo.toml
  iml-wire-types/src/lib.rs
  iml-wire-types/src/snapshot.rs
Labels: enhancement

#2113 Rename client nodes to non hexadecimal characters
  iml-system-test-utils/src/lib.rs
  vagrant/Vagrantfile
  vagrant/scripts/install_iml_docker_local.sh
  vagrant/scripts/install_iml_docker_repouri.sh
Labels: bug

#2100 EX-1465 - Create and populate ldev.conf file on MGT nodes
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/ldev.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/action_plugins/snapshots/iml_agent__action_plugins__ldev__tests__config_without_ha.snap
  iml-agent/src/action_plugins/snapshots/iml_agent__action_plugins__ldev__tests__create.snap
  iml-agent/src/agent_error.rs
  iml-agent/src/env.rs
  iml-agent/systemd-units/settings.conf
  iml-wire-types/src/lib.rs
Labels: enhancement

#2111 Tests: Add clients to ldiskfs zfs profile list
  iml-system-docker-tests/tests/ldiskfs_test.rs
  iml-system-docker-tests/tests/zfs_test.rs
  iml-system-rpm-tests/tests/ldiskfs_test.rs
  iml-system-rpm-tests/tests/zfs_test.rs
  iml-system-test-utils/src/lib.rs
Labels: bug

#2098 Disable default features of reqwest
  Cargo.lock
  iml-action-client/Cargo.toml
  iml-agent/Cargo.toml
  iml-manager-cli/Cargo.toml
  iml-manager-client/Cargo.toml
  iml-request-retry/Cargo.toml
  iml-services/iml-stats/Cargo.toml
  wbem-client/Cargo.toml
Labels: enhancement

#2109 Implement mounting and unmounting snapshots
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/lustre/snapshot.rs
  iml-agent/src/cli.rs
  iml-wire-types/src/snapshot.rs
Labels: enhancement

#2120 Add all packages to all target
  Makefile
Labels: chore

#2087 Add "make check" to Makefile
  Makefile
Labels: enhancement

#2118 Split FilesystemDetect state into 3
  iml-system-test-utils/src/snapshots.rs
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_ldiskfs_test_path_from_graph.snap
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_stratagem_test_path_from_graph.snap
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_zfs_test_path_from_graph.snap
Labels: bug, integration-tests

#2116 Bump sqlx to latest
  Cargo.lock
  iml-services/iml-journal/src/main.rs
Labels: chore
