Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2020-06, with the labels that each got.

#1934 Use Single-step server deployment
  chroma_api/host.py
  chroma_api/urls.py
  chroma_core/lib/cache.py
  chroma_core/migrations/0019_auto_20200529_2026.py
  chroma_core/models/corosync.py
  chroma_core/models/host.py
  chroma_core/models/host_jobs/test_host_contact.py
  chroma_core/services/job_scheduler/job_scheduler.py
  chroma_core/services/job_scheduler/job_scheduler_client.py
  chroma_core/services/lustre_audit/update_scan.py
  iml-gui/crate/src/test_utils/fixtures.rs
  iml-manager-cli/src/server.rs
  iml-orm/src/models.rs
  iml-orm/src/schema.rs
  iml-wire-types/src/db.rs
  iml-wire-types/src/lib.rs
  tests/unit/chroma_api/test_host.py
  tests/unit/chroma_core/helpers/mock_agent_rpc.py
  tests/unit/remote_operations.py
  tests/unit/services/job_scheduler/host/test_host_contact.py
Labels: enhancement

#1938 Bump iml-docker to 0.3.0
  iml-docker.spec
Labels: chore

#1936 influx/grafana: Fix data display in charts
  chroma_core/lib/service_config.py
  docker/influxdb/setup-influxdb.sh
  grafana/dashboards/iml-metrics.json
Labels: bug

#1931 Remove fk relation between lustreclientmount and fs
  chroma_api/host.py
  chroma_core/lib/cache.py
  chroma_core/migrations/0020_clientmounts_remove_fk.py
  chroma_core/models/client_mount.py
  chroma_core/models/host.py
  chroma_core/models/stratagem.py
  chroma_core/services/job_scheduler/job_scheduler.py
  chroma_core/services/job_scheduler/job_scheduler_client.py
  chroma_core/services/lustre_audit/update_scan.py
  iml-orm/src/models.rs
  iml-orm/src/schema.rs
  tests/unit/chroma_api/test_client_management.py
  tests/unit/chroma_core/models/test_advertised_jobs.py
Labels: enhancement

#1940 Allow vagrants clients to have thier lnet provisioned
  vagrant/Vagrantfile
  vagrant/scripts/configure_lustre_network.sh
Labels: enhancement

#1941 Properly handle SFA object deletions
  Cargo.lock
  iml-orm/src/lib.rs
  iml-orm/src/sfa/disk_drive.rs
  iml-orm/src/sfa/enclosure.rs
  iml-orm/src/sfa/job.rs
  iml-orm/src/sfa/power_supply.rs
  iml-sfa/src/main.rs
Labels: bug

#1942 Add SFAController model
  chroma_core/migrations/0017_sfaenclosure_sfastoragesystem.py
  chroma_core/migrations/0019_auto_20200529_2026.py
  chroma_core/models/sfa.py
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/test_utils/fixtures.rs
  iml-orm/src/schema.rs
  iml-orm/src/sfa/controller.rs
  iml-orm/src/sfa/mod.rs
  iml-orm/src/sfa/wbem_interop.rs
  iml-sfa/src/main.rs
  iml-warp-drive/src/cache.rs
  iml-warp-drive/src/db_record.rs
  iml-wire-types/src/db.rs
  iml-wire-types/src/warp_drive.rs
Labels: enhancement

#1947 Increase max body size for Rust agent
  chroma-manager.conf.template
Labels: enhancement

#1943 Fix some clippy warnings
  iml-action-client/src/lib.rs
  iml-agent/src/action_plugins/stratagem/action_purge.rs
  iml-agent/src/cli.rs
  iml-agent/src/daemon_plugins/stats.rs
  iml-manager-cli/src/display_utils.rs
  iml-manager-cli/src/server.rs
  iml-orm/src/hosts.rs
  iml-system-test-utils/src/iml.rs
  iml-system-test-utils/src/vagrant.rs
  iml-tracing/src/lib.rs
Labels: chore

#1958 Fixup filesystem parameter in LustreClientMount
  chroma_core/models/stratagem.py
Labels: bug

#1962 Grafana Fixup
  grafana/dashboards/iml-metrics.json
Labels: bug

#1959 Update iml-request-retry to pass iteration index
  iml-manager-client/src/lib.rs
  iml-request-retry/examples/demo-server-client.rs
  iml-request-retry/src/lib.rs
Labels: enhancement

#1965 Update docker online-help version from 5.1 to 6.1
  docker/nginx.dockerfile
Labels: docs

#1964 Update DDN logo variant
  iml-gui/crate/Cargo.lock
  iml-gui/crate/src/components/logo.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/page/login.rs
  iml-gui/crate/src/page/partial/header.rs
Labels: enhancement

#1966 Fix Bandwidth per server display
  grafana/dashboards/iml-metrics.json
Labels: bug

#1967 Update branding matrix
  iml-gui/crate/src/page/login.rs
  iml-gui/crate/src/page/partial/header.rs
  iml-wire-types/src/lib.rs
Labels: enhancement

#1960 Retry SFA Endpoint
  Cargo.lock
  iml-sfa/Cargo.toml
  iml-sfa/src/main.rs
Labels: enhancement

#1963 Update footer and change "support" to "help"
  chroma_core/management/commands/print-settings.py
  docker/docker-compose.yml
  iml-api/src/main.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/login.rs
  iml-gui/crate/src/page/partial/footer.rs
  iml-gui/crate/src/page/partial/header.rs
  iml-gui/crate/src/status_section.rs
  iml-manager-env/src/lib.rs
  iml-wire-types/src/lib.rs
  settings.py
Labels: enhancement

#1968 Fix stale EPEL metadata
  docker/power-control.dockerfile
  docker/python-service-base.dockerfile
  docker/rust-base.dockerfile
  iml-system-docker-tests/tests/stratagem_test.rs
  tests/framework/services/runner.sh.in
  vagrant/Vagrantfile
Labels: chore

#1970 Fixup IML 6.1 repo path
  vagrant/Vagrantfile
Labels: bug

#1973 Add missing sfa table
  chroma_core/migrations/0018_sfa_json_notify.py
Labels: bug

#1974 Fixup controller monitoring
  iml-orm/src/sfa/controller.rs
  iml-sfa/src/main.rs
Labels: bug

#1976 grafana: Fix usage of "filesystem" where it should be "fs"
  grafana/dashboards/iml-metrics.json
Labels: bug

#1978 Use the filesystem from the object cache when unmounting / mounting filesystems.
  chroma_core/models/client_mount.py
Labels: bug

#1977 Add the configure_ntp provisioner to client nodes
  vagrant/Vagrantfile
Labels: enhancement

#1980 Allow for empty EnumerateInstances
  wbem-client/fixtures/empty.xml
  wbem-client/src/cim_xml.rs
  wbem-client/src/snapshots/wbem_client__cim_xml__resp__tests__empty.snap
Labels: bug

#1979 Fix policy index in sfa
  iml-sfa/src/main.rs
Labels: bug

#1982 Update footer branding
  iml-gui/crate/src/page/partial/footer.rs
Labels: enhancement

#1981 Fix mount jobs such that they use the correct mount point
  chroma_core/models/client_mount.py
Labels: bug

#1986 Update influxdb healthcheck
  docker/docker-compose.yml
Labels: bug

#1985 Make chart icons blue in tree view
  iml-gui/crate/src/components/tree.rs
Labels: enhancement

#1987 Add wait-for-settings check
  docker/docker-compose.yml
  docker/influxdb.dockerfile
  docker/wait-for-settings.sh
Labels: bug

#1990 Update rabbit healthcheck
  docker/Makefile
  docker/docker-compose.yml
  docker/rabbitmq.dockerfile
Labels: enhancement

#1995 Fix branch of _test_yum_rpm_sanity that returns a tuple of bool
  chroma_core/models/host_jobs/test_host_contact.py
Labels: bug

#1996 remove SRCMAP_PATH
  chroma_core/management/commands/print-settings.py
Labels: chore

#1997 Create a command to update docker services
  .copr/Makefile
  docker/update-embedded.sh
  iml-docker.spec
Labels: enhancement

#1989 Fix file descriptor leak in the postoffice plugin
  iml-agent/src/daemon_plugins/postoffice.rs
Labels: bug

#1994 Create an iml-config cli tool
  .copr/Makefile
  Cargo.lock
  chroma_core/lib/service_config.py
  chroma_core/management/commands/print-settings.py
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/config-main.rs
  iml-manager-cli/src/error.rs
  iml-manager-cli/src/lib.rs
  iml-manager-cli/src/nginx.rs
  iml-manager-cli/src/snapshots/iml_manager_cli__nginx__tests__replace_template_variables.snap
  iml-sfa.service
  nginx/nginx-dropin-iml.conf
  python-iml-manager.spec
  rust-iml.spec
  tests/framework/services/runner.sh.in
  vagrant/scripts/install_iml_local.sh
Labels: enhancement

#2002 Remove blocking debug in postoffice
  iml-agent/src/daemon_plugins/postoffice.rs
Labels: bug

#2001 Add in_flight handle to active sessions
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/README.md
  iml-agent/src/http_comms/session.rs
  iml-agent/src/poller.rs
  iml-agent/src/reader.rs
Labels: bug

#2004 vagrant: Rename client lustre network target
  vagrant/README.md
  vagrant/Vagrantfile
Labels: chore

#1972 Update lapin to latest
  Cargo.lock
  iml-agent-comms/src/main.rs
  iml-agent-comms/src/messaging.rs
  iml-api/Cargo.toml
  iml-api/src/action.rs
  iml-api/src/error.rs
  iml-api/src/main.rs
  iml-job-scheduler-rpc/src/lib.rs
  iml-rabbit/Cargo.toml
  iml-rabbit/src/lib.rs
  iml-services/iml-action-runner/src/main.rs
  iml-services/iml-action-runner/src/receiver.rs
  iml-services/iml-action-runner/src/sender.rs
  iml-services/iml-action-runner/tests/action_runner_tests.rs
  iml-services/iml-device/src/error.rs
  iml-services/iml-device/src/main.rs
  iml-services/iml-ntp/src/main.rs
  iml-services/iml-ostpool/Cargo.toml
  iml-services/iml-ostpool/src/main.rs
  iml-services/iml-postoffice/src/main.rs
  iml-services/iml-service-queue/Cargo.toml
  iml-services/iml-service-queue/src/service_queue.rs
  iml-services/iml-stats/Cargo.toml
  iml-services/iml-stats/src/error.rs
  iml-services/iml-stats/src/main.rs
  iml-warp-drive/src/locks.rs
  iml-warp-drive/src/main.rs
Labels: chore

#2008 Do not set environment variables in tests
  iml-agent/src/action_plugins/lamigo.rs
  iml-agent/src/action_plugins/lpurge.rs
  iml-agent/src/action_plugins/snapshots/iml_agent__action_plugins__lpurge__lpurge_conf_tests__works.snap
  iml-agent/src/daemon_plugins/postoffice.rs
  iml-agent/src/env.rs
Labels: failing tests

#1988 Make favicons dynamic
  chroma-manager.conf.template
  docker/docker-compose.yml
  iml-docker.spec
  iml-manager-cli/src/snapshots/iml_manager_cli__nginx__tests__replace_template_variables.snap
Labels: enhancement

#2018 IML cannot detect filesystem when a client is mounted on a storage server
  chroma_core/models/client_mount.py
Labels: bug

#2014 Bring 6.1 0016_task migration in line with master
  chroma_core/migrations/0016_task.py
  chroma_core/models/task.py
  iml-orm/src/models.rs
  iml-orm/src/schema.rs
Labels: bug

#2006 Fix user disconnects
  Cargo.lock
  iml-warp-drive/README.md
  iml-warp-drive/src/users.rs
Labels: bug

#2021 Add copyright to footer for exascaler.
  iml-gui/crate/src/page/partial/footer.rs
Labels: bug

#2022 Use systemd_post instead of systemctl preset
  rust-iml.spec
Labels: bug

#1911 Monitor client mounts in iml-device
  Cargo.lock
  chroma_core/services/lustre_audit/update_scan.py
  device-scanner/device-scanner-daemon/src/state.rs
  iml-services/iml-device/Cargo.toml
  iml-services/iml-device/src/main.rs
Labels: enhancement

#2025 Use sqlx for iml-devices
  .copr/Makefile
  .dockerignore
  .github/workflows/rust-ci.yml
  .gitignore
  Cargo.lock
  Makefile
  iml-orm/src/models.rs
  iml-services/iml-device/Cargo.toml
  iml-services/iml-device/README.md
  iml-services/iml-device/sqlx-data.json
  iml-services/iml-device/src/error.rs
  iml-services/iml-device/src/linux_plugin_transforms.rs
  iml-services/iml-device/src/main.rs
  settings.py
  vagrant/scripts/install_iml_local.sh
  vagrant/scripts/install_iml_local_agent.sh
Labels: enhancement
