Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2020-04, with the labels that each got.

#1758 Sort OSTs in OST pools display
  iml-manager-cli/src/ostpool.rs
Labels: bug

#1754 Fix influx queries for FS stats
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/page/filesystems.rs
Labels: bug

#1751 Vagrant: Add ldiskfs-lvm-fs provisioners
  vagrant/README.md
  vagrant/Vagrantfile
  vagrant/scripts/create_ldiskfs_fs_osts.sh
  vagrant/scripts/create_ldiskfs_lvm_fs.sh
  vagrant/scripts/create_ldiskfs_lvm_mds_ha_setup.sh
  vagrant/scripts/create_ldiskfs_lvm_oss_ha_setup.sh
  vagrant/scripts/install_ldiskfs_no_iml.sh
Labels: enhancement

#1753 Add repouri provisioner
  iml-system-tests/Cargo.lock
  iml-system-tests/tests/vagrant.rs
  vagrant/README.md
  vagrant/Vagrantfile
  vagrant/scripts/install_iml_repouri.sh
Labels: enhancement

#1763 bump version
  .github/workflows/prod-release.yml
  .travis.yml
  Cargo.lock
  docker/Makefile
  docker/corosync.dockerfile
  docker/docker-compose.yml
  docker/gunicorn.dockerfile
  docker/http-agent.dockerfile
  docker/iml-action-runner.dockerfile
  docker/iml-agent-comms.dockerfile
  docker/iml-api.dockerfile
  docker/iml-mailbox.dockerfile
  docker/iml-manager-cli.dockerfile
  docker/iml-ostpool.dockerfile
  docker/iml-postoffice.dockerfile
  docker/iml-stats.dockerfile
  docker/iml-timer.dockerfile
  docker/iml-warp-drive.dockerfile
  docker/job-scheduler.dockerfile
  docker/lustre-audit.dockerfile
  docker/plugin-runner.dockerfile
  docker/power-control.dockerfile
  docker/setup.dockerfile
  docker/syslog.dockerfile
  iml-agent-comms/Cargo.toml
  iml-agent/Cargo.toml
  iml-api-utils/Cargo.toml
  iml-api/Cargo.toml
  iml-cmd/Cargo.toml
  iml-fs/Cargo.toml
  iml-gui/crate/Cargo.lock
  iml-gui/crate/Cargo.toml
  iml-gui/crate/src/page/partial/footer.rs
  iml-job-scheduler-rpc/Cargo.toml
  iml-mailbox/Cargo.toml
  iml-manager-cli/Cargo.toml
  iml-manager-client/Cargo.toml
  iml-manager-env/Cargo.toml
  iml-orm/Cargo.toml
  iml-postgres/Cargo.toml
  iml-rabbit/Cargo.toml
  iml-request-retry/Cargo.toml
  iml-services/iml-action-runner/Cargo.toml
  iml-services/iml-ostpool/Cargo.toml
  iml-services/iml-postoffice/Cargo.toml
  iml-services/iml-service-queue/Cargo.toml
  iml-services/iml-stats/Cargo.toml
  iml-system-tests/Cargo.toml
  iml-timer/Cargo.toml
  iml-util/Cargo.toml
  iml-warp-drive/Cargo.toml
  iml-wire-types/Cargo.toml
  liblustreapi-types/Cargo.toml
  liblustreapi/Cargo.toml
  python-iml-manager.spec
  rust-iml.spec
  setup.py
  tokio-runtime-shutdown/Cargo.toml
  vagrant/Vagrantfile
Labels: chore

#1757 Implement device-aggregator as iml daemon plugin
  .copr/Makefile
  10-device-aggregator.service.conf
  Cargo.lock
  Cargo.toml
  chroma-manager.conf.template
  docker/Makefile
  docker/docker-compose.override.yml
  docker/docker-compose.yml
  docker/iml-device.dockerfile
  docker/setup-nginx
  iml-agent/src/agent_error.rs
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/daemon_plugins/device.rs
  iml-agent/src/daemon_plugins/mod.rs
  iml-device.service
  iml-manager-env/src/lib.rs
  iml-manager.target
  iml-services/iml-device/Cargo.toml
  iml-services/iml-device/fixtures/devtree.json
  iml-services/iml-device/fixtures/devtree_zpool.json
  iml-services/iml-device/fixtures/devtree_zpool_dataset.json
  iml-services/iml-device/src/error.rs
  iml-services/iml-device/src/lib.rs
  iml-services/iml-device/src/linux_plugin_transforms.rs
  iml-services/iml-device/src/main.rs
  iml-services/iml-device/src/snapshots/iml_device__linux_plugin_transforms__tests__devtree2linuxoutput.snap
  iml-services/iml-device/src/snapshots/iml_device__linux_plugin_transforms__tests__devtree2linuxoutput_dataset.snap
  iml-services/iml-device/src/snapshots/iml_device__linux_plugin_transforms__tests__devtree2linuxoutput_zpool.snap
  python-iml-manager.spec
  rust-iml.spec
  vagrant/scripts/install_iml_local.sh
Labels: enhancement

#1764 Use 2.12.4 for client
  vagrant/Vagrantfile
Labels: chore

#1756 Hide the Logs icon from the anonymous user
  iml-gui/crate/src/status_section.rs
Labels: bug

#1765 Make lustre version configurable and singular
  vagrant/Vagrantfile
  vagrant/scripts/install_ldiskfs_no_iml.sh
  vagrant/scripts/install_zfs_no_iml.sh
Labels: chore

#1767 Fix client count
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/page/filesystems.rs
Labels: bug

#1769 Fix docker GUI build
  docker/iml-gui.dockerfile
  iml-gui/crate/Cargo.lock
Labels: bug

#1774 add-device-url
  docker/docker-compose.yml
Labels: bug

#1739 Update page title & breadcrumb with user
  iml-gui/crate/src/components/breadcrumbs.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/mod.rs
  iml-gui/crate/src/page/user.rs
Labels: bug, enhancement

#1776 Fix detection logging
  chroma_core/lib/detection.py
Labels: bug

#1775 Make CLI use influxdb for filesystem stats
  Cargo.lock
  Cargo.toml
  iml-gui/crate/Cargo.lock
  iml-gui/crate/Cargo.toml
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/page/filesystems.rs
  iml-influx/Cargo.toml
  iml-influx/LICENSE
  iml-influx/src/filesystem.rs
  iml-influx/src/filesystems.rs
  iml-influx/src/lib.rs
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/filesystem.rs
  iml-manager-client/Cargo.toml
  iml-manager-client/src/lib.rs
Labels: bug, enhancement

#1768 Fixup lamigo / lpurge code to mesh with HPv2
  iml-agent/src/action_plugins/lamigo.rs
  iml-agent/src/action_plugins/lpurge.rs
  iml-agent/src/action_plugins/snapshots/iml_agent__action_plugins__lamigo__lamigo_tests__works.snap
  iml-agent/src/action_plugins/snapshots/iml_agent__action_plugins__lpurge__lpurge_conf_tests__works.snap
  iml-agent/systemd-units/settings.conf
Labels: chore

#1781 Use postgres 9.6 instead of 9.2
  chroma_core/lib/service_config.py
  docker/docker-compose.yml
  docker/python-service-base.dockerfile
  iml-job-scheduler.service
  iml-manager.target
  iml-settings-populator.service
  python-iml-manager.spec
  tests/framework/chroma_support.repo.in
  tests/framework/services/runner.sh.in
  tests/integration/core/api_testcase_with_test_reset.py
  vagrant/scripts/install_iml_local.sh
  vagrant/scripts/install_iml_repouri.sh
Labels: enhancement

#1787 Extract systemd into its own crate
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/high_availability/mod.rs
  iml-agent/src/lib.rs
  iml-systemd/Cargo.toml
  iml-systemd/src/lib.rs
  iml-systemd/src/systemd_error.rs
  iml-wire-types/src/lib.rs
Labels: enhancement

#1207 Ntp daemon
  .copr/Makefile
  .github/workflows/iml-gui.yml
  .github/workflows/rust-ci.yml
  Cargo.lock
  Cargo.toml
  chroma_core/migrations/0014_multipletimesyncalert_notimesyncalert_timeoutofsyncalert.py
  chroma_core/models/host.py
  chroma_core/models/ntp.py
  docker/docker-compose.override.yml
  docker/docker-compose.yml
  docker/iml-ntp.dockerfile
  docker/rust-base.dockerfile
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/high_availability/mod.rs
  iml-agent/src/action_plugins/ntp/action_configure.rs
  iml-agent/src/action_plugins/ntp/common.rs
  iml-agent/src/action_plugins/ntp/is_ntp_configured.rs
  iml-agent/src/action_plugins/ntp/mod.rs
  iml-agent/src/agent_error.rs
  iml-agent/src/cli.rs
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/daemon_plugins/device.rs
  iml-agent/src/daemon_plugins/mod.rs
  iml-agent/src/daemon_plugins/ntp.rs
  iml-agent/src/snapshots/iml_agent__daemon_plugins__ntp__test__session_with_ntp_configured_by_iml.snap
  iml-manager.target
  iml-ntp.service
  iml-orm/Cargo.toml
  iml-orm/README.md
  iml-orm/diesel.toml
  iml-orm/src/alerts.rs
  iml-orm/src/hosts.rs
  iml-orm/src/lib.rs
  iml-orm/src/models.rs
  iml-orm/src/schema.rs
  iml-services/iml-device/src/linux_plugin_transforms.rs
  iml-services/iml-ntp/Cargo.toml
  iml-services/iml-ntp/src/main.rs
  iml-systemd/src/systemd_error.rs
  iml-wire-types/src/lib.rs
  python-iml-manager.spec
  rust-iml.spec
  vagrant/scripts/install_iml_local.sh
Labels: enhancement

#1789 Lower Active alerts
  iml-gui/crate/Cargo.lock
  iml-gui/crate/src/lib.rs
Labels: bug

#1797 Fix iml-devel provision
  vagrant/Vagrantfile
Labels: bug

#1794 Use device alias for iscsi storage devices
  vagrant/99-external-storage.rules
  vagrant/Vagrantfile
  vagrant/scripts/bootstrap_iscsi.sh
Labels: bug

#1799 Add POSTGRES_HOST_AUTH_METHOD environment var
  docker/docker-compose.yml
Labels: bug

#1804 Cleanup after building to avoid No space errors
  .github/workflows/iml-docker-ci.yml
Labels: bug

#1807 Use table titles in CLI
  iml-manager-cli/src/display_utils.rs
Labels: enhancement

#1786 Fix z-index
  iml-gui/crate/src/components/action_dropdown/mod.rs
  iml-gui/crate/src/page/partial/header.rs
  iml-gui/crate/src/status_section.rs
Labels: bug

#1811 Update deploy restart policy
  docker/docker-compose.yml
Labels: enhancement

#1810 Update systemd to 0.2.0
  Cargo.lock
  Cargo.toml
  iml-agent/Cargo.toml
  iml-systemd/Cargo.toml
Labels: enhancement

#1795 Obsolete device-scanner-proxy
  rust-iml.spec
Labels: bug

#1792 Implement basic storage of devices JSON in Postgres via iml-orm
  Cargo.lock
  chroma_core/migrations/0015_device.py
  chroma_core/models/__init__.py
  chroma_core/models/devices.py
  iml-orm/Cargo.toml
  iml-orm/src/models.rs
  iml-orm/src/schema.rs
  iml-services/iml-device/Cargo.toml
  iml-services/iml-device/src/main.rs
Labels: enhancement

#1818 Add iml-tracing crate
  Cargo.lock
  Cargo.toml
  iml-agent-comms/Cargo.toml
  iml-agent-comms/src/main.rs
  iml-agent/Cargo.toml
  iml-agent/src/cli.rs
  iml-agent/src/http_comms/crypto_client.rs
  iml-agent/src/main.rs
  iml-api/Cargo.toml
  iml-api/src/main.rs
  iml-fs/Cargo.toml
  iml-mailbox/Cargo.toml
  iml-mailbox/src/main.rs
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/main.rs
  iml-services/iml-action-runner/Cargo.toml
  iml-services/iml-action-runner/src/main.rs
  iml-services/iml-device/Cargo.toml
  iml-services/iml-device/src/main.rs
  iml-services/iml-ntp/Cargo.toml
  iml-services/iml-ntp/src/main.rs
  iml-services/iml-ostpool/Cargo.toml
  iml-services/iml-ostpool/src/main.rs
  iml-services/iml-postoffice/Cargo.toml
  iml-services/iml-postoffice/src/main.rs
  iml-services/iml-stats/Cargo.toml
  iml-services/iml-stats/src/main.rs
  iml-timer/Cargo.toml
  iml-timer/src/bin/iml-timer.rs
  iml-timer/src/bin/start-stratagem-scan.rs
  iml-tracing/Cargo.toml
  iml-tracing/src/lib.rs
  iml-warp-drive/Cargo.toml
  iml-warp-drive/src/main.rs
Labels: enhancement

#1821 Add CLI commands for loading / removing profiles
  Cargo.lock
  iml-fs/src/lib.rs
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/error.rs
  iml-manager-cli/src/lib.rs
  iml-manager-cli/src/profile.rs
  iml-manager-cli/src/server.rs
  iml-orm/src/lib.rs
  iml-orm/src/models.rs
  iml-orm/src/profile.rs
  iml-orm/src/repo.rs
Labels: enhancement

#1712 Update system integration test framework
  Cargo.lock
  Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/high_availability/mod.rs
  iml-cmd/src/lib.rs
  iml-system-docker-tests/Cargo.lock
  iml-system-docker-tests/Cargo.toml
  iml-system-docker-tests/tests/docker_integration_test.rs
  iml-system-rpm-tests/Cargo.lock
  iml-system-rpm-tests/Cargo.toml
  iml-system-rpm-tests/tests/vagrant_integration_test.rs
  iml-system-test-utils/Cargo.lock
  iml-system-test-utils/Cargo.toml
  iml-system-test-utils/src/docker.rs
  iml-system-test-utils/src/iml.rs
  iml-system-test-utils/src/lib.rs
  iml-system-test-utils/src/ssh.rs
  iml-system-test-utils/src/vagrant.rs
  iml-system-tests/Cargo.toml
  iml-system-tests/tests/integration_test.rs
  iml-system-tests/tests/vagrant.rs
  iml-wire-types/src/lib.rs
  vagrant/Vagrantfile
  vagrant/scripts/configure_ntp.sh
  vagrant/scripts/wait_for_ntp.sh
Labels: enhancement

#1809 Change titles from Total to Available in GUI
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/page/filesystems.rs
Labels: bug

#1827 Fail fast for integration tests
  Cargo.lock
  iml-cmd/src/lib.rs
  iml-system-docker-tests/Cargo.lock
  iml-system-docker-tests/Cargo.toml
  iml-system-docker-tests/src/lib.rs
  iml-system-docker-tests/tests/docker_integration_test.rs
  iml-system-docker-tests/tests/ldiskfs_test.rs
  iml-system-docker-tests/tests/stratagem_test.rs
  iml-system-docker-tests/tests/zfs_test.rs
  iml-system-rpm-tests/Cargo.lock
  iml-system-rpm-tests/src/lib.rs
  iml-system-rpm-tests/tests/ldiskfs_test.rs
  iml-system-rpm-tests/tests/stratagem_test.rs
  iml-system-rpm-tests/tests/vagrant_integration_test.rs
  iml-system-rpm-tests/tests/zfs_test.rs
  iml-system-test-utils/Cargo.toml
  iml-system-test-utils/src/lib.rs
  iml-system-test-utils/src/ssh.rs
  iml-system-test-utils/src/vagrant.rs
  vagrant/Vagrantfile
  vagrant/scripts/create_iml_diagnostics.sh
Labels: enhancement

#1837 - Updating the vm's is causing CentOS to upgrade
  iml-system-test-utils/src/vagrant.rs
Labels: enhancement

#1840 Always run sosreport at the end of any integration test
  iml-system-test-utils/src/lib.rs
  iml-system-test-utils/src/ssh.rs
  vagrant/scripts/create_iml_diagnostics.sh
Labels: enhancement

#1779 Display tooltips with full date for relative dates
  iml-gui/crate/src/components/date.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/activity.rs
  iml-gui/crate/src/page/server.rs
  iml-gui/crate/src/page/servers.rs
  iml-gui/crate/src/server_date.rs
  iml-gui/crate/src/status_section.rs
Labels: enhancement

#1845 Update sosreport permissions to be 777
  iml-system-test-utils/src/ssh.rs
Labels: enhancement

#1839 Remove LOCAL_SETTINGS module level var wrapper
  settings.py
Labels: tech debt
