Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2020-09, with the labels that each got.

#2203 EX-1629 - Ensure client-mounts do not pickup snapshot mounts
  iml-services/iml-device/src/lib.rs
  iml-services/iml-device/src/main.rs
Labels: enhancement

#2206 Add test_setup fn to iml_postgres
  Cargo.lock
  iml-postgres/Cargo.toml
  iml-postgres/src/lib.rs
  iml-services/iml-device/Cargo.toml
  iml-services/iml-device/tests/integration_tests.rs
Labels: enhancement

#2202 Use IML cli inside iml-timer
  Cargo.lock
  chroma_core/models/stratagem.py
  docker/iml-timer.dockerfile
  iml-timer/Cargo.toml
  iml-timer/src/bin/start-stratagem-scan.rs
  iml-timer/src/error.rs
  iml-timer/src/main.rs
Labels: enhancement

#2196 Account for multiple fs with the same target name
  Cargo.lock
  iml-gui/crate/Cargo.lock
  iml-influx/Cargo.toml
  iml-influx/src/lib.rs
  iml-services/iml-device/Cargo.toml
  iml-services/iml-device/src/lib.rs
  iml-services/iml-device/src/snapshots/iml_device__tests__deletions_only.snap
  iml-services/iml-device/src/snapshots/iml_device__tests__upserts_and_deletions.snap
  iml-services/iml-stats/src/main.rs
Labels: enhancement

#2205 Implement snapshot listing daemons
  .copr/Makefile
  Cargo.lock
  Cargo.toml
  docker/docker-compose.yml
  docker/iml-snapshot.dockerfile
  iml-agent/src/action_plugins/lustre/snapshot/parse.rs
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/daemon_plugins/mod.rs
  iml-agent/src/daemon_plugins/snapshot.rs
  iml-manager.target
  iml-services/iml-snapshot/Cargo.toml
  iml-services/iml-snapshot/src/main.rs
  iml-snapshot.service
  iml-wire-types/src/snapshot.rs
  migrations/20200831174542_snapshot.sql
  python-iml-manager.spec
  rust-iml.spec
  sqlx-data.json
  vagrant/scripts/install_iml_local.sh
Labels: enhancement

#2210 Implement Snapshot listing GraphQL API
  Cargo.lock
  iml-api/Cargo.toml
  iml-api/src/graphql.rs
  iml-wire-types/Cargo.toml
  iml-wire-types/src/snapshot.rs
  sqlx-data.json
Labels: enhancement

#2217 Bump nginx to support tlsv1.3
  chroma-manager.conf.template
  iml-manager-cli/src/snapshots/iml_manager_cli__nginx__tests__replace_template_variables.snap
Labels: enhancement

#2224 Do not warn if snapshot listing cannot be found
  iml-agent/src/daemon_plugins/snapshot.rs
Labels: bug

#2222 Simplify Snapshot structure
  iml-agent/src/action_plugins/lustre/snapshot.rs
  iml-agent/src/action_plugins/lustre/snapshot/parse.rs
  iml-agent/src/daemon_plugins/snapshot.rs
  iml-api/src/graphql.rs
  iml-services/iml-snapshot/src/main.rs
  iml-wire-types/src/snapshot.rs
  sqlx-data.json
Labels: enhancement

#2177 Implement entire Snapshot GraphQL API
  iml-api/src/error.rs
  iml-api/src/graphql.rs
  iml-api/src/main.rs
  iml-rabbit/src/lib.rs
  iml-wire-types/src/lib.rs
  iml-wire-types/src/snapshot.rs
  sqlx-data.json
Labels: enhancement

#2216 Rename "targets" table to "target"
  iml-api/src/graphql.rs
  iml-services/iml-device/src/lib.rs
  iml-services/iml-device/src/main.rs
  migrations/20200728203410_devices.sql
  sqlx-data.json
Labels: bug

#2227 Add clush to vagrant
  vagrant/Vagrantfile
  vagrant/local.cfg
Labels: enhancement

#2225 Add Snapshots to iml-warp-drive
  Cargo.lock
  iml-api/src/graphql.rs
  iml-gui/crate/Cargo.lock
  iml-gui/crate/src/components/stratagem/mod.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/test_utils/fixtures.rs
  iml-warp-drive/src/cache.rs
  iml-warp-drive/src/db_record.rs
  iml-warp-drive/src/main.rs
  iml-wire-types/Cargo.toml
  iml-wire-types/src/db.rs
  iml-wire-types/src/sfa.rs
  iml-wire-types/src/snapshot.rs
  iml-wire-types/src/warp_drive.rs
  migrations/20200831174542_snapshot.sql
  sqlx-data.json
Labels: enhancement

#2212 PR-2211 Add llapi_path2fid support
  liblustreapi/src/lib.rs
Labels: enhancement

#2228 Bump libloading to latest
  Cargo.lock
  liblustreapi-types/Cargo.toml
  liblustreapi/Cargo.toml
  liblustreapi/src/error.rs
  liblustreapi/src/lib.rs
Labels: enhancement

#2235 Add barrier support to snapshot create
  chroma_core/migrations/0025_createsnapshotjob_destroysnapshotjob.py
  chroma_core/models/host.py
  iml-agent/src/action_plugins/lustre/snapshot.rs
  iml-api/src/graphql.rs
  iml-wire-types/src/snapshot.rs
Labels: enhancement

#2236 Add iml-graphql-queries crate
  Cargo.lock
  Cargo.toml
  iml-graphql-queries/Cargo.toml
  iml-graphql-queries/src/lib.rs
  iml-graphql-queries/src/snapshot.rs
  iml-gui/crate/Cargo.lock
  iml-influx/Cargo.toml
  iml-system-test-utils/Cargo.toml
  iml-system-test-utils/src/lib.rs
  iml-timer/Cargo.toml
Labels: enhancement

#2234 Implement snapshot listing in CLI
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/display_utils.rs
  iml-manager-cli/src/lib.rs
  iml-manager-cli/src/main.rs
  iml-manager-cli/src/snapshot.rs
  iml-manager-client/src/lib.rs
Labels: enhancement

#2237 Implement graphql queries for all snapshot queries and mutations
  Cargo.lock
  iml-graphql-queries/src/lib.rs
  iml-graphql-queries/src/snapshot.rs
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/error.rs
  iml-manager-cli/src/snapshot.rs
  iml-manager-client/src/lib.rs
Labels: enhancement

#2233 Target resources endpoint
  iml-api/src/graphql.rs
  sqlx-data.json
Labels: enhancement

#2245 Hardcode docker compose version
  .github/workflows/iml-docker-ci.yml
Labels: chore

#2240 EX-1687 graphql commands
  iml-api/src/graphql.rs
  iml-manager-env/src/lib.rs
  iml-postgres/src/lib.rs
  sqlx-data.json
  vagrant/Vagrantfile
Labels: enhancement

#2209 Add debugql subcommand to manager
  iml-graphql-queries/src/lib.rs
  iml-manager-cli/src/api.rs
  iml-manager-cli/src/main.rs
  iml-manager-client/src/lib.rs
Labels: enhancement

#2247 Add snapshot configuration API
  Cargo.lock
  iml-api/Cargo.toml
  iml-api/src/graphql.rs
  iml-graphql-queries/Cargo.toml
  iml-graphql-queries/src/snapshot.rs
  iml-gui/crate/Cargo.lock
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/test_utils/fixtures.rs
  iml-warp-drive/src/cache.rs
  iml-warp-drive/src/db_record.rs
  iml-wire-types/Cargo.toml
  iml-wire-types/src/graphql_duration.rs
  iml-wire-types/src/lib.rs
  iml-wire-types/src/snapshot.rs
  iml-wire-types/src/warp_drive.rs
  migrations/20200817164118_utils.sql
  migrations/20200824170157_corosync.sql
  migrations/20200831174542_snapshot.sql
  sqlx-data.json
  tests/unit/lib/iml_unit_test_case.py
  vagrant/README.md
Labels: enhancement

#2252 Fix docker releases so older compose is used
  .github/workflows/devel-release.yml
  .github/workflows/prod-release.yml
Labels: bug

#2253 Add list snapshot interval GUI
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/mod.rs
  iml-gui/crate/src/page/snapshot/list.rs
  iml-gui/crate/src/page/snapshot/list_interval.rs
  iml-gui/crate/src/page/snapshot/mod.rs
  iml-gui/crate/src/page/snapshot/take.rs
  iml-gui/crate/src/page/snapshots.rs
Labels: enhancement

#2250 Add iml-timer service to rpm builds
  .copr/Makefile
  chroma-manager.conf.template
  chroma_core/management/commands/print-settings.py
  chroma_core/models/stratagem.py
  docker/docker-compose.yml
  docker/iml-timer/iml-timer.conf
  docker/nginx.dockerfile
  docker/setup-nginx
  iml-job-scheduler.service
  iml-manager-cli/src/nginx.rs
  iml-manager-cli/src/snapshots/iml_manager_cli__nginx__tests__replace_template_variables.snap
  iml-manager.target
  iml-timer.service
  python-iml-manager.spec
  rust-iml.spec
  settings.py
  vagrant/scripts/install_iml_local.sh
Labels: enhancement

#2256 Create add interval modal
  iml-gui/crate/Cargo.lock
  iml-gui/crate/Cargo.toml
  iml-gui/crate/src/page/snapshot/add_interval.rs
  iml-gui/crate/src/page/snapshot/list_interval.rs
  iml-gui/crate/src/page/snapshot/mod.rs
  iml-gui/crate/src/page/snapshot/take.rs
Labels: enhancement

#2260 Make task remove idempotent
  chroma_core/models/task.py
Labels: enhancement

#2257 Add snapshot interval operations to CLI
  Cargo.lock
  iml-api/src/graphql.rs
  iml-graphql-queries/src/snapshot.rs
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/display_utils.rs
  iml-manager-cli/src/snapshot.rs
  sqlx-data.json
Labels: enhancement

#2264 Fix add_interval.rs
  iml-gui/crate/src/page/snapshot/add_interval.rs
Labels: bug

#2251 Extract command polling logic to it's own crate
  Cargo.lock
  Cargo.toml
  iml-command-utils/Cargo.toml
  iml-command-utils/src/lib.rs
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/error.rs
Labels: enhancement

#2266 Implement snapshot interval deletion support in GUI
  iml-graphql-queries/src/snapshot.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/snapshot/add_interval.rs
  iml-gui/crate/src/page/snapshot/list_interval.rs
  iml-gui/crate/src/page/snapshot/mod.rs
  iml-manager-cli/src/snapshot.rs
Labels: enhancement

#2246 Implement idle snapshot autounmount
  Cargo.lock
  Cargo.toml
  iml-command-utils/src/lib.rs
  iml-services/iml-snapshot/Cargo.toml
  iml-services/iml-snapshot/src/main.rs
  sqlx-data.json
Labels: enhancement

#2270 Pin Toolz dep to 0.10.0
  Pipfile.lock
  requirements.txt
Labels: chore

#2267 Add snapshot retention ops to CLI
  iml-api/src/graphql.rs
  iml-graphql-queries/src/snapshot.rs
  iml-manager-cli/src/display_utils.rs
  iml-manager-cli/src/snapshot.rs
  iml-warp-drive/src/cache.rs
  iml-wire-types/src/snapshot.rs
  migrations/20200831174542_snapshot.sql
  sqlx-data.json
Labels: enhancement

#2269 GH-2268 Update the limit param in graphql api's
  iml-api/src/graphql.rs
Labels: enhancement

#2272 Fix parse
  iml-api/src/graphql.rs
Labels: bug

#2274 Fix Limit
  iml-api/src/graphql.rs
Labels: bug

#2276 Lower snapshot listing interval
  iml-agent/src/daemon_plugins/snapshot.rs
Labels: enhancement

#2277 Use transaction for table update
  iml-services/iml-snapshot/src/main.rs
Labels: bug

#2265 Implement fetching commands by ids
  iml-api/src/graphql.rs
  sqlx-data.json
Labels: enhancement

#2280 Use three dashes instead of two
  iml-manager-cli/src/display_utils.rs
Labels: chore

#2259 Retention analysis
  Cargo.lock
  iml-api/src/graphql.rs
  iml-graphql-queries/src/snapshot.rs
  iml-gui/crate/src/page/snapshot/create_retention.rs
  iml-manager-cli/src/snapshot.rs
  iml-services/iml-snapshot/Cargo.toml
  iml-services/iml-snapshot/src/client_monitor.rs
  iml-services/iml-snapshot/src/lib.rs
  iml-services/iml-snapshot/src/main.rs
  iml-services/iml-snapshot/src/retention.rs
  sqlx-data.json
Labels: enhancement

#2278 Implement feature flag support for snapshots
  chroma_core/management/commands/print-settings.py
  docker/docker-compose.yml
  iml-api/src/main.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/partial/header.rs
  iml-manager-env/src/lib.rs
  iml-wire-types/src/lib.rs
  settings.py
Labels: enhancement

#2161 Filesync
  chroma_core/lib/stratagem.py
  chroma_core/migrations/0026_runstratagemjob_search_expression.py
  chroma_core/models/stratagem.py
  chroma_core/services/job_scheduler/job_scheduler.py
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/stratagem/action_cloudsync.rs
  iml-agent/src/action_plugins/stratagem/action_filesync.rs
  iml-agent/src/action_plugins/stratagem/mod.rs
  iml-agent/src/cli.rs
  iml-manager-cli/src/stratagem.rs
  liblustreapi/src/lib.rs
Labels: enhancement
