Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2020-02, with the labels that each got.

#1500 `warp-drive` cache should have `Arc` variant
  iml-gui/crate/src/components/activity_indicator.rs
  iml-gui/crate/src/components/alert_indicator.rs
  iml-gui/crate/src/components/tree.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/server.rs
  iml-warp-drive/src/cache.rs
  iml-warp-drive/src/listen.rs
  iml-wire-types/Cargo.toml
  iml-wire-types/src/db.rs
  iml-wire-types/src/lib.rs
  iml-wire-types/src/warp_drive.rs
  iml-wire-types/wire-types.rs
Labels: enhancement

#1545 Add chroma-config profile list
  chroma_core/lib/service_config.py
Labels: enhancement

#1543 Add page enum
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/filesystem_detail.rs
  iml-gui/crate/src/page/login.rs
  iml-gui/crate/src/page/mod.rs
  iml-gui/crate/src/page/ostpool_detail.rs
  iml-gui/crate/src/page/server.rs
  iml-gui/crate/src/page/server_detail.rs
  iml-gui/crate/src/page/target_detail.rs
  iml-gui/crate/src/page/user_detail.rs
  iml-gui/crate/src/page/volume_detail.rs
  iml-gui/crate/src/route.rs
Labels: enhancement

#1550 Fix clippy error
  iml-manager-cli/src/server.rs
Labels: enhancement

#1556 Add Series Check to Stragem Library
  chroma_core/lib/stratagem.py
Labels: bug

#1549 Save docker images and install with RPM
  .copr/Makefile
  .dockerignore
  .github/workflows/iml-docker-ci.yml
  .gitignore
  .travis.yml
  docker/Makefile
  docker/docker-compose.yml
  docker/iml-action-runner.dockerfile
  docker/iml-agent-comms.dockerfile
  docker/iml-cli-proxy.sh
  docker/iml-manager-cli.dockerfile
  docker/iml-ostpool.dockerfile
  docker/iml-postoffice.dockerfile
  docker/iml-stratagem.dockerfile
  docker/iml-warp-drive.dockerfile
  docker/iml-wasm-components.dockerfile
  docker/rust-base.dockerfile
  iml-docker.service
  iml-docker.spec
Labels: enhancement

#1411 Integrate Mailbox into docker
  docker/docker-compose.yml
  docker/iml-mailbox.dockerfile
  docker/iml-mailbox/iml-mailbox.conf
  docker/iml-mailbox/iml-mailbox.service
  docker/setup-nginx
Labels: enhancement

#1559 Update to newer Vagrantfile
  vagrant/Vagrantfile
Labels: chore

#1538 Add lock indicator component
  iml-gui/configs/tailwind.config.js
  iml-gui/configs/webpack.config.js
  iml-gui/crate/src/components/lock_indicator.rs
  iml-gui/crate/src/components/popover.rs
  iml-gui/crate/src/generated/css_classes.rs
Labels: enhancement

#1561 Cleanup github actions
  .github/workflows/devel-release.yml
  .github/workflows/iml-docker-ci.yml
  .github/workflows/iml-gui.yml
  .github/workflows/prod-release.yml
Labels: bug

#1562 Bump docker tags
  .dockerignore
  .travis.yml
  docker/Makefile
  docker/base.dockerfile
  docker/corosync.dockerfile
  docker/docker-compose.yml
  docker/gunicorn.dockerfile
  docker/http-agent.dockerfile
  docker/job-scheduler.dockerfile
  docker/lustre-audit.dockerfile
  docker/plugin-runner.dockerfile
  docker/power-control.dockerfile
  docker/setup.dockerfile
  docker/stats.dockerfile
  docker/syslog.dockerfile
Labels: chore

#1560 Synchronize file processing with incoming streams
  iml-mailbox/src/lib.rs
  iml-mailbox/src/main.rs
Labels: bug

#1563 Create a module with common attributes
  iml-gui/crate/src/components/alert_indicator.rs
  iml-gui/crate/src/components/attrs.rs
  iml-gui/crate/src/components/lock_indicator.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/components/tooltip.rs
Labels: tech debt

#1564 Bump to latest seed
  iml-gui/crate/Cargo.lock
  iml-gui/crate/Cargo.toml
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/login.rs
Labels: chore

#1551 Put cluster in maintence mode before changing port
  Cargo.lock
  MANIFEST.in
  chroma_core/models/corosync2.py
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/check_kernel.rs
  iml-agent/src/action_plugins/check_stonith.rs
  iml-agent/src/action_plugins/firewall_cmd.rs
  iml-agent/src/action_plugins/fixtures/check_ha_test_mixed_mode.xml
  iml-agent/src/action_plugins/fixtures/corosync-cmapctl-totem.txt
  iml-agent/src/action_plugins/fixtures/corosync.conf
  iml-agent/src/action_plugins/high_availability/corosync_conf.rs
  iml-agent/src/action_plugins/high_availability/mod.rs
  iml-agent/src/action_plugins/high_availability/snapshots/tests__corosync_cmapctl_output.snap
  iml-agent/src/action_plugins/high_availability/snapshots/tests__update_config_version.snap
  iml-agent/src/action_plugins/high_availability/snapshots/tests__update_mcast_port.snap
  iml-agent/src/action_plugins/kernel_module.rs
  iml-agent/src/action_plugins/lustre.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/cli.rs
  iml-agent/src/lustre.rs
  iml-agent/src/rpm.rs
  iml-agent/src/systemd.rs
  iml-cmd/Cargo.toml
  iml-cmd/src/lib.rs
  iml-fs/src/lib.rs
  iml-manager-cli/Cargo.toml
  setup.py
  tests/integration/core/remote_operations.py
  tests/integration/shared_storage_configuration/test_corosync.py
Labels: bug

#1565 Use Centos:7 for rust-base and systemd-base
  docker/Makefile
  docker/base.dockerfile
  docker/iml-mailbox.dockerfile
  docker/rust-base.dockerfile
  docker/systemd-base.dockerfile
Labels: chore, tech debt

#1568 Remove the stratagem daemon-plugin.
  .copr/Makefile
  Cargo.lock
  Cargo.toml
  docker/docker-compose.override.yml
  docker/docker-compose.yml
  docker/iml-stratagem.dockerfile
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/daemon_plugins/mod.rs
  iml-agent/src/daemon_plugins/stratagem.rs
  iml-manager.target
  iml-services/iml-stratagem/Cargo.toml
  iml-services/iml-stratagem/src/main.rs
  iml-stratagem.service
  python-iml-manager.spec
  rust-iml.spec
  vagrant/scripts/install_iml_local.sh
Labels: tech debt

#1573 Add rust interface to call job_scheduler
  Cargo.lock
  Cargo.toml
  iml-job-scheduler-rpc/Cargo.toml
  iml-job-scheduler-rpc/src/lib.rs
  iml-job-scheduler-rpc/src/request.rs
  iml-job-scheduler-rpc/src/response.rs
  iml-rabbit/src/lib.rs
Labels: enhancement

#1445 Setup a timer to handle stratagem scans at specified intervals
  Cargo.lock
  Cargo.toml
  chroma_core/lib/service_config.py
  chroma_core/lib/util.py
  chroma_core/models/stratagem.py
  docker/Makefile
  docker/corosync.dockerfile
  docker/docker-compose.yml
  docker/gunicorn.dockerfile
  docker/http-agent.dockerfile
  docker/iml-action-runner.dockerfile
  docker/iml-agent-comms.dockerfile
  docker/iml-api.dockerfile
  docker/iml-manager-cli.dockerfile
  docker/iml-ostpool.dockerfile
  docker/iml-postoffice.dockerfile
  docker/iml-timer.dockerfile
  docker/iml-timer/iml-timer.conf
  docker/iml-timer/iml-timer.service
  docker/iml-warp-drive.dockerfile
  docker/job-scheduler.dockerfile
  docker/lustre-audit.dockerfile
  docker/nginx.dockerfile
  docker/plugin-runner.dockerfile
  docker/power-control.dockerfile
  docker/python-service-base.dockerfile
  docker/rust-base.dockerfile
  docker/rust-service-base.dockerfile
  docker/setup-nginx
  docker/setup.dockerfile
  docker/stats.dockerfile
  docker/syslog.dockerfile
  iml-cmd/Cargo.toml
  iml-cmd/src/lib.rs
  iml-manager-env/src/lib.rs
  iml-timer/Cargo.toml
  iml-timer/src/bin/iml-timer.rs
  iml-timer/src/bin/start-stratagem-scan.rs
  iml-timer/src/config.rs
  iml-timer/src/error.rs
  iml-timer/src/lib.rs
  settings.py
Labels: enhancement

#1572 Refactor get_targets_by_fs_id()
  iml-gui/crate/src/components/tree.rs
Labels: tech debt

#1580 Allow conversion from `CompositeId` to an erased `ArcCache` record
  Cargo.lock
  chroma_core/migrations/0009_django_content_type_json_notify.py
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/test_utils/fixtures.rs
  iml-postgres/Cargo.toml
  iml-warp-drive/Cargo.toml
  iml-warp-drive/src/cache.rs
  iml-warp-drive/src/db_record.rs
  iml-wire-types/Cargo.toml
  iml-wire-types/src/db.rs
  iml-wire-types/src/lib.rs
  iml-wire-types/src/warp_drive.rs
Labels: enhancement

#1579 Try to use alpine images for postgres and rabbit.
  docker/docker-compose.yml
Labels: chore

#1449 Implement action-dropdown
  iml-gui/configs/webpack.config.js
  iml-gui/crate/Cargo.lock
  iml-gui/crate/src/components/action_dropdown/confirm_action_modal.rs
  iml-gui/crate/src/components/action_dropdown/mod.rs
  iml-gui/crate/src/components/dropdown.rs
  iml-gui/crate/src/components/lnet_status.rs
  iml-gui/crate/src/components/lock_indicator.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/components/modal.rs
  iml-gui/crate/src/components/paging.rs
  iml-gui/crate/src/components/tooltip.rs
  iml-gui/crate/src/extensions.rs
  iml-gui/crate/src/generated/css_classes.rs
  iml-gui/crate/src/key_codes.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/server.rs
  iml-gui/css/custom.css
  iml-gui/package.json
  iml-gui/yarn.lock
  iml-wire-types/src/db.rs
  iml-wire-types/src/lib.rs
  iml-wire-types/src/warp_drive.rs
Labels: enhancement

#1592 Implement get-retry
  Cargo.lock
  iml-manager-client/Cargo.toml
  iml-manager-client/src/lib.rs
  iml-request-retry/README.md
  iml-warp-drive/src/cache.rs
Labels: enhancement

#1594 Prevent mixing _topdir from host and adm
  vagrant/Vagrantfile
Labels: bug

#1595 Switch branding
  iml-gui/crate/src/components/logo.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/page/login.rs
  iml-gui/crate/src/page/partial/header.rs
Labels: enhancement

#1497 Implement Filesystem pages
  iml-gui/crate/Cargo.lock
  iml-gui/crate/Cargo.toml
  iml-gui/crate/src/components/alert_indicator.rs
  iml-gui/crate/src/components/lnet_status.rs
  iml-gui/crate/src/components/lock_indicator.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/components/pie_chart.rs
  iml-gui/crate/src/components/table.rs
  iml-gui/crate/src/components/tree.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/dashboard.rs
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/page/filesystems.rs
  iml-gui/crate/src/page/mod.rs
  iml-gui/crate/src/page/servers.rs
  iml-gui/crate/src/route.rs
  iml-wire-types/src/lib.rs
Labels: enhancement

#1493 Account for pacemaker template types
  iml-agent/src/action_plugins/fixtures/check_ha_test_mixed_mode.xml
  iml-agent/src/action_plugins/high_availability/fixtures/crm-resource-chroma-stonith.xml
  iml-agent/src/action_plugins/high_availability/fixtures/crm-resource-es-ost.xml
  iml-agent/src/action_plugins/high_availability/fixtures/crm-resource-iml-mgs.xml
  iml-agent/src/action_plugins/high_availability/mod.rs
  iml-wire-types/src/lib.rs
Labels: enhancement

#1598 Commit forgotten Cargo.lock and require it being always committed on CI
  .github/workflows/iml-gui.yml
  .github/workflows/rust-ci.yml
  .github/workflows/wasm-ci.yml
  Cargo.lock
  iml-gui/crate/src/page/filesystem.rs
Labels: chore

#1599 ensure we close channel after making rpc call
  iml-job-scheduler-rpc/src/lib.rs
Labels: bug

#1601 Use lapin instead of lapin-futures
  Cargo.lock
  iml-agent-comms/Cargo.toml
  iml-agent-comms/src/main.rs
  iml-agent-comms/src/messaging.rs
  iml-agent/Cargo.toml
  iml-api/Cargo.toml
  iml-api/src/action.rs
  iml-api/src/main.rs
  iml-job-scheduler-rpc/src/lib.rs
  iml-rabbit/Cargo.toml
  iml-rabbit/src/lib.rs
  iml-services/iml-action-runner/Cargo.toml
  iml-services/iml-action-runner/src/main.rs
  iml-services/iml-action-runner/src/receiver.rs
  iml-services/iml-action-runner/src/sender.rs
  iml-services/iml-action-runner/tests/action_runner_tests.rs
  iml-services/iml-service-queue/src/service_queue.rs
  iml-warp-drive/src/locks.rs
Labels: chore

#1600 Conditionally skip yum check
  chroma_cli/handlers.py
  chroma_core/models/host.py
  chroma_core/models/host_jobs/test_host_contact.py
  chroma_help/help.py
Labels: enhancement

#1537 Ticket model & API
  chroma_api/ticket.py
  chroma_api/urls.py
  chroma_core/lib/cache.py
  chroma_core/lib/detection.py
  chroma_core/migrations/0010_tickets.py
  chroma_core/models/__init__.py
  chroma_core/models/filesystem.py
  chroma_core/models/target.py
  chroma_core/models/ticket.py
  chroma_help/help.py
  tests/unit/chroma_core/services/job_scheduler/test_available_transitions.py
Labels: enhancement

#1602 Do not load docker images in RPM %post block
  iml-docker.service
  iml-docker.spec
Labels: enhancement

#1605 Update Tailwind
  iml-gui/crate/src/generated/css_classes.rs
  iml-gui/package.json
  iml-gui/yarn.lock
Labels: enhancement

#1603 Package new GUI as RPM and docker image
  .copr/Makefile
  .dockerignore
  .github/workflows/devel-release.yml
  .github/workflows/iml-gui.yml
  Makefile
  chroma-manager.conf.template
  docker/Makefile
  docker/iml-gui.dockerfile
  docker/nginx.dockerfile
  iml-api/src/action.rs
  iml-gui/configs/webpack.config.js
  iml-gui/crate/src/event_source.rs
  iml-gui/crate/src/extensions.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/notification.rs
  iml-gui/crate/src/route.rs
  iml-gui/entries/index.hbs
  iml-gui/entries/templates/favicons.hbs
  iml-gui/entries/templates/head_scripts.hbs
  iml-gui/package.json
  iml-gui/rust-iml-gui.spec
  iml-gui/yarn.lock
  python-iml-manager.spec
Labels: chore

#1611 Fixup iml-gui deploy
  .github/workflows/devel-release.yml
Labels: bug

#1613 Fixup deploys for iml-docker and rust-iml-gui
  .copr/Makefile
  iml-docker.spec
Labels: bug

#1615 Remove extra layer of boxing
  iml-gui/crate/src/components/action_dropdown/mod.rs
  iml-wire-types/src/warp_drive.rs
Labels: enhancement

#1609 Add Tickets found during DetectScan
  chroma_core/lib/detection.py
  chroma_core/migrations/0010_tickets.py
  chroma_core/models/filesystem.py
  chroma_core/models/host.py
  chroma_core/models/target.py
  chroma_core/models/ticket.py
  chroma_help/help.py
  iml-agent/src/action_plugins/action_plugin.rs
Labels: bug, enhancement

#1612 Update alert_indicator to take composite ids
  Cargo.lock
  chroma_api/alert.py
  iml-gui/crate/src/components/alert_indicator.rs
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/page/servers.rs
  iml-wire-types/src/db.rs
  iml-wire-types/src/lib.rs
Labels: enhancement

#1614 Add Private key and Password auth types to server add
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/cli.rs
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/main.rs
  iml-manager-cli/src/server.rs
  iml-manager-cli/src/stratagem.rs
  iml-timer/Cargo.toml
Labels: enhancement

#1616 Add filesystem detect command
  iml-manager-cli/src/filesystem.rs
Labels: enhancement
