Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2020-10, with the labels that each got.

#1803 Update calculation of free/used space in IML CLI
  iml-manager-cli/src/display_utils.rs
  iml-manager-cli/src/filesystem.rs
Labels: bug, enhancement

#2294 Remove CLI indirection
  docker/docker-compose.yml
  docker/iml-manager-cli.dockerfile
Labels: bug

#2299 Update Ddn Branding
  iml-gui/crate/src/components/logo.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/page/partial/header.rs
Labels: enhancement

#2285 Add shell completions for CLI
  iml-manager-cli/src/main.rs
  rust-iml.spec
Labels: enhancement

#2301 Use default-tls for wbem-client
  Cargo.lock
  wbem-client/Cargo.toml
Labels: bug

#2303 Fix enable snapshot race
  chroma_core/management/commands/print-settings.py
  docker/docker-compose.yml
  iml-manager-env/src/lib.rs
  settings.py
Labels: bug

#2302 GH-2298 - File used percentage slightly off
  iml-gui/crate/src/components/chart/fs_usage.rs
  iml-gui/crate/src/components/progress_circle.rs
  iml-gui/crate/src/page/filesystem.rs
  iml-services/iml-snapshot/src/retention.rs
Labels: bug

#2297 Update text color for available space on the chart
  iml-gui/crate/src/components/dashboard/dashboard_fs_usage.rs
Labels: chore

#2304 EX-1850 - Implement Report query and deletion
  docker/docker-compose.yml
  iml-api/src/graphql.rs
Labels: enhancement

#2306 Remove "Other" bucket
  iml-agent/src/action_plugins/stratagem/server.rs
Labels: bug

#2305 Allow different names for IML CLI
  iml-manager-cli/src/config-main.rs
  iml-manager-cli/src/filesystem.rs
  iml-manager-cli/src/lib.rs
  iml-manager-cli/src/main.rs
  iml-manager-cli/src/ostpool.rs
  iml-manager-cli/src/profile.rs
  iml-manager-cli/src/server.rs
  iml-manager-cli/src/snapshot.rs
  iml-manager-cli/src/update_repo_file.rs
Labels: enhancement

#2311 Account for empty ARRAY.VALUE
  Cargo.lock
  docker/docker-compose.yml
  iml-agent/Cargo.toml
  iml-manager-cli/Cargo.toml
  iml-services/iml-journal/Cargo.toml
  wbem-client/Cargo.toml
  wbem-client/src/cim_xml.rs
  wbem-client/src/snapshots/wbem_client__cim_xml__resp__tests__instance.snap
  wbem-client/src/snapshots/wbem_client__cim_xml__resp__tests__instance_list.snap
Labels: bug

#2312 Fix target table
  iml-services/iml-device/src/lib.rs
Labels: bug

#2315 Remove spinners lib from manager cli.
  Cargo.lock
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/display_utils.rs
  iml-manager-cli/src/stratagem.rs
  iml-rabbit/Cargo.toml
Labels: bug

#2324 Change reserve_value to doc comment
  iml-manager-cli/src/snapshot.rs
Labels: bug

#2333 Add pbr to requirements
  docker/python-service-base.dockerfile
  tests/framework/services/runner.sh.in
Labels: chore

#2290 chroma: Add graphql helper function
  chroma_core/lib/graphql.py
  chroma_core/lib/util.py
  chroma_core/models/filesystem.py
  docker/python-service-base.dockerfile
  settings.py
Labels: enhancement

#2316 Add graphql schema listing support
  chroma-manager.conf.template
  iml-api/src/graphql.rs
  iml-manager-cli/src/snapshots/iml_manager_cli__nginx__tests__replace_template_variables.snap
Labels: enhancement

#2293 Pass RUST_LOG to cli
  docker/iml-cli-proxy.sh
Labels: bug

#2319 Add devpath to targets
  Cargo.lock
  iml-api/src/graphql.rs
  iml-services/iml-device/src/lib.rs
  iml-services/iml-device/src/main.rs
  iml-services/iml-device/src/snapshots/iml_device__tests__deletions_only.snap
  iml-services/iml-device/src/snapshots/iml_device__tests__upserts_and_deletions.snap
  iml-services/iml-device/src/snapshots/iml_device__tests__upserts_only.snap
  migrations/20201008184126_target_devpath_column.sql
  sqlx-data.json
Labels: enhancement

#2339 Fix quoting for graphql query from FS
  chroma_core/models/filesystem.py
Labels: bug

#2328 Convert stratagem scanning over to graphql
  Cargo.lock
  chroma-manager.conf.template
  chroma_api/stratagem.py
  chroma_api/urls.py
  chroma_core/migrations/0027_add_scan_mdt_jobs.py
  chroma_core/models/stratagem.py
  chroma_core/services/job_scheduler/job_scheduler.py
  chroma_core/services/job_scheduler/job_scheduler_client.py
  chroma_help/help.py
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-api/Cargo.toml
  iml-api/src/graphql/mod.rs
  iml-api/src/graphql/stratagem.rs
  iml-api/src/graphql/task.rs
  iml-api/src/main.rs
  iml-api/src/task.rs
  iml-graphql-queries/src/lib.rs
  iml-graphql-queries/src/stratagem.rs
  iml-graphql-queries/src/task.rs
  iml-gui/crate/Cargo.lock
  iml-gui/crate/src/components/stratagem/mod.rs
  iml-gui/crate/src/components/stratagem/scan_stratagem_button.rs
  iml-gui/crate/src/components/stratagem/scan_stratagem_modal.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/page/mod.rs
  iml-mailbox/src/lib.rs
  iml-manager-cli/src/api.rs
  iml-manager-cli/src/snapshot.rs
  iml-manager-cli/src/snapshots/iml_manager_cli__nginx__tests__replace_template_variables.snap
  iml-manager-cli/src/stratagem.rs
  iml-system-docker-tests/tests/stratagem_test.rs
  iml-system-rpm-tests/tests/stratagem_test.rs
  iml-system-test-utils/Cargo.toml
  iml-system-test-utils/src/lib.rs
  iml-system-test-utils/src/snapshots.rs
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_ldiskfs_test_path_from_graph.snap
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_stratagem_test_path_from_graph.snap
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_zfs_test_path_from_graph.snap
  iml-system-test-utils/src/ssh.rs
  iml-task-runner/src/main.rs
  iml-wire-types/src/lib.rs
  iml-wire-types/src/stratagem.rs
  iml-wire-types/src/task.rs
  sqlx-data.json
Labels: enhancement

#2292 Update lamigo/lpurge for lipe compatibililty
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/lamigo.rs
  iml-agent/src/action_plugins/lpurge.rs
  iml-agent/src/action_plugins/ltuer.rs
  iml-agent/src/action_plugins/mod.rs
  iml-agent/src/action_plugins/snapshots/iml_agent__action_plugins__lamigo__lamigo_tests__works.snap
  iml-agent/src/action_plugins/snapshots/iml_agent__action_plugins__lpurge__lpurge_conf_tests__works.snap
  iml-agent/src/cli.rs
Labels: bug

#2342 Fix Vbox fencing
  vagrant/Vagrantfile
  vagrant/scripts/create_ldiskfs_lvm_mds_ha_setup.sh
  vagrant/scripts/create_ldiskfs_lvm_oss_ha_setup.sh
Labels: bug

#2341 Reconfigure zfs-zed before start zed-enhancer
  device-scanner/zed-enhancer/systemd-units/zed-enhancer.service
Labels: bug

#2334 Implement GUI for Stratagem reports
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/mod.rs
  iml-gui/crate/src/page/partial/header.rs
  iml-gui/crate/src/page/snapshot/mod.rs
  iml-gui/crate/src/page/stratagem/mod.rs
  iml-gui/crate/src/page/stratagem/report.rs
  iml-gui/crate/src/route.rs
Labels: enhancement

#2345 Fixup changed structure path
  iml-gui/crate/Cargo.lock
  iml-gui/crate/src/page/stratagem/mod.rs
  iml-gui/crate/src/page/stratagem/report.rs
Labels: bug

#2134 Implement the fix
  iml-gui/crate/src/components/command_modal.rs
Labels: bug

#2336 Switch UI to new logs GraphQL endpoint
  chroma_api/log.py
  chroma_api/urls.py
  iml-api/src/graphql/mod.rs
  iml-graphql-queries/src/lib.rs
  iml-graphql-queries/src/log.rs
  iml-graphql-queries/src/snapshot.rs
  iml-gui/crate/src/page/logs.rs
  iml-services/iml-journal/src/lib.rs
  iml-wire-types/src/db.rs
  iml-wire-types/src/lib.rs
  migrations/20201022090849_rowcount_trigger.sql
  sqlx-data.json
  tests/unit/chroma_api/test_log.py
  tests/unit/chroma_api/test_query_scaling.py
  tests/unit/chroma_api/test_target.py
Labels: enhancement

#2352 Add add/remove_fstab_entry agent actions
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/lustre/client.rs
Labels: enhancement

#2350 Error on unknown FS
  iml-api/src/graphql/mod.rs
Labels: bug

#2348 Stop client changes when adding / removing servers
  chroma_core/models/client_mount.py
Labels: bug

#2356 Update action-client
  iml-action-client/src/lib.rs
  iml-task-runner/src/main.rs
Labels: enhancement
