Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2020-03, with the labels that each got.

#1597 Add action dropdown to fs and fs detail pages.
  iml-gui/configs/tailwind.config.js
  iml-gui/crate/Cargo.lock
  iml-gui/crate/src/components/action_dropdown/mod.rs
  iml-gui/crate/src/components/dropdown.rs
  iml-gui/crate/src/components/paging.rs
  iml-gui/crate/src/components/table.rs
  iml-gui/crate/src/components/tree.rs
  iml-gui/crate/src/generated/css_classes.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/page/filesystems.rs
  iml-gui/crate/src/page/mod.rs
  iml-gui/crate/src/page/partial/header.rs
  iml-gui/crate/src/page/servers.rs
  iml-gui/package.json
  iml-gui/yarn.lock
  iml-wire-types/src/warp_drive.rs
Labels: enhancement

#1619 Add repos/profiles during setup
  Makefile
  docker/docker-compose.yml
  docker/setup.sh
  iml-docker.spec
Labels: enhancement

#1623 Add paging / updates and removes to the filesystem page
  iml-gui/crate/src/components/action_dropdown/confirm_action_modal.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/page/filesystems.rs
Labels: enhancement

#1624 Only check for rpms installed not repos disabled
  chroma_core/models/host_jobs/test_host_contact.py
Labels: bug

#1626 Switch the default port
  iml-gui/configs/webpack.config.js
  iml-gui/crate/src/event_source.rs
Labels: chore

#1625 Remove some pages from header
  iml-gui/crate/src/page/partial/header.rs
Labels: enhancement

#1629 Return empty list if resource list is empty in get_ha_resource_list
  iml-agent/src/action_plugins/high_availability/mod.rs
Labels: bug

#1628 Extract progress_circle
  iml-gui/configs/tailwind.config.js
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/components/pie_chart.rs
  iml-gui/crate/src/components/progress_circle.rs
  iml-gui/crate/src/generated/css_classes.rs
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/css/custom.css
Labels: enhancement

#1631 Only pass hosts argument to DetectTarget if there are hosts
  iml-manager-cli/src/filesystem.rs
Labels: bug

#1634 Update stratagem api validation
  chroma_api/stratagem.py
Labels: enhancement

#1617 Don't allow "Remove" of mgs with MasterTicket
  chroma_core/models/target.py
Labels: bug

#1646 Add wait for iml service to fully up
  docker/iml-cli-proxy.sh
  iml-docker.service
Labels: enhancement

#1647 Add MGT page
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/components/resource_links.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/page/filesystems.rs
  iml-gui/crate/src/page/mgt.rs
  iml-gui/crate/src/page/mgts.rs
  iml-gui/crate/src/page/mod.rs
Labels: enhancement

#1648 Add grafana charts on the filesystem page
  iml-gui/configs/webpack.config.js
  iml-gui/crate/Cargo.lock
  iml-gui/crate/Cargo.toml
  iml-gui/crate/src/components/grafana_chart.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/components/stratagem/inode_table.rs
  iml-gui/crate/src/components/stratagem/mod.rs
  iml-gui/crate/src/page/filesystem.rs
Labels: enhancement

#1653 Implement target page
  iml-gui/configs/tailwind.config.js
  iml-gui/crate/src/components/action_dropdown/mod.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/components/modal.rs
  iml-gui/crate/src/components/panel.rs
  iml-gui/crate/src/generated/css_classes.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/mgts.rs
  iml-gui/crate/src/page/mod.rs
  iml-gui/crate/src/page/target.rs
Labels: enhancement

#1655 Fixup wasm-pack install
  .github/workflows/iml-gui.yml
  docker/iml-gui.dockerfile
Labels: bug

#1656 Fix grafana iframe src
  iml-gui/crate/src/components/grafana_chart.rs
Labels: bug

#1657 Detect tty for iml proxy cli
  docker/iml-cli-proxy.sh
Labels: enhancement

#1658 Fix NaN case in progress circle
  iml-gui/crate/src/components/progress_circle.rs
Labels: bug

#1659 Ensure help links aren't handled by internal routing
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/status_section.rs
Labels: bug

#1662 Calculate relative time using server time
  iml-gui/crate/src/auth.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/activity.rs
  iml-gui/crate/src/page/servers.rs
  iml-gui/crate/src/server_date.rs
  iml-gui/crate/src/status_section.rs
Labels: bug

#1665 Add connected clients to influx
  Cargo.lock
  iml-agent/Cargo.toml
  iml-fs/Cargo.toml
  iml-mailbox/Cargo.toml
  iml-manager-cli/Cargo.toml
  iml-services/iml-action-runner/Cargo.toml
  iml-services/iml-ostpool/Cargo.toml
  iml-services/iml-postoffice/Cargo.toml
  iml-services/iml-stats/Cargo.toml
  iml-services/iml-stats/src/main.rs
  iml-wasm-components/Cargo.lock
  iml-wasm-components/iml-action-dropdown/Cargo.toml
  iml-wasm-components/iml-duration-picker/Cargo.toml
  iml-wasm-components/iml-environment/Cargo.toml
  iml-wasm-components/iml-fs/Cargo.toml
  iml-wasm-components/iml-sleep/Cargo.toml
  iml-wasm-components/iml-toggle/Cargo.toml
  iml-wasm-components/iml-tooltip/Cargo.toml
  iml-wasm-components/iml-utils/Cargo.toml
Labels: enhancement

#1670 Make grafana graphs "kiosk" mode
  iml-gui/crate/src/components/grafana_chart.rs
Labels: bug

#1671 Implement logs sidebar
  Cargo.lock
  iml-gui/crate/Cargo.lock
  iml-gui/crate/src/components/resource_links.rs
  iml-gui/crate/src/ctx_help.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/activity.rs
  iml-gui/crate/src/page/logs.rs
  iml-gui/crate/src/page/mod.rs
  iml-gui/crate/src/route.rs
  iml-gui/crate/src/status_section.rs
  iml-gui/package.json
  iml-gui/yarn.lock
  iml-wasm-components/Cargo.lock
  iml-wire-types/Cargo.toml
  iml-wire-types/src/lib.rs
Labels: enhancement

#1674 influx: Disable HTTP logging
  chroma_core/lib/service_config.py
  docker/docker-compose.yml
Labels: enhancement

#1676 Add filesystem name to some influx stats
  iml-services/iml-stats/Cargo.toml
  iml-services/iml-stats/src/main.rs
Labels: enhancement

#1677 Implement first pass of users page
  Cargo.lock
  chroma_core/migrations/0011_auth_json_notify.py
  iml-gui/crate/src/components/resource_links.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/page/users.rs
  iml-gui/crate/src/test_utils/fixtures.rs
  iml-services/iml-stats/src/main.rs
  iml-warp-drive/src/cache.rs
  iml-warp-drive/src/db_record.rs
  iml-wire-types/src/db.rs
  iml-wire-types/src/warp_drive.rs
Labels: enhancement

#1495 Create Vagrant test framework
  Cargo.lock
  Cargo.toml
  iml-system-tests/Cargo.lock
  iml-system-tests/Cargo.toml
  iml-system-tests/tests/integration_test.rs
  iml-system-tests/tests/vagrant.rs
Labels: enhancement

#1684 Server detail
  Cargo.lock
  Cargo.toml
  chroma_core/migrations/0012_ha_json_notify.py
  iml-api-utils/Cargo.toml
  iml-api-utils/src/lib.rs
  iml-gui/crate/Cargo.lock
  iml-gui/crate/Cargo.toml
  iml-gui/crate/src/components/resource_links.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/mgts.rs
  iml-gui/crate/src/page/mod.rs
  iml-gui/crate/src/page/server.rs
  iml-gui/crate/src/page/servers.rs
  iml-gui/crate/src/page/target.rs
  iml-gui/crate/src/test_utils/fixtures.rs
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/ostpool.rs
  iml-manager-cli/src/server.rs
  iml-warp-drive/src/cache.rs
  iml-warp-drive/src/db_record.rs
  iml-wasm-components/Cargo.lock
  iml-wire-types/Cargo.toml
  iml-wire-types/src/db.rs
  iml-wire-types/src/lib.rs
  iml-wire-types/src/warp_drive.rs
Labels: enhancement

#1654 Implement stratagem config box
  chroma-manager.conf.template
  chroma_core/lib/service_config.py
  docker/setup-nginx
  iml-gui/crate/src/components/duration_picker.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/components/modal.rs
  iml-gui/crate/src/components/stratagem/delete_stratagem_button.rs
  iml-gui/crate/src/components/stratagem/enable_stratagem_button.rs
  iml-gui/crate/src/components/stratagem/inode_table.rs
  iml-gui/crate/src/components/stratagem/mod.rs
  iml-gui/crate/src/components/stratagem/scan_stratagem_button.rs
  iml-gui/crate/src/components/stratagem/scan_stratagem_modal.rs
  iml-gui/crate/src/components/stratagem/update_stratagem_button.rs
  iml-gui/crate/src/components/stratagem/validation.rs
  iml-gui/crate/src/components/tooltip.rs
  iml-gui/crate/src/environment.rs
  iml-gui/crate/src/generated/css_classes.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/page/mod.rs
  settings.py
Labels: enhancement

#1686 Implement volumes page
  iml-gui/crate/src/components/table.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/about.rs
  iml-gui/crate/src/page/jobstats.rs
  iml-gui/crate/src/page/mod.rs
  iml-gui/crate/src/page/ostpool.rs
  iml-gui/crate/src/page/ostpools.rs
  iml-gui/crate/src/page/power_control.rs
  iml-gui/crate/src/page/server_dashboard.rs
  iml-gui/crate/src/page/servers.rs
  iml-gui/crate/src/page/target_dashboard.rs
  iml-gui/crate/src/page/targets.rs
  iml-gui/crate/src/page/users.rs
  iml-gui/crate/src/page/volume.rs
  iml-gui/crate/src/page/volumes.rs
  iml-warp-drive/src/cache.rs
  iml-wire-types/src/db.rs
  iml-wire-types/src/warp_drive.rs
Labels: enhancement

#1689 fix black formatting
  chroma_api/user.py
Labels: bug

#1690 Allow anonymous Auth
  chroma-manager.conf.template
  chroma_api/session.py
  chroma_api/urls.py
Labels: enhancement

#1687 Api config
  chroma_core/management/commands/print-settings.py
  iml-api/src/main.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/page/login.rs
  iml-gui/crate/src/page/partial/header.rs
  iml-manager-env/src/lib.rs
  iml-wire-types/src/lib.rs
  settings.py
Labels: enhancement

#1693 Remove volume links and other tree-view links that do not need to be shown
  iml-gui/crate/src/components/resource_links.rs
  iml-gui/crate/src/components/tree.rs
  iml-gui/crate/src/page/volumes.rs
Labels: enhancement

#1695 Add pagination to activity viewer
  iml-gui/crate/src/components/paging.rs
  iml-gui/crate/src/extensions.rs
  iml-gui/crate/src/page/activity.rs
  iml-gui/crate/src/page/logs.rs
Labels: enhancement

#1694 Get filesystem stats from influxdb
  iml-gui/crate/src/components/chart/fs_usage.rs
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/page/filesystems.rs
  iml-gui/crate/src/page/fs_dashboard.rs
  iml-gui/crate/src/page/mod.rs
Labels: enhancement

#1697 Replace "N/A" with "---"
  iml-gui/crate/src/components/resource_links.rs
  iml-gui/crate/src/components/stratagem/inode_table.rs
  iml-gui/crate/src/components/stratagem/mod.rs
Labels: chore

#1698 Have nginx pass proxied gzip data from grafana and influx
  chroma-manager.conf.template
  grafana/grafana-iml.ini
Labels: enhancement

#1699 Remove outdated video
  README.md
  media/iml_overview_title_and_play.png
Labels: chore

#1701 Add reboot for non iml lustre installs
  vagrant/Vagrantfile
Labels: enhancement

#1696 Update stats to utilize batch writes
  Cargo.lock
  grafana/dashboards/iml-metrics.json
  iml-gui/crate/src/components/chart/fs_usage.rs
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/page/filesystems.rs
  iml-services/iml-stats/Cargo.toml
  iml-services/iml-stats/src/error.rs
  iml-services/iml-stats/src/main.rs
Labels: enhancement

#1666 Command modal v1
  iml-gui/configs/tailwind.config.js
  iml-gui/crate/src/auth.rs
  iml-gui/crate/src/components/action_dropdown/confirm_action_modal.rs
  iml-gui/crate/src/components/action_dropdown/mod.rs
  iml-gui/crate/src/components/chart/fs_usage.rs
  iml-gui/crate/src/components/command_modal.rs
  iml-gui/crate/src/components/dropdown.rs
  iml-gui/crate/src/components/duration_picker.rs
  iml-gui/crate/src/components/mod.rs
  iml-gui/crate/src/components/modal.rs
  iml-gui/crate/src/components/paging.rs
  iml-gui/crate/src/components/stratagem/inode_table.rs
  iml-gui/crate/src/components/stratagem/mod.rs
  iml-gui/crate/src/components/stratagem/scan_stratagem_button.rs
  iml-gui/crate/src/components/stratagem/scan_stratagem_modal.rs
  iml-gui/crate/src/components/table.rs
  iml-gui/crate/src/components/toast.rs
  iml-gui/crate/src/components/tree.rs
  iml-gui/crate/src/generated/css_classes.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/notification.rs
  iml-gui/crate/src/page/about.rs
  iml-gui/crate/src/page/activity.rs
  iml-gui/crate/src/page/dashboard.rs
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/page/filesystems.rs
  iml-gui/crate/src/page/fs_dashboard.rs
  iml-gui/crate/src/page/jobstats.rs
  iml-gui/crate/src/page/login.rs
  iml-gui/crate/src/page/logs.rs
  iml-gui/crate/src/page/mgts.rs
  iml-gui/crate/src/page/mod.rs
  iml-gui/crate/src/page/ostpool.rs
  iml-gui/crate/src/page/ostpools.rs
  iml-gui/crate/src/page/power_control.rs
  iml-gui/crate/src/page/server.rs
  iml-gui/crate/src/page/server_dashboard.rs
  iml-gui/crate/src/page/servers.rs
  iml-gui/crate/src/page/target.rs
  iml-gui/crate/src/page/target_dashboard.rs
  iml-gui/crate/src/page/targets.rs
  iml-gui/crate/src/page/user.rs
  iml-gui/crate/src/page/users.rs
  iml-gui/crate/src/page/volume.rs
  iml-gui/crate/src/page/volumes.rs
  iml-gui/crate/src/status_section.rs
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/server.rs
  iml-manager-cli/src/stratagem.rs
  iml-wire-types/src/lib.rs
  iml-wire-types/src/warp_drive.rs
Labels: enhancement

#1704 Update functionality of date picker on charts
  iml-gui/crate/Cargo.lock
  iml-gui/crate/Cargo.toml
  iml-gui/crate/src/components/dashboard/mod.rs
  iml-gui/crate/src/components/datepicker.rs
  iml-gui/crate/src/components/grafana_chart.rs
  iml-gui/crate/src/components/stratagem/mod.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/dashboard.rs
  iml-gui/crate/src/page/fs_dashboard.rs
  iml-gui/crate/src/page/mod.rs
  iml-gui/crate/src/page/target_dashboard.rs
Labels: enhancement

#1703 Add `fs` tag to Target and BrwStats records
  iml-services/iml-stats/src/main.rs
Labels: enhancement

#1709 Address immediate GUI visual bugs
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/status_section.rs
Labels: bug

#1707 Show page details in title and in breadcrumbs
  iml-gui/crate/src/components/breadcrumbs.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/mod.rs
  iml-gui/crate/src/page/partial/header.rs
  iml-gui/crate/src/route.rs
Labels: enhancement

#1711 Add baseless profile
  Cargo.lock
  agent-bootstrap-script.template
  default_baseless.profile
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/error.rs
  iml-manager-cli/src/filesystem.rs
  iml-manager-cli/src/ostpool.rs
  iml-manager-cli/src/server.rs
  iml-manager-cli/src/update_repo_file.rs
  iml-warp-drive/src/cache.rs
  iml-warp-drive/src/main.rs
Labels: bug

#1714 Update profile should not deal with rpms
  chroma_core/models/host.py
Labels: bug

#1718 Fix host await
  chroma_core/models/host.py
Labels: bug

#1717 Remove unused imports
  iml-gui/crate/src/extensions.rs
  iml-wire-types/src/lib.rs
Labels: chore

#1721 wait_for_cmds fn does not return final command
  iml-manager-cli/src/api_utils.rs
  iml-manager-cli/src/filesystem.rs
  iml-manager-cli/src/ostpool.rs
  iml-manager-cli/src/server.rs
  iml-manager-cli/src/update_repo_file.rs
Labels: bug

#1713 Add route to show per-host volumes
  iml-gui/crate/src/components/tree.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/mod.rs
  iml-gui/crate/src/page/volumes.rs
  iml-gui/crate/src/route.rs
Labels: enhancement

#1724 Failed Preflight checks should print details
  iml-manager-cli/src/server.rs
Labels: enhancement

#1727 Fix warp drive hanging
  iml-warp-drive/Cargo.toml
  iml-warp-drive/src/cache.rs
Labels: bug

#1730 Always generate identity.pfx on rust agent startup
  iml-agent/src/env.rs
Labels: bug

#1733 Add charset
  iml-gui/entries/index.hbs
Labels: bug

#1744 Allow NTP to use the `stratagem_existing_client`
  chroma_api/stratagem.py
  chroma_core/models/stratagem.py
  chroma_core/services/job_scheduler/job_scheduler.py
Labels: enhancement

#1747 Change `MGTs` to `MDTs` on filesystem page
  iml-gui/crate/src/page/filesystem.rs
Labels: bug

#1745 Scan LVs in detect_scan to find failover peers
  chroma_core/lib/detection.py
  tests/unit/services/job_scheduler/test_detection.py
Labels: enhancement

#1749 Bump deps
  Cargo.lock
  docker/docker-compose.yml
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/high_availability/snapshots/iml_agent__action_plugins__high_availability__corosync_conf__tests__corosync_cmapctl_output.snap
  iml-agent/src/action_plugins/high_availability/snapshots/iml_agent__action_plugins__high_availability__corosync_conf__tests__update_config_version.snap
  iml-agent/src/action_plugins/high_availability/snapshots/iml_agent__action_plugins__high_availability__corosync_conf__tests__update_mcast_port.snap
  iml-agent/src/action_plugins/ntp/snapshots/iml_agent__action_plugins__ntp__action_configure__test__configure_ntp_with_modified_config.snap
  iml-agent/src/action_plugins/ntp/snapshots/iml_agent__action_plugins__ntp__action_configure__test__configure_ntp_with_no_server_specified.snap
  iml-agent/src/action_plugins/ntp/snapshots/iml_agent__action_plugins__ntp__action_configure__test__configure_ntp_with_server_as_adm.snap
  iml-agent/src/action_plugins/ntp/snapshots/iml_agent__action_plugins__ntp__action_configure__test__configure_ntp_with_server_as_localhost.snap
  iml-agent/src/action_plugins/ntp/snapshots/iml_agent__action_plugins__ntp__action_configure__test__reset_config_with_local_server_markers.snap
  iml-agent/src/action_plugins/ntp/snapshots/iml_agent__action_plugins__ntp__action_configure__test__reset_config_with_no_server_markers.snap
  iml-agent/src/action_plugins/ntp/snapshots/iml_agent__action_plugins__ntp__action_configure__test__reset_config_with_server_markers.snap
  iml-agent/src/action_plugins/ntp/snapshots/test__configure_ntp_with_no_server_specified.snap
  iml-agent/src/action_plugins/snapshots/iml_agent__action_plugins__lamigo__lamigo_tests__works.snap
  iml-agent/src/action_plugins/snapshots/iml_agent__action_plugins__lpurge__lpurge_conf_tests__works.snap
  iml-gui/crate/Cargo.lock
  iml-manager-cli/Cargo.toml
  iml-rabbit/Cargo.toml
  iml-rabbit/src/lib.rs
Labels: chore
