Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2020-12, with the labels that each got.

#2407 Update client.rs
  iml-agent/src/action_plugins/lustre/client.rs
Labels: bug

#2405 agent: Fix clippy warnings
  iml-agent/src/cli.rs
  iml-agent/src/daemon_plugins/snapshot.rs
Labels: chore

#2409 Add precommit with rusty-hook
  .rusty-hook.toml
  README.md
Labels: enhancement

#2410 Add iml-ssh crate
  .gitignore
  Cargo.lock
  Cargo.toml
  iml-fs/src/lib.rs
  iml-ssh/Cargo.toml
  iml-ssh/src/lib.rs
Labels: enhancement

#2382 Add rust rpm provisioner to adm node
  vagrant/Vagrantfile
  vagrant/scripts/build_rust_rpms.sh
Labels: chore

#2412 Switch to using the journald driver for docker logging
  docker/docker-compose.yml
Labels: enhancement

#2413 Remove configure-docker-network-trigger
  vagrant/Vagrantfile
Labels: bug

#2414 Always use adm node as ntp server
  iml-system-docker-tests/tests/ldiskfs_test.rs
  iml-system-docker-tests/tests/stratagem_test.rs
  iml-system-docker-tests/tests/zfs_test.rs
  iml-system-test-utils/src/lib.rs
  iml-system-test-utils/src/ssh.rs
  vagrant/Vagrantfile
  vagrant/scripts/install_iml_docker_local.sh
  vagrant/scripts/install_iml_docker_repouri.sh
  vagrant/scripts/install_ntp.sh
Labels: bug

#2388 Add writing out of config
  .copr/Makefile
  docker/copy-embedded-settings
  docker/iml-cli-proxy.sh
  iml-docker.service
  iml-docker.spec
  iml-system-test-utils/src/lib.rs
  vagrant/Vagrantfile
Labels: enhancement

#2398 Remove CLI docker bits
  docker/docker-compose.yml
  docker/iml-manager-cli.dockerfile
Labels: enhancement

#2420 Include MGS fs info with devices
  Cargo.lock
  iml-agent/src/daemon_plugins/device.rs
  iml-agent/src/daemon_plugins/stats.rs
  iml-services/iml-device/Cargo.toml
  iml-services/iml-device/src/error.rs
  iml-services/iml-device/src/lib.rs
  iml-services/iml-device/src/main.rs
  iml-services/iml-stats/src/main.rs
Labels: bug

#2408 Handle Resource Bans on Filesystem Detail Page
  iml-api/src/graphql/filesystem.rs
  iml-api/src/graphql/mod.rs
  iml-gui/crate/src/lib.rs
  iml-gui/crate/src/page/filesystem.rs
  iml-gui/crate/src/test_utils/fixture.json
  iml-services/iml-corosync/src/lib.rs
  iml-warp-drive/src/cache.rs
  iml-warp-drive/src/db_record.rs
  iml-wire-types/src/db.rs
  iml-wire-types/src/warp_drive.rs
  migrations/20201201204247_corosync_resource_ban.sql
  migrations/20201204185824_corosync_listen_notify.sql
  sqlx-data.json
Labels: enhancement

#2422 Bump sqlx to latest
  .github/workflows/rust-ci.yml
  Cargo.lock
  README.md
  iml-postgres/Cargo.toml
  iml-services/iml-journal/Cargo.toml
  iml-services/iml-journal/src/main.rs
  iml-wire-types/Cargo.toml
  tests/framework/services/runner.sh.in
Labels: chore

#2423 Use cursor pointer on the Management menu
  iml-gui/crate/src/page/partial/header.rs
Labels: enhancement

#2424 Silence python http agent logging
  chroma_core/services/http_agent/__init__.py
Labels: enhancement

#2426 Use kill_on_drop for all agent commands
  iml-agent/src/action_plugins/check_kernel.rs
  iml-agent/src/action_plugins/check_stonith.rs
  iml-agent/src/action_plugins/firewall_cmd.rs
  iml-agent/src/action_plugins/high_availability/corosync_conf.rs
  iml-agent/src/action_plugins/high_availability/mod.rs
  iml-agent/src/action_plugins/kernel_module.rs
  iml-agent/src/action_plugins/lustre/client.rs
  iml-agent/src/action_plugins/stratagem/action_cloudsync.rs
  iml-agent/src/action_plugins/stratagem/action_filesync.rs
  iml-agent/src/action_plugins/stratagem/action_mirror.rs
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/daemon_plugins/device.rs
  iml-agent/src/daemon_plugins/ntp.rs
  iml-agent/src/daemon_plugins/stats.rs
  iml-agent/src/high_availability.rs
  iml-agent/src/lustre.rs
  iml-agent/src/network_interfaces.rs
  iml-agent/src/rpm.rs
Labels: bug

#2433 Ensure iml-docker starts after multi-user.target
  iml-docker.service
Labels: bug

#2431 Switch all systemctl preset to systemd_post
  device-scanner/iml-device-scanner.spec
  iml-docker.spec
  rust-iml.spec
Labels: bug

#2430 Support combined MGS / MDT
  iml-api/src/graphql/filesystem.rs
  iml-services/iml-device/src/lib.rs
  iml-services/iml-device/src/main.rs
  migrations/20201209221117_update_target_unique.sql
  sqlx-data.json
Labels: bug

#2436 Action plugin execution blocks daemon plugins
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/daemon_plugins/action_runner.rs
  iml-agent/src/daemon_plugins/corosync.rs
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/daemon_plugins/device.rs
  iml-agent/src/daemon_plugins/journal.rs
  iml-agent/src/daemon_plugins/network.rs
  iml-agent/src/daemon_plugins/ntp.rs
  iml-agent/src/daemon_plugins/ostpool.rs
  iml-agent/src/daemon_plugins/postoffice.rs
  iml-agent/src/daemon_plugins/snapshot.rs
  iml-agent/src/daemon_plugins/stats.rs
  iml-agent/src/http_comms/session.rs
Labels: bug

#2434 Bump to 6.3
  .github/workflows/prod-release.yml
  .travis.yml
  device-scanner/iml-device-scanner.spec
  docker/compose-deps.hcl
  docker/corosync.dockerfile
  docker/docker-compose.yml
  docker/gunicorn.dockerfile
  docker/http-agent.dockerfile
  docker/iml-action-runner.dockerfile
  docker/iml-agent-comms.dockerfile
  docker/iml-api.dockerfile
  docker/iml-corosync.dockerfile
  docker/iml-device.dockerfile
  docker/iml-mailbox.dockerfile
  docker/iml-network.dockerfile
  docker/iml-ntp.dockerfile
  docker/iml-ostpool.dockerfile
  docker/iml-postoffice.dockerfile
  docker/iml-report.dockerfile
  docker/iml-sfa.dockerfile
  docker/iml-snapshot.dockerfile
  docker/iml-stats.dockerfile
  docker/iml-task-runner.dockerfile
  docker/iml-timer.dockerfile
  docker/iml-warp-drive.dockerfile
  docker/job-scheduler.dockerfile
  docker/journal.dockerfile
  docker/lustre-audit.dockerfile
  docker/plugin-runner.dockerfile
  docker/power-control.dockerfile
  docker/setup.dockerfile
  iml-docker.spec
  iml-gui/rust-iml-gui.spec
  python-iml-manager.spec
  rust-iml.spec
  setup.py
  vagrant/Vagrantfile
Labels: chore

#2367 EX-1979 filesync restore
  Cargo.lock
  iml-agent/src/action_plugins/stratagem/action_cloudsync.rs
  iml-agent/src/action_plugins/stratagem/action_filesync.rs
  iml-agent/src/cli.rs
  iml-api/src/graphql/mod.rs
  iml-api/src/graphql/stratagem.rs
  iml-graphql-queries/src/stratagem.rs
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/stratagem.rs
  liblustreapi/src/lib.rs
  sqlx-data.json
Labels: enhancement

#2448 Fixup copy-embedded-settings
  docker/copy-embedded-settings
Labels: bug
