Repository whamcloud/integrated-manager-for-lustre, pull requests merged in 2020-08, with the labels that each got.

#2128 Move ActionType to iml_wire_types
  Cargo.lock
  iml-action-client/Cargo.toml
  iml-action-client/src/lib.rs
  iml-services/iml-action-runner/src/lib.rs
  iml-services/iml-action-runner/src/sender.rs
  iml-services/iml-action-runner/tests/action_runner_tests.rs
  iml-wire-types/src/lib.rs
Labels: chore

#2124 Use a single lustre install step
  Makefile
  iml-system-docker-tests/Cargo.lock
  iml-system-rpm-tests/Cargo.lock
  iml-system-test-utils/README.md
  iml-system-test-utils/src/lib.rs
  iml-system-test-utils/src/snapshots.rs
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_ldiskfs_test_path_from_graph.snap
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_stratagem_test_path_from_graph.snap
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_zfs_test_path_from_graph.snap
  iml-system-test-utils/src/ssh.rs
  vagrant/scripts/install_ldiskfs_zfs_no_iml.sh
Labels: enhancement, integration-tests

#2122 action-client: Add invoke_rust_agent
  Cargo.lock
  iml-action-client/Cargo.toml
  iml-action-client/src/lib.rs
  iml-manager-env/src/lib.rs
Labels: enhancement

#2123 Extract remote_action code from sender
  iml-services/iml-action-runner/src/lib.rs
  iml-services/iml-action-runner/src/remote_action.rs
  iml-services/iml-action-runner/src/sender.rs
Labels: enhancement

#2130 Tests: Unify iml-configured graph node
  iml-system-test-utils/src/snapshots.rs
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_ldiskfs_test_path_from_graph.snap
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_stratagem_test_path_from_graph.snap
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_zfs_test_path_from_graph.snap
Labels: enhancement

#2131 Fix cargo formatting of system tests
  iml-system-docker-tests/tests/ldiskfs_test.rs
  iml-system-docker-tests/tests/zfs_test.rs
  iml-system-rpm-tests/tests/ldiskfs_test.rs
  iml-system-rpm-tests/tests/zfs_test.rs
Labels: chore

#2115 Switch the iml-rabbit to rustls
  Cargo.lock
  iml-rabbit/Cargo.toml
Labels: enhancement

#2047 Add FS name constraint
  .github/workflows/rust-ci.yml
  .travis.yml
  chroma_core/lib/service_config.py
  chroma_core/migrations/0022_fs_name_uniqueness.py
  docker/docker-compose.yml
  docker/postgres.dockerfile
  docker/postgres/enable_btree_gist.sh
  python-iml-manager.spec
  tests/framework/services/runner.sh.in
Labels: bug

#2133 Remove ObjectCache from ClientMount
  chroma_core/lib/cache.py
  chroma_core/models/client_mount.py
Labels: bug

#2121 Implement Mount Step
  chroma_core/models/host.py
Labels: enhancement

#2138 Fix firefox tests
  .github/workflows/iml-gui.yml
  iml-gui/crate/Cargo.lock
Labels: chore

#2132 Add 'iml debugapi' to iml cli
  iml-manager-cli/src/api.rs
  iml-manager-cli/src/lib.rs
  iml-manager-cli/src/main.rs
  iml-manager-client/src/lib.rs
Labels: integration-tests

#2143 Quote arguments passed into docker iml
  docker/iml-cli-proxy.sh
Labels: chore

#2141 Allow local actions to make db calls
  Cargo.lock
  iml-orm/README.md
  iml-services/iml-action-runner/Cargo.toml
  iml-services/iml-action-runner/src/db.rs
  iml-services/iml-action-runner/src/error.rs
  iml-services/iml-action-runner/src/lib.rs
  iml-services/iml-action-runner/src/local_actions.rs
  iml-services/iml-action-runner/src/main.rs
  iml-services/iml-action-runner/src/sender.rs
  iml-services/iml-action-runner/tests/integration_tests.rs
  iml-wire-types/src/lib.rs
  sqlx-data.json
Labels: enhancement

#2140 Implement Create/Destroy SnapshotStep
  chroma_core/models/host.py
Labels: enhancement

#2145 Implement listing snapshots
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/action_plugins/lustre/snapshot.rs
  iml-agent/src/action_plugins/lustre/snapshot/parse.rs
  iml-agent/src/agent_error.rs
  iml-agent/src/cli.rs
  iml-wire-types/src/snapshot.rs
Labels: enhancement

#1919 Allow for management of existing resources
  base_monitored.profile
Labels: bug

#2148 Fixup client mounts
  chroma_api/stratagem.py
  chroma_core/models/client_mount.py
  iml-agent/src/action_plugins/lustre/client.rs
Labels: bug

#2149 debuapi: Optionally read from stdin for Body
  iml-manager-cli/src/api.rs
Labels: enhancement

#2150 Task mailbox
  .copr/Makefile
  Cargo.lock
  Cargo.toml
  chroma-manager.conf.template
  chroma_core/management/commands/print-settings.py
  chroma_core/migrations/0023_remove_stratagem_client_job.py
  chroma_core/models/stratagem.py
  chroma_core/models/task.py
  chroma_core/services/job_scheduler/job_scheduler.py
  docker/docker-compose.yml
  docker/iml-mailbox.dockerfile
  docker/iml-task-runner.dockerfile
  docker/setup-nginx
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/stratagem/action_purge.rs
  iml-agent/src/action_plugins/stratagem/action_warning.rs
  iml-agent/src/action_plugins/stratagem/server.rs
  iml-agent/src/cli.rs
  iml-api/src/command.rs
  iml-fs/src/lib.rs
  iml-mailbox.conf
  iml-mailbox/Cargo.toml
  iml-mailbox/src/lib.rs
  iml-mailbox/src/main.rs
  iml-manager-cli/src/nginx.rs
  iml-manager-cli/src/snapshots/iml_manager_cli__nginx__tests__replace_template_variables.snap
  iml-manager-env/src/lib.rs
  iml-manager.target
  iml-orm/src/clientmount.rs
  iml-orm/src/fidtaskqueue.rs
  iml-orm/src/filesystem.rs
  iml-orm/src/hosts.rs
  iml-orm/src/job.rs
  iml-orm/src/lib.rs
  iml-orm/src/lustrefid.rs
  iml-orm/src/task.rs
  iml-postgres/src/lib.rs
  iml-system-test-utils/src/lib.rs
  iml-system-test-utils/src/snapshots.rs
  iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_stratagem_test_path_from_graph.snap
  iml-system-test-utils/src/ssh.rs
  iml-task-runner.service
  iml-task-runner/Cargo.toml
  iml-task-runner/README.md
  iml-task-runner/src/error.rs
  iml-task-runner/src/main.rs
  iml-wire-types/Cargo.toml
  iml-wire-types/src/db.rs
  iml-wire-types/src/lib.rs
  python-iml-manager.spec
  rust-iml.spec
  settings.py
  sqlx-data.json
  vagrant/scripts/install_iml_local.sh
Labels: enhancement

#2158 Make db pool size configurable
  Cargo.lock
  iml-api/src/main.rs
  iml-mailbox/Cargo.toml
  iml-mailbox/src/main.rs
  iml-manager-env/src/lib.rs
  iml-services/iml-action-runner/src/main.rs
  iml-services/iml-device/src/main.rs
  iml-services/iml-journal/src/main.rs
  iml-services/iml-ntp/Cargo.toml
  iml-services/iml-ntp/src/main.rs
  iml-task-runner/Cargo.toml
  iml-task-runner/src/main.rs
  sqlx-data.json
Labels: enhancement

#2159 Add snapshot Create/Destroy jobs
  chroma_core/migrations/0025_createsnapshotjob_destroysnapshotjob.py
  chroma_core/models/host.py
  chroma_help/help.py
Labels: enhancement

#2156 Implement MountSnapshotJob / UnmountSnapshotJob
  chroma_core/migrations/0024_mountsnapshotjob_unmountsnapshotjob.py
  chroma_core/migrations/0025_createsnapshotjob_destroysnapshotjob.py
  chroma_core/models/host.py
  chroma_help/help.py
Labels: enhancement

#2164 Add a bunch of debug to the task-runner.
  iml-task-runner/src/main.rs
  iml-wire-types/src/lib.rs
Labels: enhancement

#2162 Switch iml-orm to sqlx in iml-cli
  Cargo.lock
  Makefile
  iml-manager-cli/Cargo.toml
  iml-manager-cli/src/error.rs
  iml-manager-cli/src/profile.rs
  iml-orm/src/lib.rs
  iml-orm/src/profile.rs
  iml-orm/src/repo.rs
  sqlx-data.json
Labels: chore

#2165 Don't use try_acquire alongside spawned task
  iml-task-runner/src/main.rs
Labels: bug

#2163 Implement the Device enum:
  Cargo.lock
  device-scanner/Cargo.lock
  device-scanner/device-scanner-daemon/Cargo.toml
  device-scanner/device-scanner-zedlets/Cargo.toml
  device-scanner/device-types/Cargo.toml
  device-scanner/device-types/src/devices.rs
  device-scanner/mount-emitter/Cargo.toml
  device-scanner/uevent-listener/Cargo.toml
  device-scanner/zed-enhancer/Cargo.toml
Labels: enhancement

#2166 Add ops to ResourceAgentType
  iml-agent/src/action_plugins/high_availability/mod.rs
  iml-wire-types/src/lib.rs
Labels: enhancement

#2169 Fix missing space in fstab client mount
  iml-agent/src/action_plugins/lustre/client.rs
Labels: bug

#2153 Add Mirror actions for HPv2
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/stratagem/action_mirror.rs
  iml-agent/src/action_plugins/stratagem/action_purge.rs
  iml-agent/src/action_plugins/stratagem/action_warning.rs
  iml-agent/src/action_plugins/stratagem/mod.rs
  iml-agent/src/action_plugins/stratagem/util.rs
  iml-agent/src/agent_error.rs
Labels: enhancement

#2170 Ensure empty snapshots do not produce parse error
  iml-agent/src/action_plugins/lustre/snapshot.rs
Labels: bug

#2171 Introduce iml-change crate
  Cargo.lock
  Cargo.toml
  iml-change/Cargo.toml
  iml-change/README.md
  iml-change/src/lib.rs
Labels: enhancement

#2107 Build up targets from device-scanner output
  .github/workflows/rust-ci.yml
  Cargo.lock
  device-scanner/Cargo.lock
  device-scanner/device-types/Cargo.toml
  device-scanner/device-types/src/lib.rs
  iml-agent/Cargo.toml
  iml-change/src/lib.rs
  iml-postgres/Cargo.toml
  iml-services/iml-device/Cargo.toml
  iml-services/iml-device/fixtures/devtrees.json
  iml-services/iml-device/sqlx-data.json
  iml-services/iml-device/src/error.rs
  iml-services/iml-device/src/lib.rs
  iml-services/iml-device/src/main.rs
  iml-services/iml-device/src/snapshots/iml_device__tests__deletions_only.snap
  iml-services/iml-device/src/snapshots/iml_device__tests__index.snap
  iml-services/iml-device/src/snapshots/iml_device__tests__upserts_and_deletions.snap
  iml-services/iml-device/src/snapshots/iml_device__tests__upserts_only.snap
  iml-services/iml-stats/Cargo.toml
  migrations/20200728203410_devices.sql
  sqlx-data.json
Labels: enhancement

#2179 Ignore .env
  vagrant/Vagrantfile
Labels: bug

#2180 Forward Postgres port
  vagrant/Vagrantfile
Labels: chore

#2183 Fix docker-compose.yml
  docker/docker-compose.yml
Labels: bug

#2182 Implement a crm_mon XML reader
  .gitignore
  Cargo.lock
  iml-agent/Cargo.toml
  iml-agent/src/agent_error.rs
  iml-agent/src/crm_reader.rs
  iml-agent/src/fixtures/es_fixture.xml
  iml-agent/src/lib.rs
  iml-agent/src/lustre.rs
  iml-agent/src/snapshots/iml_agent__crm_reader__tests__read_es.snap
  iml-wire-types/src/high_availability.rs
  iml-wire-types/src/lib.rs
Labels: enhancement

#2185 Fix migration help text
  chroma_core/migrations/0025_createsnapshotjob_destroysnapshotjob.py
Labels: bug

#2184 Add corosync daemon plugin to Rust
  .copr/Makefile
  Cargo.lock
  Cargo.toml
  Makefile
  docker/docker-compose.yml
  docker/iml-corosync.dockerfile
  iml-agent/src/daemon_plugins/corosync.rs
  iml-agent/src/daemon_plugins/daemon_plugin.rs
  iml-agent/src/daemon_plugins/mod.rs
  iml-manager.target
  iml-rust-corosync.service
  iml-services/iml-corosync/Cargo.toml
  iml-services/iml-corosync/src/main.rs
  iml-wire-types/src/high_availability.rs
  migrations/20200824170157_corosync_node.sql
  python-iml-manager.spec
  rust-iml.spec
  sqlx-data.json
  vagrant/scripts/install_iml_local.sh
Labels: enhancement

#2147 Add mgs fs to stats service
  Cargo.lock
  chroma_core/management/commands/print-settings.py
  docker/docker-compose.yml
  iml-agent/Cargo.toml
  iml-agent/src/daemon_plugins/stats.rs
  iml-manager-env/src/lib.rs
  iml-services/iml-device/Cargo.toml
  iml-services/iml-device/src/error.rs
  iml-services/iml-device/src/lib.rs
  iml-services/iml-device/src/main.rs
  iml-services/iml-device/src/snapshots/iml_device__tests__deletions_only.snap
  iml-services/iml-device/src/snapshots/iml_device__tests__upserts_and_deletions.snap
  iml-services/iml-device/src/snapshots/iml_device__tests__upserts_only.snap
  iml-services/iml-stats/Cargo.toml
  iml-services/iml-stats/src/main.rs
  migrations/20200728203410_devices.sql
  sqlx-data.json
Labels: enhancement

#2186 Graphql
  Cargo.lock
  chroma-manager.conf.template
  iml-api/Cargo.toml
  iml-api/src/graphql.rs
  iml-api/src/main.rs
  iml-api/src/task.rs
  iml-manager-cli/src/snapshots/iml_manager_cli__nginx__tests__replace_template_variables.snap
  sqlx-data.json
Labels: enhancement

#2181 agent: Remove duplicate function
  iml-agent/src/action_plugins/stratagem/action_mirror.rs
  iml-agent/src/action_plugins/stratagem/action_purge.rs
  iml-agent/src/action_plugins/stratagem/action_warning.rs
  iml-agent/src/action_plugins/stratagem/mod.rs
  iml-agent/src/action_plugins/stratagem/util.rs
  iml-agent/src/lustre.rs
Labels: bug

#2188 Add a graphql endpoint to list targets
  .travis.yml
  iml-api/src/graphql.rs
  sqlx-data.json
Labels: enhancement

#2193 Support Rust 1.46
  .github/workflows/iml-gui.yml
  Cargo.lock
  docker/iml-gui.dockerfile
  iml-agent/src/action_plugins/lustre/client.rs
  iml-agent/src/action_plugins/stratagem/action_warning.rs
  iml-agent/src/crm_reader.rs
  iml-agent/src/daemon_plugins/corosync.rs
  iml-gui/crate/Cargo.lock
  iml-gui/crate/src/components/sfa_overview/mod.rs
  iml-mailbox/src/lib.rs
  iml-manager-cli/src/api.rs
  iml-rabbit/Cargo.toml
  iml-services/iml-action-runner/src/main.rs
  iml-services/iml-device/src/error.rs
  iml-services/iml-device/src/lib.rs
  iml-services/iml-journal/src/lib.rs
  iml-services/iml-ostpool/Cargo.toml
  iml-services/iml-ostpool/src/main.rs
  iml-services/iml-service-queue/src/service_queue.rs
  iml-services/iml-stats/src/main.rs
  iml-util/Cargo.toml
  iml-util/util.rs
  iml-wire-types/src/warp_drive.rs
Labels: chore

#2190 Fix error handling syntax
  chroma_core/lib/detection.py
Labels: bug

#2192 Remove Device scanner make command from local build
  vagrant/scripts/install_iml_local.sh
Labels: bug

#2195 Use non-github deps for libzfs crates
  Cargo.lock
  device-scanner/Cargo.lock
  device-scanner/device-scanner-daemon/Cargo.toml
  device-scanner/device-types/Cargo.toml
  device-scanner/zed-enhancer/Cargo.toml
Labels: chore

#2146 agent: Add start/stop resource to rust agent
  iml-agent/src/action_plugins/action_plugin.rs
  iml-agent/src/action_plugins/high_availability/fixtures/crm-mon-complex.xml
  iml-agent/src/action_plugins/high_availability/mod.rs
  iml-agent/src/action_plugins/high_availability/pacemaker.rs
  iml-agent/src/cli.rs
  iml-wire-types/src/lib.rs
Labels: enhancement
